<?php 
$img = "https://carros.seminovosbh.com.br/mitsubishi-l200-2009-2009-2582955-3230ca1e0101b7c9175267c342dc5f3f56c8.jpg";
$img2= "https://carros.seminovosbh.com.br/alfa-romeo-164-1995-1995-2584144-30735681b396dd10bf29b54a7f15106a26fd.jpg";
?>
<section class="section-chat">
    <!-- <h1>CHAT - Area restrita</h1> -->
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-12">
                <div class="row">
                    <div class="list-chats col-12 col-md-4 border-right p-0">
                        <div class="chat bg-white d-flex py-2 px-2 border-bottom">
                            <div class="chat-img mr-2">
                                <img src="<?= $img ?>" alt="" class="img-fluid">
                            </div>
                            <div class="chat-details">
                                <div class="chat-title">
                                    <b>Banco Bateria Pearl...</b>
                                </div>
                                <div class="chat-name mt-1">
                                    <span>
                                        Marcos Júnio
                                    </span>
                                </div>
                                <div class="chat-last-msg mt-1">
                                    <span class="text-gray">
                                        Boa noite, não
                                    </span>
                                </div>
                            </div>
                            <div class="chat-info ml-auto">
                                <div class="chat-date d-flex justify-content-center">
                                    Sex, 5 de Jul
                                </div>
                                <div class="chat-status px-2">
                                    <span> anúncio intaivo</span>
                                </div>
                            </div>
                        </div>
                        <div class="chat bg-white d-flex py-2 px-2 py-1">
                            <div class="chat-img mr-2">
                                <img src="<?= $img2 ?>" alt="" class="img-fluid">
                            </div>
                            <div class="chat-details">
                                <div class="chat-title">
                                    <b>Chimbal aéreo Mapex</b>
                                </div>
                                <div class="chat-name mt-1">
                                    <span>
                                        Marcos Júnio
                                    </span>
                                </div>
                                <div class="chat-last-msg mt-1">
                                    <span class="text-gray">
                                        Boa noite, não
                                    </span>
                                </div>
                            </div>
                            <div class="chat-info ml-auto">
                                <div class="chat-date d-flex justify-content-center">
                                    Sex, 5 de Jul
                                </div>
                                <div class="chat-status px-2">
                                    <span> anúncio intaivo</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-8 bg-white conversation-active invisible">
                        <div class="d-flex d-md-flex w-100 align-items-center justify-content-between">
                            <div class="conversation-info py-2">
                                <div class="conversation-name">
                                    <b>
                                        Marcos Júnio
                                    </b>
                                </div>
                                <div class="conversation-last-access">
                                    último acesso 09/08/2019
                                </div>
                            </div>
                            <div class="d-flex d-md-none chat-back">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </div>
                            <div class="d-block d-md-flex conversation-menu pr-2">
                                <div class="conversation-action mr-md-4 text-center">
                                    <a href="">Ver perfil</a>
                                </div>
                                <div class="conversation-action">
                                    <a href="">Mais opções</a>
                                </div>
                            </div>
                        </div>
                        <div class="conversation bg-light border pt-3 px-3">
                            <div class="divider-date d-flex justify-content-center">
                                <b>Sex, 5 Jul</b>
                            </div>
                            <template>
                                <div class="message my-1 p-2 from-interessado">
                                    <div class="msg px-2 py-1"></div>
                                    <div class="info">
                                        <div class="time"></div>
                                        <div class="seen"></div>
                                    </div>
                                </div>
                                <div class="message my-1 p-2 from-remetente">
                                    <div class="msg px-2 py-1"></div>
                                    <div class="info">
                                        <div class="time"></div>
                                    </div>
                                </div>
                            </template>
                            <div class="message my-1 p-2 from-remetente">
                                <div class="msg px-2 py-1">
                                    Boa noite, não
                                </div>
                                <div class="info">
                                    <div class="time">
                                        21:35
                                    </div>
                                </div>
                            </div>
                            <div class="message my-1 p-2 from-remetente">
                                <div class="msg px-2 py-1">
                                    Boa noite, não
                                </div>
                                <div class="info">
                                    <div class="time">
                                        21:35
                                    </div>
                                </div>
                            </div>
                            <div class="message my-1 p-2 from-interessado">
                                <div class="msg px-2 py-1">
                                    Boa tarde.<br>
                                    Aceita cartão de crédito?
                                </div>
                                <div class="info">
                                    <div class="time">
                                        14:08
                                    </div>
                                    <div class="seen"></div>
                                </div>
                            </div>
                            <div class="message my-1 p-2 from-interessado">
                                <div class="msg px-2 py-1">
                                    Boa tarde.<br>:hamburger:
                                    Aceita cartão de crédito?Aceita cartão de crédito?Aceita cartão de crédito?Aceita
                                    cartão de crédito?Aceita cartão de crédito?Aceita cartão de crédito?Aceita cartão de
                                    crédito?Aceita cartão de crédito?
                                </div>
                                <div class="info">
                                    <div class="time">
                                        14:08
                                    </div>
                                    <div class="seen"></div>
                                </div>
                            </div>

                        </div>
                        <div class="text-area bg-white border closed py-2 pb-5">
                            <div class="d-flex justify-content-center w-100">
                                <textarea name="" id="text_area_chat" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>