<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$this->headTitle('Meus Veículos');
$veiculos = $this->meusVeiculos['data'] ?? []; //idPlano

/* @var $formatDate \AreaRestrita\View\Helper\Data */
$formatDate = new \AreaRestrita\View\Helper\Data();

?>

<div class="container-fluid container-anuncios">
    <div class="row justify-content-center">
        <div class="col-12">
            <h3>Meus Veículos</h3>
        </div>
        <div class="anuncios col-11 col-lg-12 row justify-content-center p-0 m-0">
            <?php foreach ($veiculos as $veiculo):
                $urls = [
                    'editarAnuncio' => $this->url('criar-anuncio', [
                        'tipo' => strtolower($veiculo['tipo']),
                        'idVeiculo' => $veiculo['idVeiculo']
                    ]),
                ];
                           ?>
            <div class="col-12 row mb-3 bg-white p-0 justify-content-center">
                <div class="col-12 col-md-4 col-lg-2 d-flex pt-3 justify-content-center">
                    <a href="/meus-veiculos/<?= $veiculo['idVeiculo'] ?>">
                        <img class="img-fluid" src="<?= $veiculo['imagem'] ?>" alt="" />
                    </a>
                </div>
                <div class="col-12 col-md-8 col-lg-7">
                    <div class="row justify-content-between m-t-10 active px-2 py-2">
                        <div
                            class="justify-content-center row col-12 h-auto justify-content-md-between border-bottom-c border-s-2 border-<?= $veiculo['idPlano']?>-20 pb-2">
                            <p
                                class="col-12 col-md-6 m-0 p-0 text-uppercase h4 text-cinza-escuro d-flex align-items-center">
                                <span class="mr-2">
                                    <?= $veiculo['marca'] . ' ' . $veiculo['modelo'] . ' ' . $veiculo['caracteristica']; ?>
                                </span>
                                <small class="small d-none d-md-block">
                                    <?= $veiculo['motor'] . ' ' . $veiculo['valvula'] . 'V' ?>
                                </small>
                            </p>
                            <h4
                                class="d-flex justify-content-start justify-content-md-end col-12 col-md-6 m-0 p-0 h4 text-cinza-escuro">
                                R$ <?= $veiculo['valorFormatado'] ?>
                            </h4>
                        </div>
                        <div class="col-12 col-lg-6 mt-2">
                            <ul class="h-auto">
                                <li>
                                    Placa:
                                    <span class="text-uppercase"><?= $veiculo['placa'] ?></span>
                                </li>
                                <li>
                                    Cadastrado:
                                    <?php if ($veiculo['dataCadastro'] !== '') {
                                        echo $formatDate->converterDataBR($veiculo['dataCadastro']);
                                    } else {
                                        echo '-';
                                    } ?>
                                </li>
                                <li>
                                    Renovado:
                                    <?php if ($veiculo['dataCadastro'] !== '') {
                                        echo $formatDate->converterDataBR($veiculo['dataRenovacao']);
                                    } else {
                                        echo '-';
                                    } ?>
                                </li>
                                <li>
                                    Kilometragem:
                                    <?= $veiculo['kilometragemFormatada'] ?>
                                </li>
                                <li>
                                    Código:
                                    <?= $veiculo['idVeiculo'] ?>
                                </li>
                            </ul>

                            <div class="btn-group">
                                <?php if($veiculo["botoes"]["excluir"]){?>
                                <a href="#" data-url="/meus-veiculos/excluir/<?= $veiculo['idVeiculo'] ?>" data-modal
                                    data-modal-body="<?= $this->escapeHtmlAttr("Deseja <b>realmente excluir</b> o anúncio <b>{$veiculo['marca']} {$veiculo['modelo']}</b> com a placa <b>{$veiculo['placa']}</b>?") ?>"
                                    data-modal-yes-text="Sim, Excluir" data-modal-success-msg="Veiculo excluído"
                                    title="Excluir anúncio" class="btn btn-danger icon-2 btn-excluir-anuncio">
                                    <i class=" fa fa-trash-o"></i>
                                </a>
                                <?php }?>

                                <?php if($veiculo["botoes"]["editar_dados"]){?>
                                <a href="<?=$urls['editarAnuncio']?>" class="btn bg-cinza text-white icon-2"
                                    title="Editar Anúncio">
                                    <i class=" fa fa-pencil"></i>
                                </a>
                                <?php }?>

                                <?php if($veiculo["botoes"]["editar_fotos"]){?>
                                <a href="<?=$urls['editarAnuncio']?>#fotos" class="btn bg-cinza text-white icon-2"
                                    title="Editar Fotos">
                                    <i class=" fa fa-camera"></i>
                                </a>
                                <?php }?>
                            </div>
                        </div>
                        <div class="col-12 col-md-12 col-lg-3 mt-2  p-0 m-0 row justify-content-center">
                            <!-- <div class="col-6 col-lg-12 mt-1 padding-15  bg-master-lightest">
                                <div class="pl-3 bold no-margin">
                                    <?//= $veiculo['cliques'] ? : 0 ?>
                                 cliques
                                </div>
                            </div>
                            <div class="col-6 col-lg-12 mt-1 padding-15  bg-master-lightest">
                                <div class="pl-3 bold no-margin">
                                    <?//= $veiculo['acessos'] ? : 0 ?>
                                   acessos
                                </div>
                            </div> -->
                            <div class="col-12 col-lg-12 ">
                                <div class="bg-master-lightest  mt-1 padding-15">
                                    <a href="/meus-veiculos/propostas/<?= $veiculo['idVeiculo'] ?>" class="text-dark">
                                        <div class="row d-flex justify-content-between pl-3">
                                            <div class="bold no-margin d-flex align-items-center link-danger">
                                                <span class="fa fa-circle text-success fs-11 mr-1"></span>
                                                Propostas
                                                <?php
                                                /** @todo
                                                *  Trazer o numero de propostas
                                                *  Trazer bolinha verde quando há nova proposta
                                                */
                                            ?>
                                            </div>
                                            <a href="/meus-veiculos/propostas/<?= $veiculo['idVeiculo'] ?>">
                                                <span class=" label bg-verde text-white p-t-3 p-b-3 inline fs-12 mr-2">
                                                    Ver
                                                </span>
                                            </a>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-12 col-lg-3 h-100">
                    <div data-index="0" class="company-stat-box m-t-10 px-4 py-3 bg-master-lightest">
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="pull-left d-flex text-uppercase bold align-items-center mb-0">
                                <span class="fa fa-circle text-p-<?= $veiculo['idPlano'] ?> fs-11 mr-1"></span>
                                <?= $veiculo['nomePlano'] ?>
                            </p>
                            <div>
                                <?php if($veiculo["botoes"]["trocar_plano"]){?>
                                <a href="<?=$urls['editarAnuncio']?>#plano"
                                    class="btn btn-sm btn-info text-white d-flex align-items-center ml-2">Trocar Plano</a>
                                <?php }?>
                                <?php if($veiculo["botoes"]["upgrade_plano"]){?>
                                <a href="<?=$urls['editarAnuncio']?>#plano"
                                    class="btn btn-sm btn-info text-white d-flex align-items-center py-4 ml-2">Melhorar meu Plano</a>
                                <?php }?>
                                <?php if($veiculo["botoes"]["renovar_plano"]){?>
                                <a href="<?=$urls['editarAnuncio']?>#plano"
                                    class="btn btn-sm btn-info text-white d-flex align-items-center">Renovar Plano</a>
                                <?php }?>
                                <?php
                                /** @todo
                                 *  Centralizar verticalmente
                                 */
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="pb-2">
                        <div data-index="0" class="company-stat-box m-t-10 bg-master-lightest active px-4 pt-3 h-100 ">
                            <div class="d-flex justify-content-between">
                                <p
                                    class="company-name pull-left text-uppercase bold no-margin d-flex align-items-center">
                                    <span class="fa fa-circle text-s-<?= $veiculo['idStatus'] ?> fs-11 mr-1"></span>
                                    <?= $veiculo['tituloStatus'] ?>
                                </p>
                            </div>
                            <div class=" d-flex mt-1">
                                <small class="hint-text"><?=$veiculo["frase"]?></small>
                            </div>
                            <?php if($veiculo['idStatus'] != 1): ?>
                                <div class="d-flex mt-1">
                                    <small class="hint-text mt-1">
                                        <?php if ($veiculo["intervaloData"] == 0) { ?>
                                        Expira Hoje
                                        <?php } elseif ($veiculo["intervaloData"] >= 1) { ?>
                                        Expira em <?= $veiculo["intervaloData"] ?> dias
                                        <?php } else { ?>
                                        Expirado em <?= $veiculo["dataExpiracao"] ?>
                                        <?php } ?>
                                    </small>
                                </div>
                            <?php endif; ?>
                            <div class="justify-content-end d-flex m-t-15 pb-2">

                                <?php if($veiculo["botoes"]["enviar_comprovante"]){?>
                                <a href="<?=$urls['editarAnuncio']?>#checkout&comprovante"
                                   class="btn btn-sm btn-cinza text-white d-flex align-items-center ml-2">Enviar comprovante</a>
                                <?php }?>

                                <?php if($veiculo["botoes"]["realizar_pagamento"]){?>
                                    <a href="<?=$urls['editarAnuncio']?>#plano"
                                       class="btn btn-sm bg-verde text-white d-flex align-items-center ml-2">Pagar</a>
                                <?php }?>

                                <?php if(isset($veiculo['botoes']['inativar']) && $veiculo['botoes']['inativar']){?>
                                <a href="#" data-url="/meus-veiculos/inativar/<?= $veiculo['idVeiculo'] ?>" data-modal
                                    data-modal-body="<?= $this->escapeHtmlAttr("Deseja realmente <b>INATIVAR</b> o anúncio <b>{$veiculo['marca']} {$veiculo['modelo']}</b> com a placa <b>{$veiculo['placa']}</b>?") ?>"
                                    data-modal-yes-text="Sim, inativar este veículo!" data-modal-success-msg="Veículo inativado!"
                                    title="Desativar veículo">
                                    <button class="btn btn-sm btn-danger ml-2">Inativar</button>
                                </a>
                                <?php }?>

                                <?php if($veiculo["botoes"]["vendido"]){?>
                                <a href="#" data-url="/meus-veiculos/vendido/<?= $veiculo['idVeiculo'] ?>" data-modal
                                    data-modal-body="<?= $this->escapeHtmlAttr("Deseja realmente marcar como <b>VENDIDO</b> o anúncio <b>{$veiculo['marca']} {$veiculo['modelo']}</b> com a placa <b>{$veiculo['placa']}</b>?") ?>"
                                    data-modal-yes-text="Sim, marcar como vendido!" data-modal-success-msg="Marcado como vendido!"
                                    title="Marcar como vendido">
                                    <button class="btn btn-sm btn-complete ml-2">Vendido</button>
                                </a>
                                <?php }?>


                                <?php if($veiculo["botoes"]["renovar"]){
                                    /**
                                     * @todo O renovar vai mesmo para o ativar?
                                     */
                                    ?>
                                <a href="#" data-url="/meus-veiculos/ativar/<?= $veiculo['idVeiculo'] ?>" data-modal
                                    data-modal-body="<?= $this->escapeHtmlAttr("Deseja <b>realmente renovar</b> o anúncio <b>{$veiculo['marca']} {$veiculo['modelo']}</b> com a placa <b>{$veiculo['placa']}</b>?") ?>"
                                    data-modal-yes-text="Sim, renovar" data-modal-success-msg="Veiculo Renovado"
                                    title="Renovar anúncio">
                                    <button class="btn btn-sm btn-laranja ml-2 ">Renovar</button>
                                </a>
                                <?php }?>

                                <?php if($veiculo["botoes"]["reativar"]){?>
                                <a href="#" data-url="/meus-veiculos/ativar/<?= $veiculo['idVeiculo'] ?>" data-modal
                                    data-modal-body="<?= $this->escapeHtmlAttr("Deseja <b>realmente reativar</b> o anúncio <b>{$veiculo['marca']} {$veiculo['modelo']}</b> com a placa <b>{$veiculo['placa']}</b>?") ?>"
                                    data-modal-yes-text="Sim, reativar" data-modal-success-msg="Veiculo Reativado"
                                    title="Reativar anúncio">
                                    <button class="btn btn-sm btn-laranja text-white ml-2">Reativar</button>
                                </a>
                                <?php }?>
                                <?php if($veiculo["botoes"]["alerta"]){?>

                                <a href="tel://(031) 3077-5888"
                                    class="btn btn-sm btn-laranja text-white d-flex align-items-center my-sm-2 w-100 justify-content-center">
                                    <i class="fa fa-warning text-white"></i>
                                    <span class="pl-2">
                                        LIGUE PARA:
                                        (31) 3077-5888
                                    </span>
                                </a>


                                <?php } ?>
                                <?php
                            /** @todo
                                *  ENVIAR COMPROVANTE
                                */
                            ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
