<?php

use AreaRestrita\View\Helper\AutocompleteClass;

/** @var AutocompleteClass $this */


$dateHelper = $this->dateHelper();

$renderChart = function (
    $data,
    $key,
    $title
) use ($dateHelper) {
    $series = [];

    foreach ($data as $date => $rows) {
        foreach ($rows as $id => $row) {
            $name = $row[$key];
            $series[$name] ??= [
                'name' => $name,
                'data' => [],
            ];
            $series[$name]['data'][] = [
                'x' => $dateHelper->dateToJsTimestamp($date),
                'y' => $row['qtd'],
            ];
        }
    }
?>
    <div id="metricas-por-data-<?= $key ?>" class="collapse w-100" data-parent="#metricas-por-data-container">
        <div class="container-chart"></div>
    </div>
    <script>
        (function() {
            var series = <?= json_encode(array_values($series)); ?>;
            Highcharts.chart(document.querySelector('#metricas-por-data-<?= $key ?> .container-chart'), {
                chart: {
                    type: 'line'
                },
                title: {
                    text: '<?= $title ?>'
                },
                subtitle: {
                    text: 'No último mês na seminovos.com.br'
                },

                xAxis: {
                    type: 'datetime',
                },
                yAxis: [{
                    title: {
                        text: 'Quantidade de buscas'
                    },
                }],
                tooltip: {
                    crosshairs: true,
                    shared: true
                },
                plotOptions: {
                    line: {

                        marker: {
                            enabled: false
                        },
                    },
                    series: {
                        animation: false,

                    }
                },
                series: series

            });
        })();
    </script>
<?php
};
?>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="#metricas-por-data-marca" data-toggle="collapse">
            <h4>Marcas mais buscadas</h4>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#metricas-por-data-modelo" data-toggle="collapse">
            <h4>Modelos mais buscados</h4>
        </a>
    </li>
</ul>
<div id="metricas-por-data-container">
    <?php
    $renderChart($maisAcessados['marca'], 'marca', 'Marcas mais buscadas');
    $renderChart($maisAcessados['modelo'], 'modelo', 'Modelos mais buscados');
    ?>
</div>
