<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $form \Zend\Form\View\Helper\Form */
//echo $this->form($this->formPrecoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formPrecoVeiculo;
    //var_dump($form->getElements());
    $fields = $form->getElements();
    
    $fields['valor']->setAttribute('class', 'input-lg form-control text-center');
    $fields['valor']->setLabelAttributes(['class'=>'form-control-lg']);

?>
<div class=" container-fluid container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                QUAL O VALOR QUE VOCÊ ESTA PEDINDO NO SEU VEÍCULO?
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar seu anúncio.
                    <br/>Campos com * são de preenchimento obrigatório.
                </small>
            </div>
            
            <form method="POST" name="form_precoVeiculo" class="form-group" role="form" id="form_precoVeiculo">
                <div class="row text-center">
                    
                    <div class="form-group-lg form-group form-group-default form-text-center required">
                        <?= $this->formLabel($fields['valor']) ?>
                        <?= $this->formText($fields['valor']) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-group-default">
                            <?= $this->formCheckbox($fields['combinarValor']) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-default">
                            <?= $this->formCheckbox($fields['financiamento']) ?>
                        </div>
                    </div>
                </div>
  
                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>

        </div>
    </div>
</div>