<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $form \Zend\Form\View\Helper\Form */
//echo $this->form($this->formVideoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formVideoVeiculo;
    //var_dump($form->getElements());
    $fields = $form->getElements();
    
    $fields['video']->setAttributes(array('class' =>'form-control'));
    
    /*$fields['valor']->setLabelAttributes(['class'=>'form-control-lg']);*/

?>
<div class=" container-fluid container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                TEM UM VÍDEO DO SEU VEÍCULO?
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">Agora esta na hora de mostrar a sua joia! Se você já preparou o book do seu veículo, 
                    clique no box abaixo, ou arraste para dentro dele, para enviar as fotos que deseja inserir no seu anúncio.
                </small>
            </div>
            
            <form method="POST" name="form_videoVeiculo" class="form-group" role="form" id="form_videoVeiculo">
                    
                <div class="form-group form-group-default ">
                    <?= $this->formLabel($fields['video']) ?>
                    <?= $this->formText($fields['video']) ?>
                </div>

                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>

        </div>
    </div>
</div>