<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$this->headTitle('Contrato');

?>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-10 text-left">
            <h3 class="font-montserrat all-caps hint-text">Contrato de prestação de serviço</h3>
        </div>
    </div>
</div>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">

            <div id="card-advance" class="card-default bg-white border">
                <div class="card-header bg-white border-white">
                    <div class="card-title">CLIENTE, SOLICITAMOS QUE LEIA ATENTAMENTE AO FORMATO DE
                        COBRANÇA DO SISTEMA.
                    </div>
                </div>
                <div class="card-body">
                    <h3><span class="semi-bold">1.</span> Objeto</h3>
                    <p>É objeto do presente contrato a prestação do serviço de hospedagem de
                        anúncios de veículos em
                        nossa página da internet. <br>Esta hospedagem de anúncios inclui a
                        divulgação de fotografias e
                        todas as especificações dos veículos no site, juntamente com as
                        informações pertinentes à
                        revendedora, como o nome, endereço, telefones, e-mail, endereço
                        eletrônico, logomarca e mapa
                        do endereço da loja. </p>
                    <br>
                    <h3><span class="semi-bold">2.</span> Prazo</h3>
                    <p>O contrato tem início no momento da assinatura e/ou pagamento, seguido da
                        inserção dos anúncios
                        e terá duração mínima de 30 dias. <br>
                        O contrato poderá ser cancelado por parte do contratante a qualquer
                        momento, desde que não exista
                        nenhuma pendência financeira.
                    </p>
                    <br>
                    <h3><span class="semi-bold">3.</span> Anúncios</h3>
                    <div class="row">
                        <div class="col-lg-4">
                            <div data-pages="card" class="card card-default" id="card-basic">
                                <div class="card-body">
                                    <h4><span class="semi-bold">Simples</span></h4>
                                    <p>Anúncio com até <strong>06 fotos</strong>, com baixa
                                        prioridade de exibição na busca.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div data-pages="card" class="card card-default" id="card-basic">
                                <div class="card-body">
                                    <h4><span class="semi-bold">Turbo</span></h4>
                                    <p>Anúncio com até <strong>09 fotos</strong>, com prioridade
                                        média de exibição na busca.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div data-pages="card" class="card card-default" id="card-basic">
                                <div class="card-body">
                                    <h4><span class="semi-bold">Nitro</span></h4>
                                    <p>Anúncio , com até <strong>12 fotos</strong>, com prioridade
                                        alta de exibição na busca.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h3><span class="semi-bold">4.</span> Condições</h3>
                    <p>Os planos de anúncio descritos acima podem sofrer alterações em sua
                        composição ou preço em
                        acordo com o combinado entre o Contratante e a SeminovosBH. <br>
                        Em cada plano estará disponível o número correspondente de anúncios,
                        podendo o Contratante
                        administrá-los com as ferramentas do sistema. <br>
                        Dentro do período de validade do plano, o contratante poderá: alterar,
                        incluir, excluir ou
                        substituir qualquer de seus anúncios no site, obedecendo a disponibilidade
                        de anúncios
                        do plano contratado. <br>
                        O Contratante que fizer parte de uma Revendedora de Veículos e estiver
                        anunciando como particular,
                        terá seu(s) anúncio(s) removido(s) deliberadamente (caso comprovada tal
                        ação) sem o ressarcimento
                        dos valores pagos. <br>
                        O Contratante poderá divulgar as informações pertinentes aos seus
                        anúncios, mas não poderá fazer
                        nenhum tipo de sub-locação do espaço, bem como divulgar links ou websites
                        de outra empresas. <br>
                        O Contratante só poderá colocar o endereço eletrônico da sua loja se o
                        site não tiver vínculos
                        com qualquer outro site de revenda ou administrador de anúncios. <br>
                        O Contratante não poderá incluir ou administrar veículos e anúncios de
                        outro(s) revendedor(es). <br>
                        É necessário inclusão das fotos do veículo não sendo permitido fotos
                        ilustrativas ou
                        anúncios de veículos que não estejam na loja. <br>
                        Em caso de cancelamento do plano contratado é necessário contato via email
                        solicitando a suspensão.
                    </p>
                    <br>
                    <h3><span class="semi-bold">5.</span> Tipos de veículos anúnciados</h3>
                    <p>Trabalhamos apenas com divulgação específica de automóveis, motocicletas e
                        caminhões desde que
                        não estejam sinistrados. Infelizmente não publicamos no site veículos
                        batidos, avariados ou
                        sem condições de uso. <br>
                        Não serão aceitos nenhum tipo de serviço anexo ao veiculo publicado, tais
                        como, carta de credito,
                        financiamento, consorcio contemplado ou não, ou qualquer tipo de serviço que
                        não seja
                        especificamente a venda do veiculo em questão. <br>
                        Todo veiculo publicado terá que ser obrigatoriamente informar os dados do
                        veiculo a venda como
                        marca, modelo e versão. Não serão aceitos no campo versão do anúncio , dados
                        que não sejam
                        relacionados a versão específica do veiculo. <br>
                        Não serão permitidos a publicação de imagens com textos, descrições do
                        veiculo ou qualquer
                        informação publicitaria. <br>
                        Só serão permitidos veículos com valores reais do mesmo ou condição verdadeira de compra.
                    </p>
                    <br>
                    <h3><span class="semi-bold">5.1.</span> Veículo de Leilão/Recuperado</h3>
                    <p class="mb-0">É permitida a publicação no portal de anúncios de veículos com passagem por leilão ou recuperados mediante as seguintes regras:</p>
                    <ul class="list-styled mb-0">
                        <li><span>Todos os anúncios devem obrigatoriamente conter informações detalhadas sobre o ocorrido.</span></li>
                        <li><span>É total responsabilidade do anunciante incluir/selecionar no campo especifico “veículo de leilão” no momento da confecção do anúncio, informação de passagem do veículo por leilão.</span></li>
                        <li><span>O veículo deve obrigatoriamente estar em condições de uso de acordo com o Art.27 do CTB (código de trânsito brasileiro)</span></li>
                        <li><span>O veículo em questão deve estar em nome do anunciante ou terceiro devidamente eleito através de procuração pública.</span></li>
                    </ul>
                    <p>Em caso de descumprimento de uma ou mais cláusulas acima, o anúncio será removido sem ressarcimento da importância paga.</p>
                    <br>
                    <h3><span class="semi-bold">6.</span> SEGURANÇA DAS INFORMAÇÕES</h3>
                    <p>
                        Segundo o Art. 18 da lei 13.709, conhecida como Lei Geral de Proteção de Dados Pessoais (LGPD) 
                        um dos direitos do titular de dados, seja no ambiente físico ou virtual, 
                        é a segurança de que suas informações não estão sendo compartilhadas ou 
                        usadas por qualquer meio e com qualquer finalidade sem a sua prévia autorização. <br>
                        O titular passa a ter também maior controle sobre como os seus dados estão sendo utilizados e com que finalidade. <br>
                        Ele poderá ainda, solicitar no website e no Portal que informou seus dados de identificação, a confirmação de tratamento de dados, 
                        a alteração, a remoção ou exclusão de dados, resguardando-se os casos previsto na Lei. <br>
                        Pensando nisso, a Seminovos.com.br procura sempre se atualizar e se adaptar às exigências legais, buscando oferecer um serviço com maior segurança e qualidade para seus usuários. <br>
                        Ao final deste documento, a nossa Equipe disponibiliza links da lei integral em questão e do Código de Defesa do Consumidor, para que você, usuário e internauta, possa também se informar sobre 
                        seus direitos e deveres enquanto titular de dados.
                    </p>
                    <br>
                    <h3><span class="semi-bold">7.</span> Pagamentos</h3>
                    <p>O cliente deve entrar em sua área, clicar em faturamento e gerar o boleto
                        bancário ou efetuar
                        o pagamento por cartão de crédito/debito, lembrando que o pagamento ocorre
                        de forma antecipada.
                        Plano trimestral tem 5% de desconto, plano semestral tem 10% de desconto e o
                        plano anual
                        tem 15% de desconto. <br>
                        Seu contrato permanece ativo conforme plano contratado, sendo necessário
                        efetuar um novo
                        pagamento próximo a data de expiração do plano para que sua loja continue
                        ativa em nosso
                        sistema. Em caso de não pagamento haverá a suspensão do plano e
                        consequentemente dos anúncios.
                    </p>
                    <br>
                    <h3><span class="semi-bold"></span> Resumo</h3>
                    <div class="">
                        <ul class="">
                            <li class="">O contrato tem início no momento do pagamento do plano escolhido,
                                com duração mínima de
                                1 a 12 meses de acordo com seu plano, sendo a vista ou parcelado, o
                                mesmo será prorrogado
                                automaticamente ao final do período mediante a um novo pagamento.
                            </li>
                            <li>O cliente não poderá diminuir o plano de anúncio durante o período
                                contratado e pago.
                            </li>
                            <li>Planos de anuncio pagos só poderão ser diminuídos ao final do
                                período contratado.
                            </li>
                            <li>Caso o cliente queira alterar o seu plano de anúncio para um
                                superior será necessário
                                contato conosco para maiores informações.
                            </li>
                            <li>Não é possível a devolução dos valores pagos mediante a suspensão ou
                                cancelamento do
                                contrato, independente do período pago.
                            </li>
                            <li>Os pagamentos só poderão ser efetuados via crédito, débito ou boleto
                                através da nossa
                                área restrita, não sendo possível outra forma de pagamento.
                            </li>
                            <li>Obrigatoriamente informar os dados do veiculo a venda como marca,
                                modelo e versão.
                                Não serão aceitos no campo versão do anúncio, dados que não sejam
                                relacionados a
                                versão específica do veiculo.
                            </li>
                            <li>Não serão permitidos a publicação de imagens com textos, descrições
                                do veiculo ou
                                qualquer informação publicitaria.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>