<div id="box_concluido">
    <h1>Contrato de prestação de serviço.</h1>
    <h2>Cliente, Solicitamos que leia atentamente ao formato de cobrança do sistema.</h2>

    <br>
    <h2>1. Objeto.</h2>
    É objeto do presente contrato a prestação do serviço de hospedagem de anúncios de veículos em nossa página da
    internet.<br/>
    Esta hospedagem de anúncios inclui a divulgação de fotografias e todas as especificações dos veículos no site,
    juntamente com as informações pertinentes à revendedora, como o nome, endereço, telefones, e-mail, endereço
    eletrônico, logomarca e mapa do endereço da loja.
    <br/><br/><br/>
    <h2>2. Prazo.</h2>
    O contrato tem início no momento da assinatura e/ou pagamento, seguido da inserção dos anúncios e terá
    duração mínima de 30 dias.<br/>
    O mesmo será prorrogado automaticamente a cada período mensal gerando um boleto para pagamento no valor do plano
    contratado.<br/>
    O contrato poderá ser cancelado por parte do contratante a qualquer momento, desde que não exista nenhuma
    pendência financeira.
    <br/><br/><br/>
    <h2>3. Anúncios.</h2>
    Simples.<br/>
    Anúncio com até 06 fotos, com baixa prioridade de exibição na busca.<br/><br/>
    Turbo.<br/>
    Anúncio com até 09 fotos, com prioridade média de exibição na busca.<br/><br/>
    Nitro.<br/>
    Anúncio , com até 12 fotos, com prioridade alta de exibição na busca.
    <br/><br/><br/>
    <h2>4. Condições.</h2>
    Sistema de Ligação de todo Brasil para a loja sem cobrança de interurbano para quem liga.<br/><br/>
    Os planos de anúncio descritos acima podem sofrer alterações em sua composição ou preço em acordo com o
    combinado entre o Contratante e a SeminovosBH.<br/><br/>
    Em cada plano estará disponível o número correspondente de anúncios, podendo o Contratante administrá-los com
    as ferramentas do sistema.<br/><br/>
    Dentro do período de validade do plano, o contratante poderá: alterar, incluir, excluir ou substituir qualquer de
    seus anúncios no site, obedecendo a disponibilidade de anúncios do plano contratado.<br/><br/>
    O Contratante que fizer parte de uma Revendedora de Veículos e estiver anunciando como particular, terá seu(s)
    anúncio(s) removido(s) deliberadamente (caso comprovada tal ação) sem o ressarcimento dos valores
    pagos.<br/><br/>
    O Contratante poderá divulgar as informações pertinentes aos seus anúncios, mas não poderá fazer nenhum tipo
    de sub-locação do espaço, bem como divulgar links ou websites de outra empresas.<br/><br/>
    O Contratante só poderá colocar o endereço eletrônico da sua loja se o site não tiver vínculos com qualquer
    outro site de revenda ou administrador de anúncios.<br/><br/>
    O Contratante não poderá incluir ou administrar veículos e anúncios de outro(s) revendedor(es).<br/><br/>
    É necessário inclusão das fotos do veículo não sendo permitido fotos ilustrativas ou anúncios de veículos que
    não estejam na loja.<br/><br/>
    Em caso de cancelamento do plano contratado é necessário contato via email solicitando a suspensão.
    <br/><br/><br/>
    <h2>5. Tipos de veiculos anunciados</h2>
    Trabalhamos apenas com divulgação específica de automóveis, motocicletas e caminhões desde que não estejam
    sinistrados. Infelizmente não publicamos no site veículos batidos, avariados ou sem condições de uso.<br><br>
    Não serão aceitos nenhum tipo de serviço anexo ao veiculo publicado, tais como, carta de credito, financiamento,
    consorcio contemplado ou não, ou qualquer tipo de serviço que não seja especificamente a venda do veiculo em
    questão.<br><br>
    Todo veiculo publicado terá que ser obrigatoriamente informar os dados do veiculo a venda como marca, modelo e
    versão. Não serão aceitos no campo versão do anúncio , dados que não sejam relacionados a versão específica do
    veiculo.<br><br>
    Não serão permitidos a publicação de imagens com textos, descrições do veiculo ou qualquer informação publicitaria.


    <br/><br/><br/>
    <h2>6. Pagamento.</h2>
    O cliente deve entrar em sua área, clicar em faturamento e gerar o boleto bancário ou efetuar o pagamento por cartão
    de crédito/debito, lembrando que o pagamento ocorre de forma antecipada. Plano trimestral tem 5% de desconto, plano
    semestral tem 10% de desconto e o plano anual tem 15% de desconto. <br><br>
    Seu contrato permanece ativo conforme plano contratado, sendo necessário efetuar um novo pagamento próximo a data de
    expiração do plano para que sua loja continue ativa em nosso sistema. Em caso de não pagamento haverá a suspensão do
    plano e consequentemente dos anúncios.

    <br/><br/><br/>
    <h3>Resumo</h3>
    <ul>
        <li>O contrato tem início no momento do pagamento do plano escolhido, com duração mínima de 1 a 12 meses de
            acordo com seu plano, sendo a vista ou parcelado, o mesmo será prorrogado automaticamente ao final do
            período mediante a um novo pagamento.
        </li>
        <li>O cliente não poderá diminuir o plano de anúncio durante o período contratado e pago.</li>
        <li>Planos de anuncio pagos só poderão ser diminuídos ao final do período contratado.</li>
        <li>Caso o cliente queira alterar o seu plano de anúncio para um superior será necessário contato conosco para
            maiores informações.
        </li>
        <li>Não é possível a devolução dos valores pagos mediante a suspensão ou cancelamento do contrato, independente
            do período pago.
        </li>
        <li>Os pagamentos só poderão ser efetuados via crédito, débito ou boleto através da nossa área restrita, não
            sendo possível outra forma de pagamento.
        </li>
        <li>Obrigatoriamente informar os dados do veiculo a venda como marca, modelo e versão. Não serão aceitos no
            campo versão do anúncio, dados que não sejam relacionados a versão específica do veiculo.
        </li>
        <li>Não serão permitidos a publicação de imagens com textos, descrições do veiculo ou qualquer informação
            publicitaria.
        </li>
    </ul>
</div>