<?php
/* @var $this \Laminas\View\Renderer\PhpRenderer */
$this->headTitle('Dados dos veículos');
$veiculosAll = $this->veiculos;

/* @var $formatDate \AreaRestrita\View\Helper\Data */
$formatDate = new \AreaRestrita\View\Helper\Data();
$nome = $this->userInfo('responsavelNome') ?? $this->userInfo('nomeFantasia') ?? "Não informado"

?>
<input type="hidden" class="data-user-display-name" value="<?=$nome?>">
<input type="hidden" class="data-total-veiculos" value="<?=is_countable($veiculosAll) ? count($veiculosAll) : 0?>">
<input type="hidden" class="data-total-fotos" value="<?=$totalFotos?>">
<div class="container-fluid container-anuncios">
    <div class="row justify-content-center px-3 px-md-0">
        <div class="col mb-3">
            <h3>Dados dos Veículos</h3>
            <div>
                Revise os dados, se necessário, faça as devidas alterações. <br>
                O veículo que a placa já existir, será apagado e inserido novamente.
            </div>
        </div>
        <div class="anuncios col-11 col-lg-12 row justify-content-center p-0 m-0">
            <form id="form-importar" action="/xml/salvar" method="post">
                <?php
                foreach ($veiculosAll as $veiculo):
                    $chave = random_int(0, mt_getrandmax());
                    $urls = [];

                    ?>
                    <input type="hidden" name="veiculos[<?= $chave ?>][tipoVeiculo]" value="<?= $veiculo['tipoVeiculo'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][veiculoZeroKm]" value="<?= $veiculo['veiculoZeroKm'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][idCadastro]" value="<?= $veiculo['idCadastro'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][troca]" value="<?= $veiculo['troca'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][nomePlano]" value="<?= $veiculo['nomePlano'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][idPlano]" value="<?= $veiculo['idPlano'] ?>">
                    <input type="hidden" name="veiculos[<?= $chave ?>][token]" value="1">

                    <div class="col-12 row mb-3 bg-white p-0 pt-2 veiculo" style="border-bottom:1px solid #ccc;">
                            <div class="col-2">
                                <div class="row">
                                    <?php foreach ($veiculo['imagens'] as $imagem) { ?>
                                        <input type="hidden" name="veiculos[<?= $chave ?>][imagens][]" value="<?= $imagem ?>">
                                    <?php }
                                        $numFotosPreview = 6;
                                        for ($i = 0; $i < $numFotosPreview; $i++) { 
                                            if(isset($veiculo['imagens'][$i])) {
                                                echo '<div class="col-6 pb-1 text-center">';
                                                echo '<img class="img-fluid" src="' . $veiculo['imagens'][$i] . '" alt="" />';
                                                echo '</div>';
                                            }
                                        }

                                        ?>
                                
                                        <div class="col-12 text-right">
                                            <small>...mais <?= (is_countable($veiculo['imagens']) ? count($veiculo['imagens']) : 0) - $numFotosPreview <= 0 ? 0 : (is_countable($veiculo['imagens']) ? count($veiculo['imagens']) : 0) - $numFotosPreview ?> imagens</small>
                                        </div>
                                </div>
                            </div>
                            <div class="col-10">
                                <div class="row active">
                                    <div class="col-12  border-bottom--c border-s--1 border-"<?= $veiculo['idPlano'] ?>"-20">
                                        <div class="row veiculo-titulo">
                                            <div class="col-8 text-uppercase h4 text-cinza-escuro marca-modelo">
                                                <input type="text" name="veiculos[<?= $chave ?>][caracteristica]" class="form-control" value="<?= $veiculo['caracteristica'] ?>" style="font-size:18px;" required>
                                            </div>
                                            <div class="col-4 preco">
                                                <div class="form-group input-group">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">R$</span>
                                                    <input type="text" name="veiculos[<?= $chave ?>][valor]" class="form-control" value="<?= $veiculo['valor'] ?>" required onkeyup="formatarValorBr(this)">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                    <div class="col-6 mt-2">
                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Placa:</div>
                                            <div class="col-8"><input type="text" name="veiculos[<?= $chave ?>][placa]" class="form-control" value="<?= $veiculo['placa'] ?>" required></div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Marca:</div>
                                            <div class="col-8">
                                                <select name="veiculos[<?= $chave ?>][marca]" class="form-control" required>
                                                    <?php foreach ($marcas as $marca) { ?>
                                                    <option value="<?= $marca['idMarca'] ?>" <?= isset($veiculo['idMarca']) && $marca['idMarca'] == $veiculo['idMarca'] ? 'selected' : '' ?> ><?= ucwords($marca['marca']) ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Modelo:</div>
                                            <div class="col-8">
                                                <select name="veiculos[<?= $chave ?>][modeloCarro]" class="form-control" required>
                                                    <option value=""><?= $veiculo['modelo'] ?? 'nao encontrado' ?></option>
                                                    <?php foreach ($veiculo['modelos'] as $modelo) { ?>
                                                        <option value="<?= $modelo['idModelo'] ?>" <?= $modelo['idModelo'] == $veiculo['modeloCarro'] ? 'selected' : '' ?>><?= $modelo['modelo'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Kilometragem:</div>
                                            <div class="col-8">
                                                <input type="text" name="veiculos[<?= $chave ?>][kilometragem]" class="form-control" value="<?= $veiculo['kilometragem'] ?>">
                                            </div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Combustível:</div>
                                            <div class="col-8">
                                                <select name="veiculos[<?= $chave ?>][combustivel]" class="form-control">
                                                    <option value="1" <?= $veiculo['combustivel'] == 1 ? 'selected' : '' ?>>Álcool</option>
                                                    <option value="2" <?= $veiculo['combustivel'] == 2 ? 'selected' : '' ?>>Flex</option>
                                                    <option value="3" <?= $veiculo['combustivel'] == 3 ? 'selected' : '' ?>>Diesel</option>
                                                    <option value="4" <?= $veiculo['combustivel'] == 4 ? 'selected' : '' ?>>Gasolina</option>
                                                    <option value="5" <?= $veiculo['combustivel'] == 5 ? 'selected' : '' ?>>Gasolina + Gás</option>
                                                    <option value="6" <?= $veiculo['combustivel'] == 6 ? 'selected' : '' ?>>Gás</option>
                                                    <option value="7" <?= $veiculo['combustivel'] == 7 ? 'selected' : '' ?>>Tetra Combustível</option>
                                                    <option value="8" <?= $veiculo['combustivel'] == 8 ? 'selected' : '' ?>>Gasolina e elétrico</option>
                                                    <option value="9" <?= $veiculo['combustivel'] == 9 ? 'selected' : '' ?>>Álcool + Kit Gás</option>
                                                    <option value="10" <?= $veiculo['combustivel'] == 10 ? 'selected' : '' ?>>Bi-Combustível + Kit Gás</option>
                                                    <option value="11" <?= $veiculo['combustivel'] == 11 ? 'selected' : '' ?>>Elétrico</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-6 col-lg-6 mt-2">
                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Ano Fabricação:</div>
                                            <div class="col-8"><input type="text" name="veiculos[<?= $chave ?>][anoFabricacao]" class="form-control" maxlength="4" value="<?= $veiculo['anoFabricacao'] ?>" required></div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Ano Modelo:</div>
                                            <div class="col-8"><input type="text" name="veiculos[<?= $chave ?>][anoModelo]" class="form-control" maxlength="4" value="<?= $veiculo['anoModelo'] ?>" required></div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Portas:</div>
                                            <div class="col-8">
                                                <input type="number" name="veiculos[<?= $chave ?>][portas]" min="1" max="10" class="form-control" value="<?= $veiculo['portas'] ?? '' ?>">
                                            </div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Cor:</div>
                                            <div class="col-8"><input type="text" name="veiculos[<?= $chave ?>][cor]" class="form-control" value="<?= $veiculo['cor'] ?>"></div>
                                        </div>

                                        <div class="row pb-1">
                                            <div class="col-4 text-right">Motor:</div>
                                            <div class="col-8">
                                                <select name="veiculos[<?= $chave ?>][motor]" class="form-control">
                                                    <option value="1" <?= $veiculo['motor'] == '1.0' ? 'selected' : '' ?>>1.0</option>
                                                    <option value="2" <?= $veiculo['motor'] == '1.6' ? 'selected' : '' ?>>1.6</option>
                                                    <option value="3" <?= $veiculo['motor'] == '1.2' ? 'selected' : '' ?>>1.2</option>
                                                    <option value="4" <?= $veiculo['motor'] == '1.3' ? 'selected' : '' ?>>1.3</option>
                                                    <option value="5" <?= $veiculo['motor'] == '1.4' ? 'selected' : '' ?>>1.4</option>
                                                    <option value="6" <?= $veiculo['motor'] == '1.5' ? 'selected' : '' ?>>1.5</option>
                                                    <option value="7" <?= $veiculo['motor'] == '1.7' ? 'selected' : '' ?>>1.7</option>
                                                    <option value="8" <?= $veiculo['motor'] == '1.8' ? 'selected' : '' ?>>1.8</option>
                                                    <option value="9" <?= $veiculo['motor'] == '1.9' ? 'selected' : '' ?>>1.9</option>
                                                    <option value="10" <?= $veiculo['motor'] == '2.0' ? 'selected' : '' ?>>2.0</option>
                                                    <option value="11" <?= $veiculo['motor'] == '2.1' ? 'selected' : '' ?>>2.1</option>
                                                    <option value="12" <?= $veiculo['motor'] == '2.2' ? 'selected' : '' ?>>2.2</option>
                                                    <option value="13" <?= $veiculo['motor'] == '2.3' ? 'selected' : '' ?>>2.3</option>
                                                    <option value="14" <?= $veiculo['motor'] == '2.4' ? 'selected' : '' ?>>2.4</option>
                                                    <option value="15" <?= $veiculo['motor'] == '2.5' ? 'selected' : '' ?>>2.5</option>
                                                    <option value="16" <?= $veiculo['motor'] == '2.6' ? 'selected' : '' ?>>2.6</option>
                                                    <option value="17" <?= $veiculo['motor'] == '2.7' ? 'selected' : '' ?>>2.7</option>
                                                    <option value="18" <?= $veiculo['motor'] == '2.8' ? 'selected' : '' ?>>2.8</option>
                                                    <option value="19" <?= $veiculo['motor'] == '2.9' ? 'selected' : '' ?>>2.9</option>
                                                    <option value="20" <?= $veiculo['motor'] == '3.0' ? 'selected' : '' ?>>3.0</option>
                                                    <option value="21" <?= $veiculo['motor'] == '3.2' ? 'selected' : '' ?>>3.2</option>
                                                    <option value="22" <?= $veiculo['motor'] == '3.3' ? 'selected' : '' ?>>3.3</option>
                                                    <option value="23" <?= $veiculo['motor'] == '3.4' ? 'selected' : '' ?>>3.4</option>
                                                    <option value="24" <?= $veiculo['motor'] == '3.5' ? 'selected' : '' ?>>3.5</option>
                                                    <option value="25" <?= $veiculo['motor'] == '3.6' ? 'selected' : '' ?>>3.6</option>
                                                    <option value="26" <?= $veiculo['motor'] == '3.7' ? 'selected' : '' ?>>3.7</option>
                                                    <option value="27" <?= $veiculo['motor'] == '3.8' ? 'selected' : '' ?>>3.8</option>
                                                    <option value="28" <?= $veiculo['motor'] == '3.9' ? 'selected' : '' ?>>3.9</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row col-12 col-lg-12 mt-2">
                                <div class="row col-12 d-flex justify-content-center">
                                    <p>
                                        <a href="#acessorios_<?= $veiculo['placa'] ?>" class="btn btn-outline-secondary" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="acessorios">Acessórios</a>
                                        <a href="#observacoes_<?= $veiculo['placa'] ?>" class="btn btn-outline-secondary" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="observacoes">Observações</a>
                                    </p>
                                </div>
                                <div class="row col-12">
                                    <div class="col-12">
                                        <div class="collapse multi-collapse" id="acessorios_<?= $veiculo['placa'] ?>">
                                            <div class="card card-body">
                                                <div class="col-12 row">                                                
                                                    <?php foreach ($acessoriosCarroApi as $acessorio) { ?>
                                                        <div class="col-3 col-lg-3 col-md-2 m-0 p-1">
                                                            <input 
                                                                type="checkbox" 
                                                                id="acessorio_<?= $acessorio['idAcessorio'] ?>" 
                                                                name="veiculos[<?= $chave ?>][listaAcessorios][]" 
                                                                value="<?= $acessorio['idAcessorio'] ?>"
                                                                <?= in_array($acessorio['idAcessorio'], $veiculo['listaAcessorios']) ? 'checked' : '' ?>
                                                            >
                                                            <label for="acessorio_<?= $acessorio['idAcessorio'] ?>"><?= $acessorio['acessorio'] ?></label>
                                                        </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="collapse multi-collapse" id="observacoes_<?= $veiculo['placa'] ?>">
                                            <div class="card card-body">
                                                <textarea name="veiculos[<?= $chave ?>][observacoes]" cols="30" rows="10"><?= $veiculo['observacoes'] ?></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                    
                <?php endforeach; ?>
                <button type="submit" class="btn btn-laranja text-white btn-cons pull-right">Importar Veículos</button>
            </form>
        </div>
    </div>
</div>

<script>
function formatarValorBr(input) {

    var valor = input.value;

    if(valor.length <= 2) {
        input.value = valor.replace(/(\D)/g, '').replace(/(\d{2})/g, '0,$1');
    } else if (valor.length > 2 && valor.length <= 6) {
        input.value = valor.replace(/(\D)/g, '').replace(/^0(.*)/, '$1').replace(/(\d{1,4})(\d{2})/, '$1,$2');
    } else if (valor.length > 5) {
        input.value = valor.replace(/(\D)/g, '').replace(/(\d{1,3})(\d{3})(\d{2})/g, '$1.$2,$3');
    }
}
</script>