<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$dadosCadastro = $this->dadosCadastro;
$dadosPagamento = $this->dadosPagamento;

?>

<div class="d-flex justify-content-center bg-light">
    <div class="py-2">
        <a href="/historico-pagamentos" title="Voltar" class="btn">
            <i class="link-primary fa fa-arrow-circle-left mr-1"></i>
            Voltar
        </a>
        <a href="#" title="Imprimir" class="btn btn-print">
            <i class="link-primary fa fa-print mr-1"></i>
            Imprimir
        </a>
    </div>
</div>

<div class=" container-fluid">
    <div class="card card-default m-t-20">
        <div class="card-body">
            <div class="invoice padding-50 sm-padding-10">
                <div class="d-flex justify-content-between">
                    <div>
                        <img width="135" height="47" alt="" class="invoice-logo"
                            data-src-retina="assets/img/invoice/squarespace2x.png"
                            data-src="assets/img/invoice/squarespace.png" src="/img/svg/snbh_logo.svg">
                    </div>
                    <div class="">
                        <h3 class="font-montserrat all-caps hint-text">FATURA DE SERVIÇOS ELETRÔNICA</h3>

                    </div>
                </div>
                <div class="pull-right mt-3">
                    <div class="d-flex justify-content-between">
                        <span class="font-montserrat bold all-caps">N° :</span>
                        <span>
                            <?= date('Y'); ?>
                            / <?= str_pad($dadosPagamento['idPagamento'], 6, 0, STR_PAD_LEFT); ?>
                        </span>
                    </div>
                    <div class="d-flex justify-content-between">
                        <span class="font-montserrat bold all-caps mr-2">Emitida em :</span>
                        <span class="hora"><?= date('d/m/Y'); ?> às <?= date('H:i:s'); ?></span>
                    </div>
                </div>

            </div>
            <div class="invoice padding-50 py-0">
                <div class="row">
                    <div class="col-6">
                        <div class="border-bottom pb-2">
                            <span>
                                Tomador dos Serviços
                            </span>
                        </div>
                        <h5 class="semi-bold mt-3"><?= $dadosCadastro['responsavelNome'] ?></h5>
                        <div class="row">
                            <address class="col-5">
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        CPF:
                                    </span>
                                    <span class="">
                                        <?= preg_replace('/([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{2})/', '$1.$2.$3-$4', $dadosCadastro['cpfResponsavel']) ?>
                                    </span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        Email:
                                    </span>
                                    <span class="">
                                        <?php
                                    if (!empty($dadosCadastro['email'])) :
                                    echo $dadosCadastro['email'];
                                    else :
                                    echo "Não Informado";
                                    endif;
                                    ?>
                                    </span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        Telefone:
                                    </span>
                                    <span class="">
                                        <?php
                                    if (!empty($dadosCadastro['telefone_1'])) :
                                    echo $dadosCadastro['telefone_1'];
                                    elseif (!empty($dadosCadastro['telefone_2'])) :
                                    echo $dadosCadastro['telefone_2'];
                                    else :
                                    echo "Não Informado";
                                    endif;
                                    ?>
                                    </span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        Cidade:
                                    </span>
                                    <span class="">
                                        <?php
                                    if (!empty($dadosCadastro['idCidade'])) :
                                    echo $dadosCadastro['cidaNome'];
                                    echo !empty($dadosCadastro['idEstado']) ? '/' . $dadosCadastro['sigla'] : '';
                                    endif;
                                    ?>
                                    </span>
                                </div>
                            </address>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="border-bottom pb-2">
                            <span>
                                Prestador dos Serviços
                            </span>
                        </div>
                        <h5 class="semi-bold mt-3">SEMINOVOS LTDA</h5>
                        <div class="row">
                            <address class="col-5">
                                <!-- <div class="d-flex justify-content-between">
                                    <address class="m-t-10">
                                        Rua Níquel, 11-a, Serra - Belo Horizonte/MG - CEP: 30240-020 - (31) 3077-5888
                                    </address>
                                </div> -->
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        CNPJ:
                                    </span>
                                    <span class="">
                                        0919816/001-5
                                    </span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="all-caps">
                                        Insc. Municipal:
                                    </span>
                                    <span class="">
                                        0919816/001-5
                                    </span>
                                </div>
                                <div class="mt-2">
                                    <span class="">
                                        Rua Níquel, 11-a, Serra
                                    </span>
                                    <div>
                                        Belo Horizonte/MG - CEP: 30240-020
                                    </div>
                                </div>
                            </address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>