<?php

/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headTitle('Repasse Seminovos');


$veiculos = $this->veiculos;



?>


<div class="container-fluid container-anuncios">
    <div class="row justify-content-center px-2 px-md-0">
        <div class="col-sm-12 col-md-6 my-2 d-flex">
            <h3>Repasse Seminovos</h3>
        </div>
        <div class="col-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="/repasse/meus-anuncios" class="col-12 btn btn-info">Meus Repasses</a>
        </div>
        <div class="col-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="/repasse/anuncio" class="col-12 btn btn-info">Novo Anúncio</a>
        </div>
    </div>

    <form>
        <div class="form-row">
            <div class="col-12 col-md-6">
                <div class="form-row mx-1 mx-md-0">
                    <div class="col">
                        <div class="form-group">
                            <label for="cidade">Filtrar por Cidade</label>
                            <input type="text" class="form-control" id="cidade" name="city"
                                placeholder="Ex.: Belo Horizonte">
                        </div>
                    </div>
                    <div class="form-group col">
                        <label for="marcaModelo">Filtrar por Marca/modelo</label>
                        <input type="text" class="form-control" id="marcaModelo" name="search" placeholder="Ex.: Civic">
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="form-row mx-1">
                    <div class="form-group col">
                        <label for="preco">Filtrar por Preço</label>
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="De" name="precoDe" id="precoDe">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Até" name="precoAte" id="precoAte">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col">
                        <label for="ano">Filtrar por Ano</label>
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="De" name="anoDe" id="anoDe">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Até" name="anoAte" id="anoAte">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-2 col-xl-1 d-flex align-items-end">
                <div class="form-group w-100 mx-2 mx-md-0">
                    <button class="btn btn-primary btn-block p-1" type="submit">Filtrar</button>
                </div>
            </div>
        </div>
    </form>
    <hr>
    <div class="row">
        <div class="card-deck col-12 mt-2 row-cols-md-4 row-cols-1 d-flex flex-wrap">
            <?php
            foreach ($veiculos['data'] as $key => $veiculo):
            ?>
                <div class="col mb-1">
                    <div class="card h-100 d-flex">
                        <div class="card-img-container">

                            <img src="<?= $veiculo['url'] ?>" alt="<?= $veiculo['marca'] . ' ' . $veiculo['modelo'] ?>" class="card-img-top img-thumbnail img-fluid">

                        </div>
                        <div class="card-body d-flex flex-column justify-content-end">
                            <h5 class="card-title text-uppercase h4 text-cinza-escuro marca-modelo"><?= $veiculo['marca'] . ' ' . $veiculo['modelo'] ?></h5>
                            <div class="card-text">
                                <h4 class="d-flex flex-wrap">
                                    <span class="mr-3 mr-md-0"> R$
                                        <?= number_format($veiculo['valor'], 2, ',', '.') ?>
                                    </span>
                                </h4>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Ano:
                                    <span class="text-uppercase"><?= $veiculo['ano_fabricacao'] . '/' . $veiculo['ano_modelo'] ?></span>
                                </li>
                                <li class="list-group-item">
                                    Placa:
                                    <span class="text-uppercase"><?= $veiculo['placa'] ?></span>
                                </li>
                                <li class="list-group-item">
                                    Data do Cadastro:
                                    <span class="text-uppercase"><?= (new DateTime($veiculo['data_cadastro']))->format('d/m/Y') ?> </span>
                                </li>
                            </ul>
                            <div class="btn-group d-flex justify-content-around">
                                <a href="#modalFotos" class="btn btn-laranja text-white mx-1 p-1 w-100"
                                    title="Fotos" data-toggle="modal" data-id-veiculo="<?= $veiculo['idRepasse'] ?>">
                                    <i class=" fa fa-camera"></i>
                                    <span>Fotos</span>
                                </a>
                                <a href="#modalContato" class="btn btn-laranja text-white p-1 w-100"
                                    title="Contato" data-toggle="modal" data-id-veiculo="<?= $veiculo['idRepasse'] ?>">
                                    <i class=" fa fa-user"></i>
                                    <span>Contato</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

    </div>
    <div class="col-md-12">
        <?php
        if ($veiculos) {
            //echo $this->partial('partials/pagination.phtml', $this->paginationData);
        }
        ?>
    </div>
</div>
