<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headTitle('Repasse Seminovos');


$veiculos = $this->veiculos;
$meta = $this -> meta;

?>

<div class="modal fade" tabindex="-1" role="document" aria-labelledby="modalFotos" id="modalFotos" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-fotos modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title text-uppercase h4 text-cinza-escuro marca-modelo">Fotos</h4>
        </div>
        <div class="modal-body">
                <div class="card-deck" id="deck-fotos">
                </div>
        </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modalContato" tabindex="-1" role="dialog" aria-labelledby="Contato" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="TituloModalCentralizado">Contato</h5>
      </div>
      <div class="modal-body">
        <ul class="list-group list-group-flush">
          <li id="nome" class="list-group-item">Nome: </li>
          <li id="empresa" class="list-group-item">Empresa: </li>
          <li id="cidade" class="list-group-item">Cidade/Estado: </li>
          <li id="telefone" class="list-group-item">Telefone: </li>
          <li id="detalhes" class="list-group-item">Detalhes do Veículo: </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn bg-cinza text-white" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid container-anuncios">
    <div class="row justify-content-center px-2 px-md-0">
        <div class="col-sm-12 col-md-6 my-2 d-flex">
            <h3>Repasse Seminovos</h3>
        </div>
        <div class="col-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="/repasse/meus-anuncios" class="col-12 btn btn-info">Meus Repasses</a>
        </div>
        <div class="col-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="/repasse/anuncio" class="col-12 btn btn-info">Novo Anúncio</a>
        </div>
    </div>

    <form>
        <div class="form-row">
            <div class="col-12 col-md-6">
                <div class="form-row mx-1 mx-md-0">
                    <div class="col">
                        <div class="form-group">
                            <label for="cidade">Filtrar por Cidade</label>
                            <input type="text" class="form-control" id="cidade" name="city"
                                placeholder="Ex.: Belo Horizonte">
                        </div>
                    </div>
                    <div class="form-group col">
                        <label for="marcaModelo">Filtrar por Marca/modelo</label>
                        <input type="text" class="form-control" id="marcaModelo" name="search" placeholder="Ex.: Civic">
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="form-row mx-1">
                    <div class="form-group col">
                        <label for="preco">Filtrar por Preço</label>
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="De" name="precoDe" id="precoDe">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Até" name="precoAte" id="precoAte">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col">
                        <label for="ano">Filtrar por Ano</label>
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="De" name="anoDe" id="anoDe">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Até" name="anoAte" id="anoAte">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-2 col-xl-1 d-flex align-items-end">
                <div class="form-group w-100 mx-2 mx-md-0">
                    <button class="btn btn-primary btn-block p-1" type="submit">Filtrar</button>
                </div>
            </div>
        </div>
    </form>
    <hr>
    <div class="row">
        <div class="card-deck col-12 mt-2 row-cols-md-4 row-cols-1 d-flex flex-wrap">
            <?php
            foreach ($veiculos as $key => $veiculo):
            ?>
            <div class="col mb-1">
                <div class="card h-100 d-flex">
                    <div class="card-img-container">
                        <?php if (!$veiculo['pictures']): ?>
                            <img src="https://placehold.co/600x400?text=Sem+Fotos" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid">
                        <?php else: ?>
                            <img src="<?= $veiculo['pictures'][0]['full_path']?>" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid">
                        <?php endif; ?>
                    </div>
                    <div class="card-body d-flex flex-column justify-content-end">
                        <h5 class="card-title text-uppercase h4 text-cinza-escuro marca-modelo"><?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?></h5>
                        <div class="card-text">
                            <h4 class="d-flex flex-wrap">
                                <span class="mr-3 mr-md-0"> R$
                                <?= number_format($veiculo['courier_value_sale'], 2, ',', '.') ?>
                                </span>
                            </h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                Ano:
                                <span class="text-uppercase"><?= $veiculo['creation_year'] ?></span>
                            </li>
                            <li class="list-group-item">
                                Placa:
                                <span class="text-uppercase"><?= $veiculo['license_plate']?></span>
                            </li>
                            <li class="list-group-item">
                                Data do Cadastro:
                                <span class="text-uppercase"><?= $veiculo['created_at'] ?> </span>
                            </li>
                        </ul>
                        <div class="btn-group d-flex justify-content-around">
                            <a href="#modalFotos" class="btn btn-laranja text-white mx-1 p-1 w-100"
                                title="Fotos" data-toggle="modal" data-id-veiculo = "<?= $veiculo['id']?>">
                                <i class=" fa fa-camera"></i>
                                <span>Fotos</span>
                            </a>
                            <a href="#modalContato" class="btn btn-laranja text-white p-1 w-100"
                                title="Contato" data-toggle="modal" data-id-veiculo="<?= $veiculo['id']?>">
                                <i class=" fa fa-user"></i>
                                <span>Contato</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

    </div>
    <div class="col-md-12">
                <?php
                if ($veiculos) {
                    echo $this->partial('partials/pagination.phtml', $this->paginationData);
                }
                ?>
    </div>
</div>
