<?php
/* @var $this \Laminas\View\Renderer\PhpRenderer */
$this->headTitle('Meus Anúncios');

$veiculos = $this->veiculos;
$meta = $this -> meta;

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6 my-2 d-flex">
            <h3>Meus Anúncios</h3>
        </div>
        <div class="col-sm-12 col-md-6 my-2 d-flex align-items-center justify-content-end">
        <a href="/repasse" class="btn btn-info mx-2">Todos os Anúncios</button>
        <a href="/repasse/anuncio" class="btn btn-info">Novo Anúncio</a>
        </div>
    </div>
    <?php if($meta['total'] == 0):  ?>
    <div class="row d-flex justify-content-center">
        <h4>Sem anúncios disponíveis</h4>
    </div>
    <?php else: ?>
        <div class="row">
        <div class="card-deck col-12 mt-2">
            <?php
            foreach ($veiculos as $key => $veiculo): 
            ?>
            <div class="col-sm-4 mb-1">
                <div class="card" style="height: 520px; width: 320px">
                    <?php if (!$veiculo['pictures']): ?>
                    <img src="https://placehold.co/600x400?text=Sem+Fotos" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid" style="height: 190px;">
                    <?php else: ?>
                    <img src="<?= $veiculo['pictures'][0]['full_path']?>" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid" style="height: 190px;">
                    <?php endif; ?>
                    <div class="card-body">
                        <h5 class="card-title text-uppercase h4 text-cinza-escuro marca-modelo"><?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?></h5>
                        <div class="card-text">
                            <h4 class="d-flex flex-wrap">
                                <span class="mr-3 mr-md-0"> R$
                                <?= number_format($veiculo['courier_value_sale'], 2, ',', '.') ?>
                                </span>
                            </h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                Ano:
                                <span class="text-uppercase"><?= $veiculo['creation_year'] ?></span> 
                            </li>
                            <li class="list-group-item">
                                Placa:
                                <span class="text-uppercase"><?= $veiculo['license_plate']?></span>
                            </li>
                            <li class="list-group-item">
                                Data do Cadastro:
                                <span class="text-uppercase"><?= $veiculo['created_at'] ?> </span>
                            </li>
                        </ul>
                        <div class="btn-group">
                            <a href="/repasse/<?= $veiculo['id'] ?>/editar" class="btn bg-cinza text-white icon-2 btn-acao-editar-fotos"
                            title="Editar">
                            <i class=" fa fa-edit"></i><span> Editar</span>
                            </a>

                            <?php if ($veiculo['status'] == 2): ?>
                            <span class="badge badge-success mx-2">Vendido</span>
                            <?php endif; ?>    
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif ?>
    </div>
    <div class="col-md-12">
                <?php
                if ($veiculos) {
                    echo $this->partial('partials/pagination.phtml', $this->paginationData);
                }
                ?>
    </div>
</div>