<?php
/* @var $this \Laminas\View\Renderer\PhpRenderer */
$this->headTitle('Meus Anúncios');

$veiculos = $this->veiculos;
$meta = $this -> meta;

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6 my-2 d-flex">
            <h3>Meus Anúncios</h3>
        </div>
        <div class="col-sm-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="repasse" class="col-sm-12 btn btn-info">Todos os Anúncios</a>
        </div>
        <div class="col-sm-12 col-md-3 my-2 d-flex align-items-center justify-content-end">
            <a href="repasse/anuncio" class="col-sm-12 btn btn-info">Novo Anúncio</a>
        </div>
    </div>
    <?php if($meta['total'] == 0):  ?>
    <div class="row d-flex justify-content-center">
        <h4>Sem anúncios disponíveis</h4>
    </div>
    <?php else: ?>
        <div class="row">
        <div class="card-deck col-12 mt-2 row-cols-md-3 row-cols-1">
            <?php
            foreach ($veiculos as $key => $veiculo): 
            ?>
            <div class="col mb-1">
                <div class="card h-100">
                    <div style="position: relative; padding-top: 100%; width: 100%">
                        <?php if (!$veiculo['pictures']): ?>
                            <img src="https://placehold.co/600x400?text=Sem+Fotos" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover">
                        <?php else: ?>
                            <img src="<?= $veiculo['pictures'][0]['full_path']?>" alt="<?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?>" class="card-img-top img-thumbnail img-fluid" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover">
                        <?php endif; ?>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-uppercase h4 text-cinza-escuro marca-modelo"><?= $veiculo['courier_brand'] .' ' . $veiculo['courier_model'] ?></h5>
                        <div class="card-text">
                            <h4 class="d-flex flex-wrap">
                                <span class="mr-3 mr-md-0"> R$
                                <?= number_format($veiculo['courier_value_sale'], 2, ',', '.') ?>
                                </span>
                            </h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                Ano:
                                <span class="text-uppercase"><?= $veiculo['creation_year'] ?></span> 
                            </li>
                            <li class="list-group-item">
                                Placa:
                                <span class="text-uppercase"><?= $veiculo['license_plate']?></span>
                            </li>
                            <li class="list-group-item">
                                Data do Cadastro:
                                <span class="text-uppercase"><?= $veiculo['created_at'] ?> </span>
                            </li>
                        </ul>
                        <div class="btn-group">
                            <a href="/repasse/<?= $veiculo['id'] ?>/editar" class="btn text-white btn-laranja"
                            title="Editar">
                            <i class=" fa fa-edit"></i><span> Editar</span>
                            </a>

                            <?php if ($veiculo['status'] == 2): ?>
                            <span class="badge badge-success mx-2">Vendido</span>
                            <?php endif; ?>    
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif ?>
    </div>
    <div class="col-md-12">
                <?php
                if ($veiculos) {
                    echo $this->partial('partials/pagination.phtml', $this->paginationData);
                }
                ?>
    </div>
</div>