version: '3'
services:
    snbh-area-restrita:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: snbh-area-restrita
        ports:
            - "8093:80"
        volumes:
            - .:/home/www-data
        environment:
            - APPLICATION_ENV=development
            - SNBH_API_HOST=http://api2homolog.seminovosbh.com.br
            - SNBH_URL_SITE=http://localhost:8091