version: '3'
services:
    snbh-area-restrita:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                - SESSION_PHP_COOKIE_DOMAIN=dev.seminovos.com.br
                - SESSION_PHP_SAVE_HANDLER=redis
                - SESSION_SAVE_PATH=tcp://snbh-area-restrita-redis:6379?weight=1&timeout=1
        container_name: snbh-area-restrita
        ports:
            - "8093:80"
        volumes:
            - .:/home/www-data
        environment:
            - APPLICATION_ENV=development
            - SNBH_API_HOST=http://dev.seminovos.com.br:8081
            - SNBH_URL_SITE=http://dev.seminovos.com.br:8091
            - SESSION_SAVE_PATH=tcp://snbh-area-restrita-redis:6379?weight=1&timeout=1
    snbh-area-restrita-redis:
        image: redis:5.0.4
        container_name: snbh-area-restrita-redis
        ports:
        - "6378:6379"

