name: seminovos-area-restrita
services:
    snbh-area-restrita:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                - SESSION_PHP_COOKIE_DOMAIN=
                - SESSION_PHP_SAVE_HANDLER=redis
                - SESSION_SAVE_PATH=tcp://snbh-area-restrita-redis:6379?weight=1&timeout=1
        image: snbh/area-restrita
        container_name: snbh-area-restrita
        hostname: meus-anuncios
        ports:
            - "8093:80"
        environment:
            - APPLICATION_ENV=development
            - SNBH_API_HOST=http://snbh-api
            - SNBH_URL_SITE=http://localhost:8091
            - SNBH_URL_CHAT=http://localhost:8094
            - SESSION_SAVE_PATH=tcp://snbh-area-restrita-redis:6379?weight=1&timeout=1
        volumes:
            - .:/home/www-data
        networks:
            - snbh-network
    snbh-area-restrita-redis:
        image: redis:7-alpine
        container_name: snbh-area-restrita-redis
        ports:
            - "6378:6379"
        networks:
            - snbh-network
networks: 
    snbh-network:
        name: snbh-network
        driver: bridge
