version: '3'
services:
    snbh-area-restrita-production:
        build: 
            context: .
            dockerfile: DockerfileProduction
            args:
                - SESSION_PHP_SAVE_HANDLER=redis
                - SESSION_SAVE_PATH=tcp://session.ugt1op.ng.0001.usw2.cache.amazonaws.com:6379?weight=1&timeout=1
        container_name: snbh-area-restrita-production
        image: area-restrita
        ports:
            - "8093:80"
        environment:
            - APPLICATION_ENV=production
            - SNBH_API_HOST=http://api2.seminovos.com.br
            - SNBH_URL_AREA_RESTRITA=https://meus-anuncios.seminovosbh.com.br
