<?php
$fields = $formLogin->getElements();
$formLogin->prepare();
?>


<form method="POST" name="login-particular-form" class="form-horizontal" role="form" id="login-particular-form">
    <?= $this->formHidden($fields['type']) ?>
    <?= $this->formHidden($fields['tipoCadastro']) ?>
    <div class="form-group">
        <?= $this->formLabel($fields['usuarioEmail']) ?>
        <div>
            <?= $this->formEmail($fields['usuarioEmail']) ?>
        </div>
    </div>
    <div class="form-group mb-2">
        <?= $this->formLabel($fields['usuarioSenha']) ?>
        <div class="input-group group-senha">
            <?= $this->formElement($formLogin->get('usuarioSenha')) ?>
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="fa fa-eye-slash" aria-hidden="true"></i></div>
            </div>
        </div>
    </div>
    <div class="esqueci-senha text-right">
        <a href="#" data-toggle="modal" data-target="#modalLembrarSenha" class="btn-esqueci-minha-senha link-laranja">
            Esqueci minha senha
        </a>
    </div>
    <div class="form-group">
        <div class="">
            <?= $this->formElement($formLogin->get('entrar')) ?>
        </div>
    </div>
</form>