<!-- Modal -->
<div class="modal fade" id="modalErroSenha" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção</b></h5>
                <div class="mt-4 text-left">
                    <p>Usuário e/ou Senha estão incorretos</p>
                    <p>Confira os campos de usuário e senha e tente novamente</p>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalCuidado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção!!</b></h5>
                <div class="mt-4 text-left">
                    <p>Detectamos Ações Maliciosas!!</p>
                    <p>Sua sessão foi inválidada faça login novamente e tenha cuidado com o que tenta acessar!</p>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
        </div>
    </div>
</div>

<!-- Modal lembrar senha email/cpf -->
<div class="modal fade" id="modalLembrarSenha" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaLabel"
     aria-hidden="true">
    <form method="POST" name="formLembrarSenha" id="formLembrarSenha" action="remember-pass">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header py-2">
                    <h5 class="modal-title text-warning" id="modalLembrarSenhaLabel">Esqueci minha senha</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Não lembra sua senha? Digite o e-mail ou CPF cadastrado do portal no campo abaixo, para
                                    receber sua nova senha!</p>
                            </div>
                        </div>
                        <div class="row pb-2">
                            <div class="form-group col-12">
                                <div class="col-md-12 no-padding sm-p-l-10">
                                    <div class="input-group">
                                        <input type="text" id="emailLembrarSenha" name="emailLembrarSenha" class="form-control" id="inlineFormInputGroup" placeholder="Email ou CPF">
                                    </div>
                                    <p class="text-justify mt-2"> 
                                        Não lembro ou não possuo meu e-mail e CPF. <br>
                                        <a href="#" data-toggle="modal" onclick="fecharModal('modalLembrarSenha')" data-target="#modalLembrarSenhaTelefone" class="text-info btn-esqueci-minha-senha semi-bold">
                                            <span class="semi-bold"></span>
                                            Recuperar via telefone
                                        </a>
                                    </p>


                                </div>
                            </div>
                        </div>
                        <div class="row border-top py-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p class="text-justify">Ao solicitar uma nova senha o site enviará a nova senha para
                                    o e-mail cadastrado, se não receber o e-mail na sua caixa de entrada verifique
                                    na sua caixa de lixo eletrônico (spam).</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Modal recuperar senha via telefone -->
<div class="modal fade" id="modalLembrarSenhaTelefone" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaTelefoneLabel"
     aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header py-2">
                    <h5 class="modal-title text-warning" id="modalLembrarSenhaTelefoneLabel">Esqueci minha senha</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!-- Passo 1 - solicitar e enviar o token por sms ao usuario -->
                <div class="modal-body" id="passo1">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Insira seu telefone:</p>
                            </div>
                        </div>
                        <div class="row pb-2">
                            <div class="form-group col-12">
                                <div class="col-md-12 no-padding sm-p-l-10">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">+55</div>
                                        </div>
                                        <input type="text" 
                                            id="lembrarSenhaTelefone" 
                                            name="lembrarSenhaTelefone" 
                                            class="form-control" 
                                            placeholder="Telefone" 
                                            onkeyup="mascaraTelefone(this.value)"
                                            maxlength="16">
                                        </div>
                                        <p class="text-muted small mt-2 text-danger" id="telefone_invalido" style="display:none;">Não foi encontrado um cadastro com esse número de telefone!</p>
                                </div>
                            </div>
                        </div>
                        <div class="row border-top py-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p class="text-justify">Ao solicitar um token o site enviará um código para o telefone
                                    cadastrado. O código pode demorar ate 1 hora para ser enviado, mas geralmente é na mesma hora.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Passo 2 - Validar token -->
                <div class="modal-body" id="passo2" style="display:none">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Insira o código de 4 digitos:</p>
                            </div>
                        </div>
                        <div class="row pb-2">
                            <div class="form-group col-12">
                                <div class="col-md-12 no-padding sm-p-l-10">
                                    <div class="input-group">
                                        <input type="text" 
                                            id="token" 
                                            name="token" 
                                            class="form-control" 
                                            placeholder="X X X X" 
                                            maxlength="4">
                                        </div>
                                    <p class="text-muted small mt-2 text-danger" id="token_invalido" style="display:none;">Código inválido!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Passo 3 - Nova Senha -->
                <div class="modal-body" id="passo3" style="display:none">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Digite uma nova senha. Sua senha deve conter pelo menos 4 caracteres.</p>
                            </div>
                        </div>
                        <div class="row pb-2">
                            <div class="form-group col-12">
                                <div class="col-md-12 no-padding sm-p-l-10">
                                        <input type="hidden" 
                                            id="idCadastro" 
                                            name="idCadastro" 
                                            value=""
                                            >
                                        <input type="text" 
                                            id="senha" 
                                            name="senha" 
                                            class="form-control row col-12" 
                                            placeholder="Nova Senha" 
                                            >

                                        <input type="text" 
                                            id="confirmacao_senha" 
                                            name="confirmacao_senha" 
                                            class="form-control row col-12 mt-4" 
                                            placeholder="Repetir senha" 
                                            >
                                        </div>
                                    <p class="text-muted small mt-2 text-danger" style="display:none;">senha inválida!</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Passo 4 - Conclusão -->
                <div class="modal-body" id="passo4" style="display:none">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Sua senha foi alterada com sucesso!</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" id="footer_passo1">
                    <button type="button" class="btn-warning btn" onclick="mudarPasso('passo2')">Ja tenho um código</button>
                    <button type="button" class="btn btn-success" onclick="solicitarToken()">Solicitar código</button>
                </div>
                <div class="modal-footer" id="footer_passo2" style="display:none;">
                    <button type="button" class="btn-warning btn" onclick="mudarPasso('passo1')">Voltar</button>
                    <button type="button" class="btn btn-success" onclick="validarToken()">Enviar</button>
                </div>
                <div class="modal-footer" id="footer_passo3" style="display:none;">
                    <button type="button" class="btn-warning btn" onclick="mudarPasso('passo2')">Voltar</button>
                    <button type="button" class="btn btn-success" onclick="salvarNovaSenha()">Salvar nova senha</button>
                </div>
                <div class="modal-footer" id="footer_passo4" style="display:none;">
                    <button type="button" class="btn btn-success float-right" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">Fazer login</span>
                    </button>
                </div>
            </div>
        </div>
</div>

<!-- Modal email enviado -->
<div class="modal fade" id="modalEmailEnviado" tabindex="-1" role="dialog" aria-labelledby="modalEmailEnviadoLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h5 class="modal-title text-warning" id="modalLembrarSenhaLabel">Senha Enviada</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row py-2">
                        <div class="col-md-12 no-padding sm-p-l-10">
                            <p class="text-justify">
                                A senha foi enviada para o e-mail: <b><span id="emailEnviado"></span></b> <br>
                                Caso não possua esse e-mail clique em
                                <a href="javascript:void(0);" data-toggle="modal" onclick="fecharModal('modalEmailEnviado')" data-target="#modalLembrarSenhaTelefone" class="text-info btn-esqueci-minha-senha semi-bold">
                                    <span class="semi-bold"></span>
                                    recuperar por SMS/telefone
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal lembrar senha revenda -->
<div class="modal fade" id="modalLembrarSenhaRevenda" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaLabelRevenda"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h5 class="modal-title text-warning" id="modalLembrarSenhaLabel">Esqueci minha senha</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row py-2">
                        <div class="col-md-12 no-padding sm-p-l-10">
                            <p class="text-justify">
                                Entre em contato com nosso atendimento para recuperar sua senha de acesso.<br>
                                Lembre-se de ter os dados da sua revenda em mãos.<br>
                                Telefone do nosso atendimento: <a href="tel:+553130775888">(31) 3077-5888</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function solicitarToken() {
        var telefone = document.getElementById('lembrarSenhaTelefone').value;
        telefone = telefone.replace(/\D/g, '');

        if (telefone == '') {
            alert('Preencha o telefone');
            return false;
        }

        let formData = new FormData();
        formData.append("telefone", telefone);

        fetch('/remember-pass-phone', {
                method: 'POST',
                body: formData
            })
            .then((response) => {
                return response.json();
            
            })
            .then((response) => {
                if (response.status == 201) {
                    mudarPasso('passo2');
                } else {
                    document.getElementById('telefone_invalido').style.display = 'block';
                }
            })
            .catch(function (error) {
                console.log("Error: " + error);
            });
    }

    function validarToken() {
        var token = document.getElementById('token').value;
        let formData = new FormData();
        formData.append("token", token);

        fetch('/validate-token', {
                method: 'POST',
                body: formData
            })
            .then((response) => {
                return response.json();
            
            })
            .then((response) => {
                if (response.data.token == token) {
                    document.getElementById('idCadastro').value = response.data.idCadastro;
                    mudarPasso('passo3');
                } else {
                    document.getElementById('token_invalido').style.display = 'block';
                }
            })
            .catch(function (error) {
                console.log("Error: " + error);
            });
    }


    function salvarNovaSenha() {
        var senha = document.getElementById('senha').value;
        var confirmacao_senha = document.getElementById('confirmacao_senha').value;
        var idCadastro = document.getElementById('idCadastro').value;

        if (senha != '' && senha != confirmacao_senha) {
            alert('senhas não coincidem');
            return false;
        }

        if (senha.length < 4) {
            alert('A senha deve conter no mínimo 4 caracteres.');
            return false;
        }

        let formData = new FormData();
        formData.append("senha", senha);
        formData.append("idCadastro", idCadastro);

        fetch('/remember-pass-save', {
                method: 'POST',
                body: formData
            })
            .then((response) => {
                return response.json();
            
            })
            .then((response) => {
                if(response.status == 200) {
                    mudarPasso('passo4');
                }
            })
            .catch(function (error) {
                console.log("Error: " + error);
            });
    }

    function mudarPasso(passoAtual) {
        for (let i = 1; i <= 4; i++) {
            let passoTemp = 'passo' + i;

            if(passoAtual == passoTemp) {
                document.getElementById(passoAtual).style.display = 'block';
                document.getElementById('footer_' + passoAtual).style.display = 'block';
            } else {
                document.getElementById(passoTemp).style.display = 'none';
                document.getElementById('footer_' + passoTemp).style.display = 'none';
            }
        } 
    }

    function mascaraTelefone(telefone) {
        telefone = telefone.replace(/\D/g, '');
        telefone = telefone.replace(/(\d{1,2})?(\d{1})?(\d{1,4})?(\d{4})?/, '($1) $2 $3-$4');
        document.getElementById('lembrarSenhaTelefone').value = telefone;
    }

    function fecharModal(modal) {
        $('#' + modal).modal('hide');
    }
</script>


