<!-- Modal -->
<div class="modal fade" id="modalErroSenha" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção</b></h5>
                <div class="mt-4 text-left">
                    <p>Usuário e/ou Senha estão incorretos</p>
                    <p>Confira os campos de usuário e senha e tente novamente</p>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalCuidado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção!!</b></h5>
                <div class="mt-4 text-left">
                    <p>Detectamos Ações Maliciosas!!</p>
                    <p>Sua sessão foi inválidada faça login novamente e tenha cuidado com o que tenta acessar!</p>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modalLembrarSenha" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaLabel"
     aria-hidden="true">
    <form method="POST" name="formLembrarSenha" id="formLembrarSenha" action="remember-pass">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header py-2">
                    <h5 class="modal-title text-warning" id="modalLembrarSenhaLabel">Esqueci minha senha</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row pt-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p>Não lembra sua senha? Digite o e-mail cadastrado do portal no campo abaixo, para
                                    receber sua nova senha!</p>
                            </div>
                        </div>
                        <div class="row pb-2">
                            <div class="form-group col-12">
                                <div class="col-md-12 no-padding sm-p-l-10">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">@</div>
                                        </div>
                                        <input type="email" id="emailLembrarSenha" name="emailLembrarSenha" class="form-control" id="inlineFormInputGroup" placeholder="Email">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row border-top py-2">
                            <div class="col-md-12 no-padding sm-p-l-10">
                                <p class="text-justify">Ao solicitar uma nova senha o site enviará a nova senha para
                                    o e-mail cadastrado, se não receber o e-mail na sua caixa de entrada verifique
                                    na sua caixa de lixo eletrônico (spam).</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="modalLembrarSenhaRevenda" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaLabelRevenda"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h5 class="modal-title text-warning" id="modalLembrarSenhaLabel">Esqueci minha senha</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row py-2">
                        <div class="col-md-12 no-padding sm-p-l-10">
                            <p class="text-justify">
                                Entre em contato com nosso atendimento para recuperar sua senha de acesso.<br>
                                Lembre-se de ter os dados da sua revenda em mãos.<br>
                                Telefone do nosso atendimento: <a href="tel:+553130775888">(31) 3077-5888</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
