<div class="conteudo d-flex justify-content-center">
    <div class="selecionar-tipo">
        <h5 class="text-center">
            Selecione o tipo
        </h5>
        <div class="d-flex justify-content-center">
            <a class="link-tipo" data-confirm href="/carro">
                <div>
                    <i class="fa-2x icon icon-type-car-2"></i><br>
                    Carro
                </div>
            </a>
            <a class="link-tipo" data-confirm href="/moto">
                <div>
                    <i class="fa-2x icon icon-type-moto-2"></i><br>
                    Moto
                </div>
            </a>
            <a class="link-tipo" data-confirm href="/caminhao">
                <div>
                    <i class="fa-2x icon icon-type-truck-2"></i><br>
                    Caminhão
                </div>
            </a>
        </div>
    </div>
</div>
