<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Zend\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\DadosForm */
$form = $this->formDadosVeiculos;
$fields = $form->getElements();

foreach ($fields as $element) {
    if ($element->getAttribute('name') != 'checkboxacessorios' && $element->getAttribute('name') != 'veiculo_zero_km' && $element->getAttribute('name') != 'motoTrilha' && $element->getAttribute('name') != 'flag_km')
        $element->setAttribute('class', 'form-control');
}

$form->setAttribute('class', 'form');

$tipoVeiculo = $form->get('tipoVeiculo')->getValue();

$versao = $form->get('versao')->getValue();
?>
<div class="container">
    <h4 class="text-center">
        Vamos aos dados do seu anúncio?
    </h4>
    
    <div class="conteudo">
        <form method="POST" name="form_dadosVeiculo" class="needs-validation forms" role="form" id="form_dadosVeiculo">
            <?= $this->formElement($fields['tipoVeiculo']) ?>
            <div class="d-flex justify-content-between">
                <div class="form-group form-group-default required placa">
                    <div class="flex-wrap placa-container align-items-center">
                        <div class="w-25">
                            <?= $this->formLabel($fields['placa']) ?>
                            <?= $this->formText($fields['placa']) ?>
                        </div>

                        <div class="field pl-1 pl-md-3 w-75">
                            <?php if(isset($fields['motoTrilha'])): ?>
                                <div class="d-flex justify-content-end align-items-center">
                                    <b class="mr-2">
                                        Moto de trilha?
                                    </b>
                                    <label class="switch">
                                        <?= $this->formElement($fields['motoTrilha']->setLabel('')) ?>
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                            <?php endif; ?>
                            <div class="d-flex justify-content-end align-items-center">
                                <b class="mr-2">
                                    Veículo 0KM sem placa?
                                </b>
                                <label class="switch switch-success">
                                    <?= $this->formElement($fields['veiculo_zero_km']->setLabel('')) ?>
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                        <div class="valid-feedback"></div>
                        <div class="invalid-feedback">
                            Esta placa já está cadastrada no nosso sistema.
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-default required">
                <?= $this->formLabel($fields['idMarca']) ?>
                <div><?= $this->formSelect($fields['idMarca']) ?></div>
            </div>
            <div class="form-group form-group-default required">
                <?= $this->formLabel($fields['modeloCarro']) ?>
                <div><?= $this->formSelect($fields['modeloCarro']) ?></div>
            </div>
            <div class="d-flex justify-content-between conjunto-ano">
                <div class="form-group form-group-default required">
                    <?= $this->formLabel($fields['anoFabricacao']) ?>
                    <div><?= $this->formSelect($fields['anoFabricacao']) ?></div>
                </div>
                <div class="form-group form-group-default required">
                    <?= $this->formLabel($fields['anoModelo']) ?>
                    <div><?= $this->formSelect($fields['anoModelo']) ?></div>
                </div>
            </div>
            <div class="form-group form-group-default required ">
                <?= $this->formLabel($fields['versao']) ?>
                <div><?= $this->formElement($fields['versao']) ?></div>
            </div>
            <div id="divOutraVersao" class="form-group form-group-default hide">
                <label for="outraVersao">Outra Versão? Qual?</label>
                <div>
                    <input type="text" name="outraVersao" placeholder="Digite a versão" class="form-control" value autocomplete="off" maxlength="50">
                </div>
            </div>

            <?php if(isset($fields['motor']) && isset($fields['idValvula'])): ?>
                <div class="d-flex justify-content-between conjunto-motor">
                    
                    <div class="form-group form-group-default required">
                        <?= $this->formLabel($fields['motor']) ?>
                        <div><?= $this->formSelect($fields['motor']) ?></div>
                    </div>
                    <div class="form-group form-group-default">
                        <?= $this->formLabel($fields['idValvula']) ?>
                        <div><?= $this->formSelect($fields['idValvula']) ?></div>
                    </div>
                </div>
            <?php endif; ?>


            <?php if($tipoVeiculo === 1) : ?>
                <div class="form-group form-group-default required">
                    <label for="cambio">Câmbio</label>

                    <div>
                        <select name="checkboxacessorios[]" required="required" class="form-control">
                            <option value="">Selecione</option>
                            <option value="11" <?= $cambio === 11 ? 'selected="selected"' : '' ?>>Automático</option>
                            <option value="78" <?= $cambio === 78 ? 'selected="selected"' : '' ?>>Automatizado</option>
                            <option value="60" <?= $cambio === 60 ? 'selected="selected"' : '' ?>>Manual</option>
                        </select>
                    </div>
                </div>
            <?php endif ?>

            <div class="d-flex justify-content-between conjunto-motor">
                <?php if(isset($fields['motoCilindradas'])): ?>
                    <div class="form-group form-group-default required ">
                        <?= $this->formLabel($fields['motoCilindradas']) ?>
                        <div><?= $this->formElement($fields['motoCilindradas']) ?></div>
                    </div>
                <?php endif; ?>


                <div class="form-group form-group-default required">
                    <?= $this->formLabel($fields['cor']) ?>
                    <div><?= $this->formSelect($fields['cor']) ?></div>
                </div>

                <?php if(isset($fields['portas'])): ?>
                    <div class="form-group form-group-default required">
                        <?= $this->formLabel($fields['portas']) ?>
                        <div><?= $this->formSelect($fields['portas']) ?></div>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-group form-group-default required">
                <?= $this->formLabel($fields['combustivel']) ?>
                <div><?= $this->formSelect($fields['combustivel']) ?></div>
            </div>

            <div class="d-flex justify-content-between w-100 conjunto-leilao">
                <b class="mr-3">
                    Este veículo é proveniente de leilão?
                </b>
                <label class="switch">
                    <?= $this->formElement($fields['flagLeilao']->setLabel('')) ?>
                    <span class="slider round"></span>
                </label>
            </div>

            <?php if($tipoVeiculo == 2): ?>
                <div class="destaques pt-1 pb-3">
                    <div class="text-center"><b>Algum item que você quer destacar?</b></div>

                    <div class="opcionais">
                        <?php
                            $destaques = [
                                $this->formCheckbox($fields['flagIpva']),
                            ];
                            
                            if(isset($fields['adaptado'])) {
                                $destaques[] = $this->formCheckbox($fields['adaptado']);
                            }

                            foreach ($destaques as $key => $value) {
                                $value = str_replace('class="checkbox"', 'class="checkbox-custom"', $value);

                                $value = str_replace('</label>', '<i class="fa fa-check" aria-hidden="true"></i></label>', $value);

                                $value = explode('<div', $value);
                                if (trim($value[0]) == '') {
                                    unset($value[0]);
                                } ?>

                                <div class="checkbox-custom">
                                    <?= $value[0] ?>
                                </div>
                            <?php
                            }
                        ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="form-group ">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>