<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Zend\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\DadosForm */
$form = $this->formDadosVeiculos;
$fields = $form->getElements();

foreach ($fields as $element) {
    if ($element->getAttribute('name') != 'checkboxacessorios' && $element->getAttribute('name') != 'veiculo_zero_km' && $element->getAttribute('name') != 'motoTrilha' && $element->getAttribute('name') != 'flag_km')
        $element->setAttribute('class', 'form-control');
}

$form->setAttribute('class', 'form');

$tipoVeiculo = $form->get('tipoVeiculo')->getValue();

$versao = $form->get('versao')->getValue();
?>

<div class="container">
    <h4 class="text-center">
        Vamos aos dados do seu anúncio?
    </h4>
    <div class="conteudo">
        <form method="POST" name="form_dadosVeiculo" class="needs-validation forms" role="form" id="form_dadosVeiculo">
            <?= $this->formElement($fields['tipoVeiculo']) ?>
            <div class="d-flex justify-content-between">
                <div class="form-group form-group-default required placa">
                    <div class=""><?= $this->formLabel($fields['placa']) ?></div>
                    <div class="flex-wrap placa-container">
                        <?= $this->formText($fields['placa']) ?>

                        <div class="checkbox">
                            <?= $this->formCheckbox($fields['veiculo_zero_km']) ?>
                        </div>
                        <div class="valid-feedback"></div>
                        <div class="invalid-feedback">
                            Esta placa já está cadastrada no nosso sistema.
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-default required ">
                <?= $this->formLabel($fields['idMarca']) ?>
                <div><?= $this->formSelect($fields['idMarca']) ?></div>
            </div>
            <div class="form-group form-group-default required ">
                <?= $this->formLabel($fields['modeloCarro']) ?>
                <div><?= $this->formSelect($fields['modeloCarro']) ?></div>
            </div>
            <div class="form-group form-group-default required">
                <?= $this->formLabel($fields['anoFabricacao']) ?>
                <div><?= $this->formSelect($fields['anoFabricacao']) ?></div>
            </div>
            <div class="form-group form-group-default required">
                <?= $this->formLabel($fields['anoModelo']) ?>
                <div><?= $this->formSelect($fields['anoModelo']) ?></div>
            </div>
            <div class="form-group form-group-default required ">
                <?= $this->formLabel($fields['versao']) ?>
                <div><?= $this->formElement($fields['versao']) ?></div>
            </div>
            <div class="form-group form-group-default">
                <?= $this->formLabel($fields['cor']) ?>
                <div><?= $this->formSelect($fields['cor']) ?></div>
            </div>
            <div class="form-group ">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>