<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Zend\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\DadosForm */
$form = $this->formDadosVeiculos;
$fields = $form->getElements();

foreach ($fields as $element) {
    if ($element->getAttribute('name') != 'checkboxacessorios' && $element->getAttribute('name') != 'veiculo_zero_km' && $element->getAttribute('name') != 'flag_km')
        $element->setAttribute('class', 'form-control');
}

$form->setAttribute('class', 'form');

$tipoVeiculo = $form->get('tipoVeiculo')->getValue();

$versao = $form->get('versao')->getValue();
?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                DADOS DO ANÚNCIO
            </h4>
            <div class="text-center my-3">
                <small class="align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar
                    seu anúncio.
                    <br />Campos com * são de preenchimento obrigatório.
                </small>
            </div>

            <!-- <? $this->form()->openTag($form); ?>

            <form class="" role="form"> -->
            <form method="POST" name="form_dadosVeiculo" class="form-group m-b-20 needs-validation" role="form" id="form_dadosVeiculo">
                <?= $this->formElement($fields['tipoVeiculo']) ?>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-group-default required">
                            <?= $this->formLabel($fields['placa']) ?>
                            <?= $this->formText($fields['placa']) ?>
                            <div class="valid-feedback"></div>
                            <div class="invalid-feedback">
                                Esta placa já está cadastrada no nosso sistema.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-default">
                            <div class="checkbox">
                                <?= $this->formCheckbox($fields['veiculo_zero_km']) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-group-default required ">
                            <?= $this->formLabel($fields['idMarca']) ?>
                            <?= $this->formSelect($fields['idMarca']) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-default required ">
                            <?= $this->formLabel($fields['modeloCarro']) ?>
                            <?= $this->formSelect($fields['modeloCarro']) ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-group-default required">
                            <?= $this->formLabel($fields['anoFabricacao']) ?>
                            <?= $this->formSelect($fields['anoFabricacao']) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-default required">
                            <?= $this->formLabel($fields['anoModelo']) ?>
                            <?= $this->formSelect($fields['anoModelo']) ?>
                        </div>
                    </div>
                </div>
                <div class="form-group form-group-default required ">
                    <?= $this->formLabel($fields['versao']) ?>
                    <?= $this->formElement($fields['versao']) ?>
                </div>
                <div id="divOutraVersao" class="form-group form-group-default hide required">
                    <label for="outraVersao">Versão</label>
                    <input type="text" name="outraVersao" placeholder="Digite a versão" class="form-control" value autocomplete="off">
                </div>
                <div class="row">
                    <?php if (isset($fields['motor'])): ?>
                        <div class="col-md-6">
                            <div class="form-group form-group-default required">
                                <?= $this->formLabel($fields['motor']) ?>
                                <?= $this->formSelect($fields['motor']) ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if (isset($fields['idValvula'])): ?>
                        <div class="col-md-6">
                            <div class="form-group form-group-default">
                                <?= $this->formLabel($fields['idValvula']) ?>
                                <?= $this->formSelect($fields['idValvula']) ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="row">
                    <?php if (isset($fields['portas'])): ?>
                        <div class="col-md-6">
                            <div class="form-group form-group-default required">
                                <?= $this->formLabel($fields['portas']) ?>
                                <?= $this->formSelect($fields['portas']) ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if (isset($fields['motoCilindradas'])): ?>
                    <div class="col-md-6">
                        <div class="form-group form-group-default required">
                            <?= $this->formLabel($fields['motoCilindradas']) ?>
                            <?= $this->formText($fields['motoCilindradas']) ?>
                        </div>
                    </div>
                    <?php endif;?>
                    <div class="col-md-6">
                        <div class="form-group form-group-default">
                            <?= $this->formLabel($fields['cor']) ?>
                            <?= $this->formSelect($fields['cor']) ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group form-group-default required">
                            <?= $this->formLabel($fields['combustivel']) ?>
                            <?= $this->formSelect($fields['combustivel']) ?>
                        </div>
                    </div>
                    <div class="col-12 col-md-3">
                        <div class="form-group form-group-default">
                            <?= $this->formLabel($fields['kilometragem']) ?>
                            <?= $this->formText($fields['kilometragem']) ?>
                        </div>
                    </div>
                    <div class="col-12 col-md-3">
                        <div class="form-group form-group-default">
                            <div class="checkbox">
                                <?= $this->formCheckbox($fields['flag_km']) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if ($tipoVeiculo !== \SnBH\ApiModel\Model\VeiculoTipo::TIPO_CAMINHAO) : ?>
                    <h5 class="text-center">
                        Acessórios
                    </h5>
                    <?php if ($tipoVeiculo === \SnBH\ApiModel\Model\VeiculoTipo::TIPO_CARRO) : ?>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group form-group-default form-troca required">
                                <label for="checkboxacessorioss mb-2">Câmbio</label>
                                <div class="mt-2 mb-0 d-block d-md-flex align-items-center">
                                    <div class="d-flex mr-5 align-items-center radio radio-success mt-0 mb-0">
                                        <input type="radio" name="checkboxacessorios[]" required="required" class="form-control" value="11" <?= $cambio === 11 ? 'checked' : '' ?> id="Automatico_0f7b">
                                        <label for="Automatico_0f7b">Automático</label>
                                    </div>
                                    <div class="d-flex mr-5 align-items-center radio radio-success mt-0 mb-0">
                                        <input type="radio" name="checkboxacessorios[]" required="required" class="form-control" value="78" <?= $cambio === 78 ? 'checked' : '' ?> id="Automatizado_25cc">
                                        <label for="Automatizado_25cc">Automatizado</label>
                                    </div>
                                    <div class="d-flex mr-5 align-items-center radio radio-success mt-0 mb-0">
                                        <input type="radio" name="checkboxacessorios[]" required="required" class="form-control" value="60" <?= $cambio === 60 ? 'checked' : '' ?> id="Manual_e1ba">
                                        <label for="Manual_e1ba">Manual</label>
                                    </div>
                                </div>                        
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="form-group form-group-default" id="dadosAcessorios">
                        <div class="d-flex justify-content-between">
                            <?= $this->formLabel($fields['checkboxacessorios']) ?>
                            <div id="btnCompleto" title="Marcar todos os acessórios de um carro completo.">
                                <?php if ($tipoVeiculo == 1) : ?>
                                    <div class="checkbox m-0 p-0 m-b-0">
                                        <input type="checkbox" id="completoCheckbox">
                                        <label for="completoCheckbox">Completo</label>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php
                        // Gambiarra monstra pra mostrar o checkbox em 3 colunas :)
                        $acessoriosHTML = $this->formMultiCheckbox($fields['checkboxacessorios']);

                        $acessoriosHTML = explode('<div', $acessoriosHTML);

                        if (trim($acessoriosHTML[0]) == '') {
                            unset($acessoriosHTML[0]);
                        }
                        $t = "\t";
                        echo '<div class="row">' . PHP_EOL;
                        foreach ($acessoriosHTML as $key => $acessorio) {
                            echo $t . '<div class="col-6">' . PHP_EOL;
                            echo $t . $t . '<div' . $acessorio . PHP_EOL;
                            echo $t . '</div>' . PHP_EOL;
                            if ($key % 2 === 0) {
                                echo '</div>' . PHP_EOL . PHP_EOL;
                                echo '<div class="row">' . PHP_EOL;
                            }
                        }
                        echo '</div>' . PHP_EOL;

                        ?>
                    </div>
                <?php endif; ?>
                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>
        </div>
    </div>
</div>