<?php
$fotosNewKeys = [];

foreach ($fotos as $k => $foto) {
    $fotosNewKeys[(int) $foto['ordem']] = $foto;
}
$fotos = $fotosNewKeys;
unset($foto, $fotosNewKeys);
?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">
            <h4 class="text-center">
                FOTOS DO SEU VEÍCULO
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">
                    Agora está na hora de mostrar a sua joia! Se você já preparou o book do
                    seu veículo, clique no box abaixo,
                    <!--ou arraste para dentro dele, -->
                    para enviar as fotos que deseja inserir no seu anúncio.
                </small>
            </div>
            <div class="alert alert-warning d-flex align-items-center w-100" role="alert">
                <i class="text-danger icon icon-alert icon-20 mr-4 mr-md-2"></i>
                <div class="w-100 d-block d-md-flex">
                    <div class="text-sm-center text-md-left mr-2">
                        Importante !
                    </div>
                    <div class="">
                        <small class="align-center">
                            As fotos serão salvas após clicar no botão <b>*continuar/finalizar</b>
                        </small>
                    </div>    
                </div>
            </div>

            <form>
                <?php
                /**
                 * @todo Futuramente essa funcionalidade vai ser liberada
                 */
                    if (!$existeVeiculo):
                ?>
                    <!-- <div class="form-group-lg form-group form-group-default form-text-center">
                        <label class="form-control-lg" for="fotos">
                            Clique em um dos espaços abaixo para selecionar <b>uma foto</b>
                        </label>
                    </div> 
                    <div class="h1 text-center">ou</div> -->
                    <div class="form-group-lg form-group form-group-default form-text-center">
                        <label class="form-control-lg" for="fotos">
                            Clique aqui para escolher <b>várias fotos</b>:
                            <input type="file" id="fotos" name="fotos" multiple accept="image/jpg, image/jpeg"
                                   class="hidden" />
                        </label>
                    </div>
                <?php endif; ?>
                <input type="file" name="foto" accept="image/jpg, image/jpeg" class="hidden" />
                <div class=" container">
                    <div class="fotos-container">
                        <div class="row">
                            <?php
                            $count = 0;
                            $default = array(
                                'idFoto' => null,
                                'idVeiculo' => null,
                                'foto' => null,
                                'ordem' => null,
                                'imagem' => 'https://placehold.it/262x196&text=Enviar%20Foto',
                            );
                            foreach (range(0, 2) as $i):

                                ?>
                                <?php
                                foreach (range(0, 3) as $i):
                                    $count++;
                                    $foto = $fotos[$count] ?? $default;
                                    $foto_ = $foto['imagem'];
                                    ?>
                                    <div class="foto col-6 col-md-3 col-sm-6 py-2">
                                        <div class="foto-container">
                                            <div class="display-img img-thumbnail" style="background-image: url('<?= $foto_ ?>')"
                                                 data-posicao-rotacao=0
                                                 data-idfoto="<?= $foto['idFoto'] ?>"
                                                 data-placeholder="https://placehold.it/262x196&text=Enviar%20Foto"
                                                 data-original="<?= $foto['imagem'] ?>" title="Enviar Foto"></div>
                                        </div>

                                        <div class="text-justify">
                                            <a href="#" class="btn-upload-img btn btn-small text-success px-2" title="Adicionar nova foto">
                                                <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                                            </a>
                                            <a href="#" class="btn-remove-img btn btn-small text-danger px-2" title="Remover foto">
                                                <i class=" fa fa-trash-o"></i>
                                            </a>
                                            <a href="#" class="btn-move btn btn-small text-danger px-2" title="Arraste para reordenar">
                                                <i class="fa fa-arrows" aria-hidden="true"></i>
                                            </a>
                                            <a href="#" class="btn-to-rotate btn btn-small text-warning px-2" title="Girar imagem">
                                                <i class="fa fa-refresh" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

                <div class="form-group ">
                    <input type="submit">
                </div>
            </form>

        </div>
    </div>
</div>