<?php
$fotosNewKeys = [];

foreach ($fotos as $k => $foto) {
    $fotosNewKeys[(int) $foto['ordem']] = $foto;
}
$fotos = $fotosNewKeys;
unset($foto, $fotosNewKeys);
?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">
            <h4 class="text-center">
                Hora de mostrar o seu veículo, anúncios com fotos despertam mais interesse!
            </h4>
            
            <?php /*
            <div class="text-center my-3">
                <small class="my-3 align-center">
                </small>
            </div>
            <div class="alert alert-warning d-flex align-items-center w-100" role="alert">
                <i class="text-danger icon icon-alert icon-20 mr-4 mr-md-2"></i>
                <div class="w-100 d-block d-md-flex">
                    <div class="text-sm-center text-md-left mr-2">
                        Importante !
                    </div>
                    <div class="">
                        <small class="align-center">
                            As fotos serão salvas após clicar no botão <b>*continuar/finalizar</b>
                        </small>
                    </div>    
                </div>
            </div> */?>

            <form>
                <?php
                /**
                 * @todo Futuramente essa funcionalidade vai ser liberada
                 */
                    if (!$existeVeiculo):
                ?>
                    <!-- <div class="form-group-lg form-group form-group-default form-text-center">
                        <label class="form-control-lg" for="fotos">
                            Clique em um dos espaços abaixo para selecionar <b>uma foto</b>
                        </label>
                    </div> 
                    <div class="h1 text-center">ou</div> -->
                    <div class="mult-imagens w-100 d-flex justify-content-end">
                        <label class="d-flex m-0" for="fotos" title="Enviar multiplas fotos">
                            <div class="icones">
                                <i class="fa fa-picture-o" aria-hidden="true"></i>
                                <i class="fa fa-picture-o" aria-hidden="true"></i>
                            </div>
                            Multiplas imagens
                            <input type="file" id="fotos" name="fotos" multiple accept="image/*" class="hidden" />
                        </label>
                    </div>
                <?php endif; ?>
                <input type="file" name="foto" accept="image/*" class="hidden" />
                <div class=" container">
                    <div class="fotos-container">
                        <div class="row">
                            <?php
                            $count = 0;
                            $default = array(
                                'idFoto' => null,
                                'idVeiculo' => null,
                                'foto' => null,
                                'ordem' => null,
                                'imagem' => 'https://placehold.it/262x196&text=Enviar%20Foto',
                            );
                            foreach (range(0, 2) as $i):

                                ?>
                                <?php
                                foreach (range(0, 4) as $i):
                                    $count++;
                                    $default['imagem'] = "/img/placeholder_criar_anuncio/carro_$count.png";
                                    $foto = $fotos[$count] ?? $default;
                                    $isDefault = ($fotos[$count] ?? false) ? false : true; 
                                    $foto_ = $foto['imagem'];
                                    ?>
                                    <div class="foto col-6 col-md-3 col-sm-6 py-2">

                                        <div class="controls controls-sup <?= $isDefault ? 'd-none' : '' ?>">
                                            <a href="#" class="btn-upload-img text-black" title="Adicionar nova foto">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </a>

                                            <a href="#" class="btn-move text-verde" title="Arraste para reordenar">
                                                <i class="fa fa-arrows" aria-hidden="true"></i>
                                            </a>
                                        </div>

                                        <div class="foto-container">
                                            <?/*<div class="fundo <?= $foto['idFoto'] ? 'd-none' :''?>"> 
                                                <img class="display-img img-thumbnail" src="" alt="" srcset="">
                                            </div>*/?>
                                            <div class="display-img img-thumbnail" style="background-image: url('<?= $foto_ ?>')"
                                                data-posicao-rotacao=0
                                                data-idfoto="<?= $foto['idFoto'] ?>"
                                                data-placeholder="/img/placeholder_criar_anuncio/carro_<?=$count?>.png"
                                                data-original="<?= $foto['imagem'] ?>" title="Enviar Foto"></div>
                                        </div>

                                        <div class="btn-adicionar <?= $isDefault ? '' : 'd-none' ?>" title="Adicionar nova foto">
                                            <a href="#" class="btn-upload-img" title="Adicionar nova foto">
                                                <i class="fa fa-plus" aria-hidden="true"></i>
                                            </a>
                                        </div>

                                        <div class="controls <?= $isDefault ? 'd-none' : '' ?>">
                                            <a href="#" class="btn-remove-img text-danger px-2" title="Remover foto">
                                                <i class="fa fa-times" aria-hidden="true"></i>
                                            </a>
                                            <a href="#" class="btn-to-rotate text-verde" title="Girar imagem">
                                                <i class="fa fa-retweet" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

                <div class="form-group ">
                    <input type="submit">
                </div>
            </form>

        </div>
    </div>
</div>