<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">
            <h4 class="text-center">
                FOTOS DO SEU VEÍCULO
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">
                    Agora esta na hora de mostrar a sua joia! Se você já preparou o book do
                    seu veículo, clique no box abaixo,
                    <!--ou arraste para dentro dele, -->
                    para enviar as fotos que deseja inserir no seu anúncio.
                </small>
            </div>

            <form>
                <?php
                /**
                 * @todo Futuramente essa funcionalidade vai ser liberada
                 */
                if (false):
                    ?>
                <div class="form-group-lg form-group form-group-default form-text-center">
                    <label class="form-control-lg" for="fotos">
                        Clique em um dos espaços abaixo para selecionar <b>uma foto</b>
                    </label>
                </div>
                <div class="h1 text-center">ou</div>
                <div class="form-group-lg form-group form-group-default form-text-center">
                    <label class="form-control-lg" for="fotos">
                        Clique aqui para escolher <b>várias fotos</b>:
                        <input type="file" id="fotos" name="fotos" multiple accept="image/jpg, image/jpeg"
                            class="hidden" />
                    </label>
                </div>
                <?php endif;?>
                <input type="file" name="foto" accept="image/jpg, image/jpeg" class="hidden" />
                <div class=" container">
                    <div class="fotos-container">
                        <?php
                        $count = -1;
                        $default = array(
                            'idFoto' => null,
                            'idVeiculo' => null,
                            'foto' => null,
                            'ordem' => null,
                            'imagem' => 'https://placehold.it/262x196&text=Enviar%20Foto',
                        );
                        foreach (range(0, 2) as $i):

                            ?>
                        <div class="row">
                            <?php
                                foreach (range(0, 3) as $i):
                                    $count++;
                                    $foto = $fotos[$count] ?? $default;
                                    $foto_ = $foto['imagem'];
                                    ?>
                            <div class="foto col-md-3 col-sm-6 py-2">
                                <div class="display-img img-thumbnail" style="background-image: url('<?= $foto_ ?>')"
                                    data-idfoto="<?= $foto['idFoto'] ?>"
                                    data-placeholder="https://placehold.it/262x196&text=Enviar%20Foto"
                                    data-original="<?= $foto['imagem'] ?>" title="Enviar Foto"></div>
                                
                                <div class="text-justify">
                                    <a href="#" class="btn-upload-img btn btn-small text-success px-2" title="Adicionar nova foto">
                                        <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                                    </a>
                                    <a href="#" class="btn-restaurar-img btn btn-small text-primary px-2" title="Restaurar foto">
                                        <i class="fa fa-history" aria-hidden="true"></i>
                                    </a>
                                    <a href="#" class="btn-remove-img btn btn-small text-danger px-2" title="Remover foto">
                                        <i class=" fa fa-trash-o"></i>
                                    </a>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="form-group ">
                    <input type="submit">
                </div>
            </form>

        </div>
    </div>
</div>