<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $form \Zend\Form\View\Helper\Form */
//echo $this->form($this->formMaisInformacoesVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formMaisInformacoesVeiculo;
    //var_dump($form->getElements());
    $fields = $form->getElements();
    
    $fields['observacoes']->setAttributes(
        array('class' =>'form-control', 'style'=>'height:100px;',
            'placeholder'=>'Utilize este espaço para informar mais detalhes do veículo, seu histórico ou itens que não foram contemplados nas etapas anteriores.'
    ));
    
    /*$fields['valor']->setLabelAttributes(['class'=>'form-control-lg']);*/
?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                QUAIS OS DIFERENCIAIS DO SEU VEÍCULO?
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar seu anúncio.
                    <br/>Campos com * são de preenchimento obrigatório.
                </small>
            </div>
            
            <form method="POST" name="form_maisInformacoesVeiculo" class="form-group" role="form" id="form_maisInformacoesVeiculo">
                <div class="row text-center">
                    
                    <div class="form-group form-group-default required ">
                        <?= $this->formLabel($fields['observacoes']) ?>
                        <?= $this->formTextarea($fields['observacoes']) ?>
                    </div>
                </div>

                <div class="form-group form-group-default">
                    <?= $this->formLabel($fields['idTroca']) ?>
                    <?= $this->formRadio($fields['idTroca']) ?>
                </div>

                <div class="checkbox form-group form-group-default">
                    <?= $this->formCheckbox($fields['termo']) ?>
                </div>

                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>

        </div>
    </div>
</div>