<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Zend\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
$form = $this->formMaisInformacoesVeiculo;
$fields = $form->getElements();

if ($this->checkedTermo) {
    $fields['termo']->setChecked(true);
}

if ($this->checkedProposta !== '0') {
    $fields['aceitaProposta']->setChecked(true);
}

if ($this->checkedChat !== '0') {
    $fields['aceitaChat']->setChecked(true);
}

if ($this->checkedLigacao !== '0') {
    $fields['aceitaLigacao']->setChecked(true);
}

?>
<div class="container">
    <h4 class="text-center">
        Mais sobre o anúncio
    </h4>
    <div class="conteudo">
        <form method="POST" name="form_maisInformacoesVeiculo" class="forms" role="form" id="form_maisInformacoesVeiculo">

            <div class="field d-flex justify-content-between align-items-center">
                <b class="mr-2">
                    Aceita Troca?
                </b>
                <label class="switch">
                    <?= $this->formElement($fields['idTroca']->setLabel('')) ?>
                    <span class="slider round"></span>
                </label>
            </div>
            
            <?php /*
            <div class="field d-flex justify-content-between align-items-center">
                <b class="mr-2">
                    Aceita contato por chat?
                </b>
                <label class="switch">
                    <?= $this->formElement($fields['aceitaChat']->setLabel('')) ?>
                    <span class="slider round"></span>
                </label>
            </div>
             * 
             */ ?>

            <?php if ($this->userInfo()->isParticular()) : ?>
                <div class="field d-flex justify-content-between align-items-center">
                    <b class="mr-2">
                        Aceita contato por ligação?
                    </b>
                    <label class="switch">
                        <?= $this->formElement($fields['aceitaLigacao']->setLabel('')) ?>
                        <span class="slider round"></span>
                    </label>
                </div>
            <?php endif; ?>

            <?php if ($this->userInfo()->isRevenda()) : ?>
                <div class="field d-flex justify-content-between align-items-center flex-wrap">
                    <b class="mr-2">
                        Pode ser levado até o cliente?
                    </b>
                    <label class="switch switch-success">
                        <?= $this->formElement($fields['delivery']->setLabel('')) ?>
                        <span class="slider round"></span>
                    </label>
                    <small class="font-theme text-uppercase smallest w-100">
                        <a href="#" data-toggle="collapse" data-target="#delivery-detalhes-collapse" class="text-cinza">
                            <i class="fa fa-info-circle text-laranja" aria-hidden="true"></i> Clique aqui para saber mais
                        </a>
                    </small>
                </div>
            <?php endif; ?>

        
            <div class="collapse" id="delivery-detalhes-collapse">
                <div class="px-3 py-0">
                    <span>Ao marcar como <b class="text-verde">"SIM"</b> esta opção, é adicionada ao anúncio do veículo a seguinte mensagem:</span>
                    <span><b class="text-verde">Este veículo pode ser levado até você.</b></span>
                    <span>Dessa forma, sua revenda e o cliente podem acordar um local e horário.</span>
                    <span>Assim, sua revenda poderá <b>continuar a atender seus clientes</b> sem desrespeitar os decretos contra o <b>COVID-19</b>.</span>
                </div>
            </div>

            <div class="mb-1 mt-3">
                <small class="text-uppercase text-reset d-flex flex-wrap">
                    Leia atentamente as informações contidas no
                    <a href="/../termos/pessoa-fisica" target="_blank" class="text-laranja mr-1">termo de responsabilidade</a> 
                    e 
                    <a href="/../termos/politica-de-privacidade" target="_blank" class="text-laranja ml-1">política de privacidade.</a>
                </small>
            </div>
            <div class="check-termos checkbox checkbox-success text-reset form-group-default required pt-0 mt-0">
                <?= $this->formCheckbox($fields['termo'])?>
            </div>

            <div class="form-group ">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>