<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Zend\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
$form = $this->formMaisInformacoesVeiculo;
$fields = $form->getElements();

$fields['observacoes']->setAttributes(
    array('class' => 'form-control', 'style' => 'height:100px;',
        'placeholder' => 'Utilize este espaço para informar mais detalhes do veículo, seu histórico ou itens que não foram contemplados nas etapas anteriores.'
));

if ($this->checkedTermo) {
    $fields['termo']->setChecked(true);
}

if ($this->checkedProposta !== '0') {
    $fields['aceitaProposta']->setChecked(true);
}

if ($this->checkedLigacao !== '0') {
    $fields['aceitaLigacao']->setChecked(true);
}

if ($this->checkedLigacao !== '0') {
    $fields['aceitaChat']->setChecked(true);
}
if ($this->userInfo()->isRevenda()) {
    $fields['aceitaContato']->setChecked(true);
}

?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                QUAIS OS DIFERENCIAIS DO SEU VEÍCULO?
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar seu anúncio.
                    <br/>Campos com * são de preenchimento obrigatório.
                </small>
            </div>
            <form method="POST" name="form_maisInformacoesVeiculo" class="form-group" role="form" id="form_maisInformacoesVeiculo">
                <div class="row text-center">
                    <div class="form-group form-group-default input-shadow">
                        <span>
                            <?= $this->formLabel($fields['observacoes']) ?>
                        </span>
                        <?= $this->formTextarea($fields['observacoes']) ?>
                    </div>
                </div>
                <div class="wordcount float-right mb-3">(<span class="count"><?= strlen($fields['observacoes']->getValue())?></span>/700)</div>

                <div class="form-group form-group-default form-troca">
                    <?= $this->formLabel($fields['idTroca']) ?>
                    <?= $this->formRadio($fields['idTroca']) ?>
                </div>
                <?php
                    if($this->userInfo()->isRevenda()):
                        /** @var \Zend\Form\Element\Radio $deliveryRadio */
                        $deliveryRadio = $fields['delivery'];
                        $deliveryRadio->setAttribute('required', true);
                ?>
                    <div class="form-group form-group-default form-troca required">
                        <?= $this->formLabel($deliveryRadio) ?>
                        <?= $this->formRadio($deliveryRadio) ?>
                        <br>
                        <small class="font-theme text-uppercase smallest">
                            <a href="#" data-toggle="collapse" data-target="#delivery-detalhes-collapse">
                                <i class="fa fa-info-circle" aria-hidden="true"></i> Clique aqui para saber mais
                            </a>
                        </small>
                        <div class="collapse" id="delivery-detalhes-collapse">
                            <div class="card card-body">
                                <span>Ao marcar como <b>"SIM"</b> esta opção, é adicionada ao anúncio do veículo a seguinte mensagem:</span>
                                <span><b>Este veículo pode ser levado até você</b></span>
                                <span>Dessa forma, sua revenda e o cliente podem acordar um local e horário.</span>
                                <span>Assim, sua revenda poderá <b>continuar a atender seus clientes</b> sem desrespeitar os decretos contra o <b>COVID-19</b>.</span>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if($this->userInfo('tipoCadastro') != 1): ?>
                <div class="checkbox form-group form-group-default">
                    <?= $this->formCheckbox($fields['aceitaProposta']) ?>
                </div>
                
                <div class="checkbox form-group form-group-default">
                    <?= $this->formCheckbox($fields['aceitaLigacao']) ?>
                </div>

                <div class="checkbox form-group form-group-default">
                    <?= $this->formCheckbox($fields['aceitaChat']) ?>
                </div>
                <?php endif; ?>
                <div class="form-group form-group-default form-troca required">
                    <?= $this->formLabel($fields['aceitaContato']) ?>
                    <?= $this->formRadio($fields['aceitaContato']->setAttribute('class', 'radio radio-danger mt-0 mb-0'));?>
                    <?php if ($this->userInfo()->isParticular()) : ?>
                    <div class="ml-4">
                        <b class="text-danger">
                            <span>Por motivos de Segurança os contatos do anunciante foram ocultados. Tenho ciência da possibilidade do contato de possíveis golpistas, mesmo assim desejo exibir meu(s) telefone(s)</span>
                        </b>
                    </div>
                    <?php endif; ?>
                </div>

                <div class="checkbox form-group form-group-default required">
                    <?= $this->formCheckbox($fields['termo'])?>
                    <div class="ml-4">
                        <small class="font-theme text-uppercase smallest">
                            Leia atentamente as informações contidas no
                            <a href="/../termos/pessoa-fisica" target="_blank" class="text-laranja">termo de responsabilidade</a> 
                            e 
                            <a href="/../termos/politica-de-privacidade" target="_blank" class="text-laranja">política de privacidade.</a>
                        </small>
                    </div>
                </div>

                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>
        </div>
    </div>
</div>