<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
/* @var $form \Laminas\Form\View\Helper\Form */

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\DadosForm */
$form = $this->formDadosVeiculos;
$fields = $form->getElements();

foreach ($fields as $element) {
    if ($element->getAttribute('name') != 'checkboxacessorios' && $element->getAttribute('name') != 'veiculo_zero_km' && $element->getAttribute('name') != 'motoTrilha' && $element->getAttribute('name') != 'flag_km')
        $element->setAttribute('class', 'form-control');
}

$form->setAttribute('class', 'form');

$tipoVeiculo = $form->get('tipoVeiculo')->getValue();
$airBagsValue = [];

$acessoriosSelecionados = $form->get('checkboxacessorios')->getValue();
$temAirBag = -1;

if($tipoVeiculo === 1){
    $airBags = [2,3,67,52,68,69,70,71,72,73,74,75];
    $dados = $fields['checkboxacessorios']->getValueOptions();

    foreach ($airBags as $key => $value) {
        if(in_array($value, $acessoriosSelecionados ?? []) && $temAirBag == -1){
            $temAirBag = $value;
        }

        $fields['checkboxacessorios']->unsetValueOption($value);
        $airBagsValue[$value] = $dados[$value];
    }
}
?>


<?php if ($tipoVeiculo !== \SnBH\ApiModel\Model\VeiculoTipo::TIPO_CAMINHAO) : ?>
    <form method="POST" name="form_opcionaisVeiculo" class="form-group m-b-20 needs-validation" role="form" id="form_dadosVeiculo">
        <h5 class="text-center">
            Quais são os opcionais do seu veículo?
        </h5>
        <div class="form-group form-group-default pt-3" id="dadosAcessorios">
            <?php if ($tipoVeiculo == 1) : ?>
                <div class="d-flex justify-content-between">
                    <div id="btnCompleto" title="Marcar todos os acessórios de um carro completo.">
                            <div class="checkbox m-0 p-0 m-b-0">
                                <input type="checkbox" id="completoCheckbox">
                                <label for="completoCheckbox">Completo</label>
                            </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="opcionais pb-2">
                <?php if ($tipoVeiculo == 1) : ?>           
                    <div class="airbags">
                        <select name="checkboxacessorios[]" class="<?= $temAirBag != -1 ? 'selected' : '' ?>">
                            <option value>Air Bags</option>
                            <?php foreach ($airBagsValue as $key => $value) : ?>
                                <option value="<?= $key ?>"  <?= $temAirBag == $key ? 'selected' : '' ?> > <?= $value ?> </option>
                            <?php endforeach ?>
                        </select>                        
                    </div>
                <?php endif; ?>
                <?php
                    $acessoriosHTML = $this->formMultiCheckbox($fields['checkboxacessorios']);
                    $acessoriosHTML = str_replace('<label>', "<div><label>", $acessoriosHTML);
                    $acessoriosHTML = str_replace('</label>', "</label></div>\n", $acessoriosHTML);
                    echo $acessoriosHTML;
                ?>
            </div>

            <div class="border-top my-2 border-3x"></div>

            <?php

            $mesIPVA =  date('m');
            $meses = [1, 2, 3, 4, 5,12];
            $exibeIPVA = in_array($mesIPVA, $meses);
            $anoIpva = $mesIPVA == 12 ? date('Y')+1 : date('Y');

                if($tipoVeiculo != 2 && (isset($fields['adaptado']) || (isset($fields['flagIpva']) && $exibeIPVA))):
            ?>
                <div class="destaques pt-1 pb-3">
                    <div class="text-center"><b>Algum item que você quer destacar?</b></div>

                    <div class="opcionais">
                        <?php
                        /*
                        REMOVE O CHECKBOX IPVA

                        if ($exibeIPVA) {
                            $destaques = [
                                $this->formCheckbox($fields['flagIpva']->setLabel('IPVA '.$anoIpva.' quitado?'))
                            ];
                            foreach ($destaques as $key => $value) {
                                $value = str_replace('class="checkbox"', 'class="checkbox-custom"', (string) $value);

                                $value = str_replace('</label>', '<i class="fa fa-check" aria-hidden="true"></i></label>', $value);

                                $value = explode('<div', $value);
                                if (trim($value[0]) == '') {
                                    unset($value[0]);
                                } ?>

                                <div class="checkbox-custom">
                                    <?= $value[0] ?>
                                </div>
                        <?php
                            }
                        } */

                        if(isset($fields['adaptado'])) {
                            $adaptadoHTML = $this->formCheckbox($fields['adaptado']);
                            $adaptadoHTML = str_replace('class="checkbox"', 'class="checkbox-custom"', (string) $adaptadoHTML);
                            $adaptadoHTML = str_replace('</label>', '<i class="fa fa-wheelchair" aria-hidden="true"></i><i class="fa fa-check" aria-hidden="true"></i></label>', $adaptadoHTML);
                            $adaptadoHTML = explode('<div', $adaptadoHTML);
                            if (trim($adaptadoHTML[0]) == '') {
                                unset($adaptadoHTML[0]);
                            }
                            $adaptadoHTML = $adaptadoHTML[0];
                            ?>
                            <div class="checkbox-custom" data-toggle="collapse" data-target=".detalhes-pcd" aria-expanded="false">
                                <?= $adaptadoHTML ?>
                            </div>
                            <?php
                        }?>
                    </div>
                    <div class="detalhes-pcd collapse">Este veículo é adaptado para <br class="d-block d-md-none"><b class="text-success">PCD (Pessoa com deficiência)</b></div>
                </div>
            <?php endif; ?>
        </div>

        <div class="form-group ">
            <?= $this->formSubmit($fields['submit']) ?>
        </div>
    </form>
<?php endif; ?>