<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $form \Zend\Form\View\Helper\Form */
//echo $this->form($this->formPrecoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formPrecoVeiculo;
    $fields = $form->getElements();

    $fields['observacoes']->setAttributes(
        array('class' => 'form-control', 'style' => 'height:100px;',
            'placeholder' => 'Utilize este espaço para informar mais detalhes do veículo, seu histórico ou itens que não foram contemplados nas etapas anteriores.'
    ));

    switch ($tipoVeiculo) {
        case 2:
            $veiculo = 'o seu caminhão';
            break;

        case 3:
            $veiculo = 'a sua moto';
            break;
        
        default:
            $veiculo = 'o seu carro';
            break;
    }
?>
<div class="container">
    <h4 class="text-center">
        Sobre <?= $veiculo ?> agora, conta pra gente
    </h4>
    <div class="conteudo">
        <form method="POST" name="form_precoVeiculo" class="needs-validation forms" role="form" id="form_precoVeiculo">

            <div class="d-flex justify-content-between">
                <div class="conjunto-km form-group form-group-default required">
                    <div class="mb-1"><b>Quanto <?= $veiculo ?> já rodou?</b></div>
                    <div class="d-flex align-items-center">
                        <div class="form-group mb-0 d-flex align-items-center">
                            <b class="mr-2">KM</b>
                            <?= $this->formText($fields['kilometragem']) ?>
                        </div>
                        <div class="form-group d-flex align-items-center mb-0 justify-content-center justify-content-md-end flex-wrap exibir-km">
                            <b class="mr-1 mr-md-2">Exibir KM</b>
                            <label class="switch switch-danger switch-inverse-danger mb-0">
                                <?= $this->formElement($fields['flag_km']->setLabel('')) ?>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group form-group-default mb-0">
                <b>Certo, agora fale sobre os diferenciais do seu carro, ou as observações que desejar. Não é obrigatório, ok?</b>
                <div class="mt-2"><?= $this->formTextarea($fields['observacoes']) ?></div>
                <div class="wordcount float-right justify-content-end">
                    (<span class="count"><?= strlen($fields['observacoes']->getValue())?></span>/700)
                </div>
            </div>

            <div class="form-group form-group-default required">
                <b>Por quanto deseja vender <?= $veiculo ?>?</b>
                <div class="mt-1 d-flex align-items-center">
                    <b class="mr-2 text-verde">R$</b>
                    <?= $this->formText($fields['valor']) ?>
                </div>
            </div>

            <div class="d-flex justify-content-between w-100 align-items-center">
                <div><b>Este veículo esta financiado?</b></div>
                <div>
                    <label class="switch mb-0">
                        <?= $this->formElement($fields['financiamento']->setLabel('')) ?>
                        <span class="slider round"></span>
                    </label>
                </div>
            </div>

            <div class="d-flex justify-content-between w-100 align-items-center">
                <b>Exibir valor do veículo?</b>
                <label class="switch switch-danger switch-inverse-danger mb-0">
                    <?= $this->formElement($fields['combinarValor']->setLabel('')) ?>
                    <span class="slider round"></span>
                </label>
            </div>

            <div class="form-group">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>