<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $form \Zend\Form\View\Helper\Form */
//echo $this->form($this->formPrecoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formPrecoVeiculo;
    //var_dump($form->getElements());
    $fields = $form->getElements();

    $fields['observacoes']->setAttributes(
        array('class' => 'form-control', 'style' => 'height:100px;',
            'placeholder' => 'Utilize este espaço para informar mais detalhes do veículo, seu histórico ou itens que não foram contemplados nas etapas anteriores.'
    ));
?>
<div class="container">
    <h4 class="text-center">
        Sobre o seu carro agora, conta pra gente
    </h4>
    <div class="conteudo">
        <form method="POST" name="form_precoVeiculo" class="needs-validation forms" role="form" id="form_precoVeiculo">

            <div class="d-flex justify-content-between">
                <div class="conjunto-km form-group form-group-default required">
                    <div class=""><b>Quanto o seu carro já rodou?</b></div>
                    <div class="d-flex align-items-center">
                        <div class="form-group mb-0">
                            <?= $this->formText($fields['kilometragem']) ?>
                        </div>
                        <div class="form-group d-flex align-items-center mb-0 justify-content-center justify-content-md-end w-50 flex-wrap">
                            <b class="mr-0 mr-md-2">Exibir KM</b>
                            <label class="switch switch-danger switch-inverse-danger mb-0">
                                <?= $this->formElement($fields['flag_km']->setLabel('')) ?>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group form-group-default">
                <b>Certo, agora fale sobre os diferenciais do seu carro, ou as observações que desejar. Não é obrigatório, ok?</b>
                <div class="mt-2"><?= $this->formTextarea($fields['observacoes']) ?></div>
                <div class="wordcount float-right mb-3 justify-content-end">
                    (<span class="count"><?= strlen($fields['observacoes']->getValue())?></span>/700)
                </div>
            </div>

            <div class="form-group form-group-default required mt-2">
                <b>Por quanto deseja vender o seu carro?</b>
                <div class="mt-1"><?= $this->formText($fields['valor']) ?></div>
            </div>

            <div class="d-flex justify-content-between w-100 align-items-center">
                <div><b>Este veículo esta financiado?</b></div>
                <div>
                    <label class="switch mb-0">
                        <?= $this->formElement($fields['financiamento']->setLabel('')) ?>
                        <span class="slider round"></span>
                    </label>
                </div>
            </div>

            <div class="d-flex justify-content-between w-100 align-items-center">
                <b>Valor a combinar</b>
                <label class="switch mb-0">
                    <?= $this->formElement($fields['combinarValor']->setLabel('')) ?>
                    <span class="slider round"></span>
                </label>
            </div>

            <div class="form-group">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>