<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
/* @var $form \Laminas\Form\View\Helper\Form */
//echo $this->form($this->formPrecoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formPrecoVeiculo;
    $fields = $form->getElements();

    $fields['observacoes']->setAttributes(
        ['class' => 'form-control', 'style' => 'height:100px;', 'placeholder' => 'Utilize este espaço para informar mais detalhes do veículo, seu histórico ou itens que não foram contemplados nas etapas anteriores.']);

    switch ($tipoVeiculo) {
        case 2:
            $veiculo = 'o seu caminhão';
            break;

        case 3:
            $veiculo = 'a sua moto';
            break;
        
        default:
            $veiculo = 'o seu carro';
            break;
    }

    if ($checkedCombinarValor !== '1') {
        $fields['combinarValor']->setChecked(true);
    }

    if ($checkedExibirKm !== '1') {
        $fields['flag_km']->setChecked(true);
    }

    if ($checkedFlagFinanciar !== '0') {
        $fields['flagFinanciar']->setChecked(true);
    }
?>
<div class="container">
    <h4 class="text-center">
        Sobre <?= $veiculo ?> agora, conta pra gente
    </h4>
    <div class="conteudo">
        <form method="POST" name="form_precoVeiculo" class="needs-validation forms" role="form" id="form_precoVeiculo">

            <div class="d-flex justify-content-between">
                <div class="conjunto-km form-group form-group-default">
                    <div class="mb-1"><b>Quanto <?= $veiculo ?> já rodou?</b></div>
                    <div class="d-flex align-items-center">
                        <div class="form-group required mb-0 d-flex align-items-center">
                            <b class="mr-2 text-laranja">KM</b>
                            <?= $this->formText($fields['kilometragem']) ?>
                        </div>
                        <div class="form-group d-flex align-items-center mb-0 justify-content-center justify-content-md-end flex-wrap exibir-km">
                            <b class="mr-1 mr-md-2">Exibir <span class="text-laranja">KM</span>?</b>
                            <label class="switch mb-0">
                                <?= $this->formElement($fields['flag_km']->setLabel('')) ?>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group form-group-default mb-2">
                <b>Certo, agora fale sobre os diferenciais do seu carro, ou as observações que desejar. Não é obrigatório, ok?</b>
                <p class="text-danger" id="blockWords"></p>
                <div class="mt-2"><?= $this->formTextarea($fields['observacoes']) ?></div>
                <div class="wordcount float-right justify-content-end">
                    <span class="count"><?= strlen($fields['observacoes']->getValue()??'')?></span>
                </div>
            </div>


            <div class="d-flex justify-content-between">
                <div class="conjunto-preco form-group form-group-default">
                    <div class="mb-1"><b>Por quanto deseja vender <?= $veiculo ?>?</b></div>
                    <div class="d-flex align-items-center">
                        <div class="form-group required mb-0 d-flex align-items-center">
                            <div class="mt-1 d-flex align-items-center">
                                <b class="mr-2 text-verde">R$</b>
                                <?= $this->formText($fields['valor']) ?>
                            </div>
                        </div>
                        
                        <div class="form-group d-flex align-items-center mb-0 justify-content-center justify-content-md-end flex-wrap exibir-preco">
                            <b class="mr-1 mr-md-2">Exibir <span class="text-verde">preço</span>?</b>
                            <label class="switch mb-0">
                                <?= $this->formElement($fields['combinarValor']->setLabel('')) ?>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group d-flex justify-content-between w-100 align-items-center">
                <div><b>Este veículo está financiado?</b></div>
                <div class="pr-1 pr-md-2 mr-0 mr-md-1 w-auto">
                    <label class="switch mb-0">
                        <?= $this->formElement($fields['financiamento']->setLabel('')) ?>
                        <span class="slider round"></span>
                    </label>
                </div>
            </div>
            <?php $particularClass = $this->userInfo()->isParticular()? 'd-none' : '' ; ?>
            <div class="control-financiamento <?= $particularClass ?>">
                <div class="form-group group-financiamento mb-0 d-flex justify-content-between w-100 align-items-center">
                    <?php if ($this->userInfo()->isParticular()) : ?>
                        <div>
                            <a href="" data-toggle="collapse" data-target=".texto-financiamento,.rodape" aria-expanded="true" aria-controls="texto-financiamento">
                                <b class="mr-2">Quero disponibilizar meu veículo para financiamento?</b>
                            </a>
                        </div>
                    <?php else: ?>
                        <div><b class="mr-2">Este veículo pode ser financiado?</b></div>
                    <?php endif; ?>

                    <div class="pr-1 pr-md-2 mr-0 mr-md-1 w-auto">
                        <label class="switch mb-0">
                            <?= $this->formElement($fields['flagFinanciar']->setLabel('')) ?>
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>

                <?php if ($this->userInfo()->isParticular()) : ?>
                    <div class="detalhes-financiamento">

                        <div class="rodape collapse show">
                            <a href="" data-toggle="collapse" data-target=".texto-financiamento,.rodape" aria-expanded="true" aria-controls="texto-financiamento">
                                <small class="mr-2 text-laranja">Clique para saber mais</small><i class="fa fa-info-circle text-laranja"></i>
                            </a>
                        </div>
                        <div class="mt-2 texto-financiamento collapse">
                            <p><small>A <b class="text-laranja">Seminovos</b> fez uma parceria com a <b class="link-bv">Credville</b> que disponibiliza o <b>financiamento de veículos em particulares.</b></small></p>
                            <b class="">Como funciona: </b>
                            <p class="mb-0"><i class="fa fa-circle text-laranja mr-1"></i>O interessado <b>clica no botão</b> disponível no seu anúncio.</p>
                            <p class="mb-0"><i class="fa fa-circle text-laranja mr-1"></i>Preenche o formulário com dados dele.</p>
                            <p class="mb-0"><i class="fa fa-circle text-laranja mr-1"></i>Enviamos os dados do veículo e o <b>seu contato para a financeira.</b></p>
                            <p class="mb-0"><i class="fa fa-circle text-laranja mr-1"></i>Financeira faz uma avaliação e em caso de aprovação <b>entra em contato com você (vendedor)</b> para que o processo de financiamento dê continuidade.</p>
                            <p class="mb-2"><i class="fa fa-circle text-laranja mr-1"></i>Você <b>não pagará</b> nada há mais por isso, e facilita o pagamento ao comprador, <b>aumentando a chance de venda</b>.</p>
                            <b class="">IMPORTANTE:</b>
                            <p class="mb-0">Está é mais uma funcionalidade para que seu carro seja vendido de forma segura e <b class="text-verde">o recebimento é á vista</b> por parte da financeira.</p>
                            <p class="mb-0"><small>*Atualmente o financiamento com a Credville só está disponível para vendas com <b>modelo  do veículo superior a <?= Date('Y') - 10 ?>.</b></samll></p>
                            <p class="mb-0"><small>*O processo de verificação de crédito e pagamento é de <b>responsabilidade da financeira!</b></samll></p>
                            <p class="mb-0"><small>**Processo pela financeira ocorre <b>100% online.</b></samll></p>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <?= $this->formSubmit($fields['submit']) ?>
            </div>
        </form>
    </div>
</div>