<?php
/* @var $this \Laminas\View\Renderer\PhpRenderer */
/* @var $form \Laminas\Form\View\Helper\Form */
//echo $this->form($this->formVideoVeiculo);

/* @var $this \AreaRestritaAnuncio\Form\Veiculo\PrecoForm */
    $form = $this->formVideoVeiculo;
    //var_dump($form->getElements());
    $fields = $form->getElements();

    $fields['video']->setAttributes(['class' =>'form-control']);

    /*$fields['valor']->setLabelAttributes(['class'=>'form-control-lg']);*/

?>
<div class="container container-fixed-lg">
    <div class="row">
        <div class="col-lg-12">

            <h4 class="text-center">
                TEM UM VÍDEO DO SEU VEÍCULO?
            </h4>
            <div class="text-center my-3">
                <small class="my-3 align-center">
                    Agora está na hora de mostrar a sua joia! Se possuí um vídeo do seu veicúlo publicado no youtube
                    cole a URL abaixo
                    que ele será mostrado juntamente de suas fotos!
                </small>
            </div>

            <form method="POST" name="form_videoVeiculo" class="form-group" role="form" id="form_videoVeiculo">

                <div class="row">
                    <div class="col-8">
                        <h4 class="text-bold"><b>URL do Youtube:</b></h4>
                        <div class="form-group form-group-default ">
                            <?= $this->formLabel($fields['video']) ?>
                            <?= $this->formText($fields['video']) ?>
                        </div>
                        <div class="text-center px-3">
                            <small>
                                Se estiver tudo certo com o seu vídeo ele deve aparecer no player ao lado. Caso ele não
                                apareça confira se a url esta
                                correta!
                            </small>
                        </div>
                    </div>
                    <div class="col-4 d-flex justify-content-end">
                        <div class="preview-video bg-dark justify-content-center align-items-center d-flex">
                            <i class="text-white fa fa-youtube-play fa-3x" aria-hidden="true"></i>
                        </div>
                        <iframe id="videoWindow" class="d-none" width="240" height="147" src="" frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                    </div>
                </div>

                <div class="form-group ">
                    <?= $this->formSubmit($fields['submit']) ?>
                </div>
            </form>
        </div>
    </div>
</div>