<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */

use Zend\Router\PriorityList;
use Zend\Router\Http\Part;

/* @var $restrito Zend\Router\Http\Part */
$restrito = $this->router->getRoutes();


$parametros = [
    'idVeiculo' => 87687,
    'idPagamento' => 23424232,
    'parametro-obrigatorio' => 'Parametro Obrigatorio',
    'tipo' => 'carro',
    'email' => 'email@seminovosbh.com.br',
    'action' => 'dados'
];

function renderRoutes(PriorityList $routeList, $baseRoute, $ctx, $parametros)
{
    foreach ($routeList as $routeName => $route) {
        /* @var $route \Zend\Router\Http\Literal */
        if ($baseRoute) {
            $routeName = $baseRoute . '/' . $routeName;
        }

        $hasParts = $route instanceof Part;
        try {
            $url = ($ctx->url($routeName, $parametros));
        } catch (\Exception $ex) {
            $reflection = new ReflectionClass($route);
            $properties = $reflection->getProperties();
            $mayTerminate = null;
            foreach ($properties as $property) {
                if ($property->name != 'mayTerminate') {
                    continue;
                }
                $property->setAccessible(true);
                $mayTerminate = $property->getValue($route);
            }
            if ($mayTerminate === null) {
                throw $ex;
            }

            $url = false;
        }


        if ($hasParts) {
            echo '<div class="sub--route">';
        }
        echo '<b>Route name: </b>' . $routeName . '<br>';
        if ($url) {
            echo '<b>Exemplo: </b>';
            echo '<b><a href="' . $url . '"><i class="fa fa-link" aria-hidden="true"></i> ' . $url . '</a></b>';
        }

        if ($hasParts) {
            echo '<div class="sub-route">';
            renderRoutes($route->getRoutes(), $routeName, $ctx, $parametros);
            echo '</div>';
            echo '</div>';
            continue;
        }
        echo '<hr>';
    }
}

?>
<style>
    .sub-route{
        margin-left: 50px;
        border-left: 1px solid #e6e6e6;
        padding-left: 35px;
    }
    .sub-route > h3{
        /*margin-left: -30px;*/
    }
</style>
<?php
renderRoutes($restrito, '', $this, $parametros);
