<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */

use Zend\Router\PriorityList;
use Zend\Router\Http\Part;

/* @var $restrito Zend\Router\Http\Part */
$restrito = $this->router->getRoutes();


$parametros = [
    'idPagamento' => 23424232,
    'parametro-obrigatorio' => 'Parametro Obrigatorio'
];

renderRoutes($restrito, '', $this, $parametros);

function renderRoutes(PriorityList $routeList, $baseRoute, $ctx, $parametros)
{
    foreach ($routeList as $routeName => $route) {
        /* @var $route \Zend\Router\Http\Literal */
        if ($baseRoute) {
            $routeName = $baseRoute . '/' . $routeName;
        }

        $url = ($ctx->url($routeName, $parametros));
        echo '<b>Route name: </b>' . $routeName . '<br>';
        echo '<b>Exemplo: </b>';
        echo '<b><a href="' . $url . '"><i class="fa fa-link" aria-hidden="true"></i> ' . $url . '</a></b><br><br>';

        if ($route instanceof Part) {
            echo '<h3>Rota pai: ' . $routeName . '</h3>';
            renderRoutes($route->getRoutes(), $routeName, $ctx, $parametros);
        }
    }
}
