<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$routeName = $this->routeName;
$isRoute = function($route)use($routeName) {
    return $route == $routeName ? 'btn-success' : 'btn-outline-success';
};

?>
<a class="btn <?= $isRoute('restrito/rota-exemplo') ?>" href="<?= $this->url('restrito/rota-exemplo') ?>">
  Rota Exemplo
</a>


<a class="btn <?= $isRoute('restrito/rota-exemplo/parametro-opcional') ?>" href="<?= $this->url('restrito/rota-exemplo/parametro-opcional') ?>">
  Parametro opcional
</a>


<a class="btn <?= $isRoute('restrito/rota-exemplo/parametro-opcional') ?>" href="<?= $this->url('restrito/rota-exemplo/parametro-opcional', ['parametro' => 'Valor exemplo do parametro opcional']) ?>">
  Parametro opcional definido
</a>


<a class="btn <?= $isRoute('restrito/rota-exemplo/sub-rota') ?>" href="<?= $this->url('restrito/rota-exemplo/sub-rota') ?>">
  Sub rota
</a>


<a class="btn <?= $isRoute('restrito/rota-exemplo/outra-sub-rota') ?>" href="<?= $this->url('restrito/rota-exemplo/outra-sub-rota', ['parametro-obrigatorio' => 'Valo do parametro obrigatório']) ?>">
  Outra sub rota
</a>

