<?php
/* @var $this AreaRestrita\View\Helper\AutocompleteClass */
$this->headTitle('Financeiro');
$dadosFinanceiro = $this->financeiro;
?>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-12 text-left">
            <h3 class="font-montserrat all-caps hint-text">Financeiro</h3>
        </div>
    </div>
</div>
<div class=" container-fluid container-fixed-lg">
    <div id="rootwizard">
        <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator nav-stack-sm nav-main-financeiro"
            role="tablist" data-init-reponsive-tabs="dropdownfx">
            <li class="nav-item">
                <a class="active" data-toggle="tab" href="#tab-planos" data-target="#tab-planos" role="tab">
                    <i class="fa fa-shopping-cart tab-icon"></i> <span>Plano</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="" data-toggle="tab" href="#tab-pagamento" data-target="#tab-pagamento" role="tab">
                    <i class="fa fa-credit-card tab-icon"></i> <span>Pagamento</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="" data-toggle="tab" href="#tab-finalizar" data-target="#tab-finalizar" role="tab">
                    <i class="fa fa-check tab-icon"></i> <span>Finalizar</span>
                </a>
            </li>
        </ul>
        <div class="tab-content tab-content-main">
            <div class="tab-pane px-md-4 p-0 active slide-left" id="tab-planos">
                <div class="row">
                    <div class="col-md-5 col-12 b-r b-dashed b-grey sm-b-b">
                        <div class="sm-m-t-15 m-t-50">
                            <i class="fa fa-shopping-cart fa-2x hint-text"></i>
                            <h5>Valor mensal do plano atual: R$ <?= $dadosFinanceiro['valor'] ?></h5>
                            <p class="small hint-text">Escolha o tempo que deseja pagar.</p>
                        </div>
                    </div>
                    <div class="col-md-7 col-12">
                        <form class="form-planos">
                            <table class="table-condensed w-100">
                                <?php
                            $planos = [
                                [
                                    'nome' => 'Plano Mensal',
                                    'desconto' => $dadosFinanceiro['desconto_mensal'],
                                    'economia' => $dadosFinanceiro['economia_mensal'],
                                    'valor' => $dadosFinanceiro['valor_mensal'],
                                    'value_checkbox' => $dadosFinanceiro['value_checkbox_mensal'],
                                    'parcelas' => '1'
                                ],
                                [
                                    'nome' => 'Plano Trimestral',
                                    'desconto' => $dadosFinanceiro['desconto_trimestral'],
                                    'economia' => $dadosFinanceiro['economia_trimestral'],
                                    'valor' => $dadosFinanceiro['valor_trimestral'],
                                    'value_checkbox' => $dadosFinanceiro['value_checbkox_trimestral'] ?? null,
                                    'parcelas' => '3'
                                ],
                                [
                                    'nome' => 'Plano Semestral',
                                    'desconto' => $dadosFinanceiro['desconto_semestral'],
                                    'economia' => $dadosFinanceiro['economia_semestral'],
                                    'valor' => $dadosFinanceiro['valor_semestral'],
                                    'value_checkbox' => $dadosFinanceiro['value_checkbox_semestral'],
                                    'parcelas' => '6'
                                ],
                                [
                                    'nome' => 'Plano Anual',
                                    'desconto' => $dadosFinanceiro['desconto_anual'],
                                    'economia' => $dadosFinanceiro['economia_anual'],
                                    'valor' => $dadosFinanceiro['valor_anual'],
                                    'value_checkbox' => $dadosFinanceiro['value_checkbox_anual'],
                                    'parcelas' => '12'
                                ],
                            ];

                            foreach ($planos as $i => $plano):
                                ?>
                                <tr class="border-bottom">
                                    <td class="pl-0">
                                        <div class="radio radio-success">
                                            <input type="radio" name="tempo_contrato" id="tempo_contrato<?= $i ?>"
                                                value="<?= $plano['value_checkbox'] ?>"
                                                data-tempo_contrato="<?= $plano['parcelas'] ?>" required>
                                            <label class="ml-0 ml-md-2 font-montserrat fs-11 all-caps"
                                                for="tempo_contrato<?= $i ?>">
                                                <span id="plano"><?= $plano['nome'] ?></span>
                                            </label>
                                        </div>
                                    </td>
                                    <td class="">
                                        <span>Desconto de
                                            <span id="desconto" class="mr-2"><?= $plano['desconto'] ?>
                                            </span>
                                            <small id="economia">
                                                (<?= $plano['economia'] ?>)
                                            </small>
                                        </span>
                                    </td>
                                    <td class="">
                                        <h4 class="text-orange font-montserrat">R$
                                            <span id="valor"><?= $plano['valor'] ?></span>
                                        </h4>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </form>
                        <div class="row  mt-3" id="resultado">
                            <div class="col-md-3 p-l-10 sm-padding-15 align-items-center d-flex">
                                <div>
                                    <h5 class="font-montserrat all-caps small no-margin hint-text bold">
                                        Desconto </h5>
                                    <p class="no-margin"><span id="desconto">-</span></p>
                                </div>
                            </div>
                            <div class="col-md-3 col-middle sm-padding-15 align-items-center d-flex">
                                <div>
                                    <h5 class="font-montserrat all-caps small no-margin hint-text bold">
                                        Economia</h5>
                                    <p class="no-margin">R$ <span id="economia">-</span></p>
                                </div>
                            </div>
                            <div class="col-md-6 text-right bg-dark padding-10">
                                <h5 class="font-montserrat all-caps small no-margin hint-text text-white bold">
                                    Total</h5>
                                <h4 class="no-margin text-white">R$ <span id="total">-</span></h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane slide-left px-md-4 p-0" id="tab-pagamento">
                <div class="row">
                    <div class="col-md-6 col-12 b-r b-dashed b-grey ">
                        <div class="">
                            <h2>Forma de pagamento</h2>
                            <p>Escolha ao lado a forma de pagamento desejda para finalizar a compra.</p>
                            <p class="small hint-text">Dados do plano contratado</p>
                            <table class="table-condensed" width="100%">
                                <tr>
                                    <td class="">
                                        <div class="align-items-center d-flex">
                                            <span class="m-l-10 font-montserrat fs-11 all-caps" id="plano">
                                                Selecione Um Plano
                                            </span>
                                        </div>
                                    </td>
                                    <td class="align-items-center text-right">
                                        <div class="d-flex align-items-center">
                                            <span>Desconto </span>
                                            <span id="desconto">-</span>
                                        </div>
                                    </td>
                                    <td class="align-items-center text-right">
                                        <span>Economia R$ </span>
                                        <a id="economia">-</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="col-md-3 text-center justify-content-end">
                                        <h4 class="text-dark no-margin font-montserrat align-items-center">
                                            <span>R$ </span>
                                            <span id="valor">-<span>
                                        </h4>
                                    </td>
                                </tr>
                            </table>
                            <p>A fatura estará disponível no seu histórico de pagamentos após a confirmação de
                                pagamento. <br>Condições de pagamento: Cartão de Crédito ou Boleto Bancário </p>
                        </div>
                    </div>
                    <div class="col-md-6 col-12">
                        <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator nav-stack-sm" role="tablist"
                            data-init-reponsive-tabs="dropdownfx">
                            <li class="nav-item">
                                <a class="" data-toggle="tab" href="#tab1" data-target="#cartao_tab" role="tab">
                                    <i class="fa fa-shopping-cart tab-icon"></i>
                                    <span>Cartão de Crédito</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="" data-toggle="tab" href="#tab3" data-target="#boleto_tab" role="tab">
                                    <i class="fa fa-file-text tab-icon"></i>
                                    <span>Boleto Bancário</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="" data-toggle="tab" href="#tab3" data-target="#pix_tab" role="tab">
                                    <i class="fa fa-credit-card tab-icon"></i>
                                    <span>PIX</span>
                                </a>
                            </li>
                        </ul>
                        <div class="tab-content p-0">
                            <div class="tab-pane padding-20 sm-no-padding slide-left" id="cartao_tab">
                                <div class="row row-same-height">
                                    <?= $this->partial('area-restrita/financeiro/form-cartao-credito.phtml') ?>
                                </div>
                            </div>
                            <div class="tab-pane padding-20 sm-no-padding slide-left" id="boleto_tab">
                                <div class="row row-same-height">
                                    <?= $this->partial('area-restrita/financeiro/form-boleto.phtml') ?>
                                </div>
                            </div>
                            <div class="tab-pane padding-20 sm-no-padding slide-left" id="pix_tab">
                                <div class="row row-same-height">
                                    <?= $this->partial('area-restrita/financeiro/form-pix.phtml') ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane padding-20 sm-no-padding slide-left" id="tab-finalizar">
                <div class="row row-same-height padding-30">
                    <h2>
                        Obrigado por renovar, seu plano a Seminovos agradeçe.
                    </h2>
                </div>
            </div>
            <ul
                class="pager wizard no-style d-flex bg-white justify-content-center justify-content-md-end ml-2 mt-2 mr-2">
                <li class="">
                    <a class="previous btn btn-default btn-cons pull-right hide" data-nav-dir="prev">
                        <span>Anterior</span>
                    </a>
                </li>
                <li class="">
                    <a class="next btn btn-laranja text-white btn-cons " data-nav-dir="next">
                        <span>Próximo</span>
                    </a>
                </li>
                <li class="">
                    <a href="/" class="finish btn btn-success text-white btn-cons pull-right hide"
                        data-nav-dir="finish">
                        <span>Finalizar</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="retorno-boleto"></div>
