<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$dadosFinanceiro = $this->financeiro;

?>

<div class=" container-fluid container-fixed-lg">
    <div id="rootwizard">
        <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator nav-stack-sm" role="tablist"
            data-init-reponsive-tabs="dropdownfx">
            <li class="nav-item">
                <a class="active" data-toggle="tab" href="#tab1" data-target="#tab1" role="tab"><i
                        class="fa fa-shopping-cart tab-icon"></i> <span>Plano tual</span></a>
            </li>
            <li class="nav-item">
                <a class="" data-toggle="tab" href="#tab3" data-target="#tab2" role="tab"><i
                        class="fa fa-credit-card tab-icon"></i> <span>Pagamento</span></a>
            </li>
            <li class="nav-item">
                <a class="" data-toggle="tab" href="#tab4" data-target="#tab3" role="tab"><i
                        class="fa fa-check tab-icon"></i> <span>Resumo</span></a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane padding-20 sm-no-padding active slide-left" id="tab1">
                <div class="row row-same-height">
                    <div class="col-md-5 b-r b-dashed b-grey sm-b-b">
                        <div class="padding-30 sm-padding-5 sm-m-t-15 m-t-50">
                            <i class="fa fa-shopping-cart fa-2x hint-text"></i>
                            <h5>Valor mensal do plano atual: R$ <?= $dadosFinanceiro['valor'] ?></h5>
                            <p class="small hint-text">Escolha o tempo que deseja pagar.</p>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="padding-30 sm-padding-5">
                            <table class="table table-condensed">
                                <?php
                                $planos = [
                                    ["nome" => "Plano Mensal", "desconto" => $dadosFinanceiro['desconto_mensal'], "economia" => $dadosFinanceiro['economia_mensal'], "valor" => $dadosFinanceiro['valor_mensal'], "value_checkbox" => $dadosFinanceiro['value_checkbox_mensal'],"parcelas"=>false],
                                    ["nome" => "Plano Trimestral", "desconto" => $dadosFinanceiro['desconto_trimestral'], "economia" => $dadosFinanceiro['economia_trimestral'], "valor" => $dadosFinanceiro['valor_trimestral'], "value_checkbox" => $dadosFinanceiro['value_checbkox_trimestral'],"parcelas"=>'3'],
                                    ["nome" => "Plano Semestral", "desconto" => $dadosFinanceiro['desconto_semestral'], "economia" => $dadosFinanceiro['economia_semestral'], "valor" => $dadosFinanceiro['valor_semestral'], "value_checkbox" => $dadosFinanceiro['value_checkbox_semestral'],"parcelas"=>'6'],
                                    ["nome" => "Plano Anual", "desconto" => $dadosFinanceiro['desconto_anual'], "economia" => $dadosFinanceiro['economia_anual'], "valor" => $dadosFinanceiro['valor_anual'], "value_checkbox" => $dadosFinanceiro['value_checkbox_anual'],"parcelas"=>'8'],
                                ];
                                foreach ($planos as $i => $plano):
                                    ?>
                                <tr>
                                    <td class="radio radio-success col-lg-5 col-md-6 col-sm-7 " onclick="$('#parcelas<?=$i?>').collapse('toggle')">
                                        <input type="radio" name="options" id="option<?= $i ?>"
                                            value="<?= $plano['value_checkbox'] ?>">
                                        <label class="m-l-10 font-montserrat fs-11 all-caps" for="option<?= $i ?>"><span
                                                id="plano"><?= $plano['nome'] ?></span>
                                        </label>
                                    </td>

                                    <td class="col-lg-2 col-md-3 col-sm-3 text-right">
                                        <span>Desconto de <span id="desconto"><?= $plano['desconto'] ?></span></span>
                                    </td>

                                    <td class="col-lg-2 col-md-3 col-sm-3 text-right">
                                        <span>Economia de R$ <span id="economia"><?= $plano['economia'] ?></span></span>
                                    </td>

                                    <td class="col-lg-3 col-md-3 col-sm-2 text-right">
                                        <h4 class="text-primary no-margin font-montserrat">R$
                                            <span id="valor"><?= $plano['valor'] ?></span></h4>
                                    </td>
                                </tr>
                                <?php /*if($plano["parcelas"]):?>
                                <tr id="parcelas<?=$i?>" class="collapse">
                                    <td colspan="4" class="d-flex justify-content-start">
                                        <p>Pode Ser parcelado em até <span id="nParcelas"><?=$plano["parcelas"]?></span></p>
                                    </td>
                                </tr>
                                <?php endif; */endforeach; ?>
                            </table>
                            <div class="row b-a b-grey no-margin" id="resultado">
                                <div class="col-md-3 p-l-10 sm-padding-15 align-items-center d-flex">
                                    <div>
                                        <h5 class="font-montserrat all-caps small no-margin hint-text bold">
                                            Desconto </h5>
                                        <p class="no-margin"><span id="desconto">-</span></p>
                                    </div>
                                </div>
                                <div class="col-md-3 col-middle sm-padding-15 align-items-center d-flex">
                                    <div>
                                        <h5 class="font-montserrat all-caps small no-margin hint-text bold">
                                            Economia</h5>
                                        <p class="no-margin">R$ <span id="economia">-</span></p>
                                    </div>
                                </div>
                                <div class="col-md-6 text-right bg-laranja padding-10">
                                    <h5 class="font-montserrat all-caps small no-margin hint-text text-white bold">
                                        Total</h5>
                                    <h4 class="no-margin text-white">R$ <span id="total">-</span></h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane slide-left padding-20 sm-no-padding" id="tab2">
                <div class="row row-same-height">
                    <div class="col-md-5 b-r b-dashed b-grey ">
                        <div class="padding-30 sm-padding-5">
                            <h2>Forma de pagamento</h2>
                            <p>Escolha ao lado a forma de pagamento desejda para finalizar a compra.</p>
                            <p class="small hint-text">Dados do plano contratado</p>
                            <table class="table table-condensed">
                                <tr>
                                    <td class="col-md-6">
                                        <div class="align-items-center d-flex">
                                            <span class="m-l-10 font-montserrat fs-11 all-caps" id="plano">Selecione Um
                                                Plano</span>
                                        </div>
                                    </td>
                                    <td class="align-items-center col-md-3 text-right">
                                        <div class="d-flex align-items-center">
                                            <span>Desconto </span>
                                            <span id="desconto">-</span>
                                            <span>%</span>
                                        </div>
                                    </td>
                                    <td class="align-items-center col-md-3 text-right">
                                        <span>Economia R$ </span>
                                        <a id="economia">-</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td colspan="3" class="col-md-3 text-right justify-content-end">
                                        <h4 class="text-primary no-margin font-montserrat d-flex align-items-center">
                                            <span>R$ </span>
                                            <span id="valor">-<span>
                                        </h4>
                                    </td>
                                </tr>
                            </table>
                            <p>A fatura estará disponível no seu histórico de pagamentos após a confirmação de
                                pagamento. <br>Condições de pagamento: Cartão de Crédito ou Boleto Bancário </p>
                            <p>Ao selecionar pagar agora, você concorda com os nossos <a href="#">Termos &amp;
                                    Condições</a></p>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="padding-30 sm-padding-5">
                            <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator nav-stack-sm"
                                role="tablist" data-init-reponsive-tabs="dropdownfx">
                                <li class="nav-item">
                                    <a class="active" data-toggle="tab" href="#tab1" data-target="#cartao_tab"
                                        role="tab"><i class="fa fa-shopping-cart tab-icon"></i> <span>Cartão de
                                            Crédito</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="" data-toggle="tab" href="#tab3" data-target="#boleto_tab" role="tab"><i
                                            class="fa fa-credit-card tab-icon"></i> <span>Boleto Bancŕio</span></a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane padding-20 sm-no-padding active slide-left" id="cartao_tab">
                                    <div class="row row-same-height">
                                        <form role="form" class="pagamento-cc-form">
                                            <div class="bg-master-light padding-30 b-rad-lg">
                                                <div class="d-flex align-items-baseline justify-content-between mb-3">
                                                    <h2 class="pull-left no-margin">Cartão de Crédito</h2>
                                                    <ul class="list-unstyled pull-right list-inline no-margin">
                                                        <li>
                                                            <a href="#">
                                                                <img width="51" height="32"
                                                                    data-src-retina="assets/img/form-wizard/visa2x.png"
                                                                    data-src="assets/img/form-wizard/visa.png"
                                                                    class="brand" alt="logo"
                                                                    src="assets/img/form-wizard/visa.png">
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="#" class="hint-text">
                                                                <img width="51" height="32"
                                                                    data-src-retina="assets/img/form-wizard/amex2x.png"
                                                                    data-src="assets/img/form-wizard/amex.png"
                                                                    class="brand" alt="logo"
                                                                    src="assets/img/form-wizard/amex.png">
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="#" class="hint-text">
                                                                <img width="51" height="32"
                                                                    data-src-retina="assets/img/form-wizard/mastercard2x.png"
                                                                    data-src="assets/img/form-wizard/mastercard.png"
                                                                    class="brand" alt="logo"
                                                                    src="assets/img/form-wizard/mastercard.png">
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="form-group form-group-default required">
                                                    <label>Número do Cartão</label>
                                                    <input type="text" class="form-control" name="numero_cartao"
                                                        placeholder="8888-8888-8888-8888" required>
                                                </div>
                                                <div class="form-group form-group-default required">
                                                    <label>Nome igual ao do Cartão</label>
                                                    <input type="text" class="form-control" placeholder="Nome no cartão"
                                                        required>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group form-group-default required"
                                                            title="Validade do cartão">
                                                            <label for="validade_cartao">Validade</label>
                                                            <input type="text" class="form-control" id="validade_cartao"
                                                                name="validade_cartao" placeholder="mês/ano"
                                                                required="">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group form-group-default required"
                                                            title="Código de segurança do cartão">
                                                            <label for="cvc_cartao">CVV </label>
                                                            <input type="text" class="form-control" id="cvc_cartao"
                                                                name="cvc_cartao"
                                                                placeholder="CVV / Código de Segurança" required=""
                                                                maxlength="4">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="form-group form-group-default required"
                                                            title="Validade do cartão">
                                                            <label for="validade_cartao">Parcelas</label>
                                                            <select type="text" class="form-control" id="parcelas"
                                                                required="" name="parcelas">

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="tab-pane padding-20 sm-no-padding slide-left" id="boleto_tab">
                                    <div class="row row-same-height">
                                        <div class="col-12">
                                            Lorem ipsum dolor sit amet consectetur adipisicing elit. In, error. Soluta
                                            autem, aspernatur minima quaerat tenetur obcaecati. Labore, ipsum. Tempora
                                            blanditiis fugiat delectus excepturi autem sunt temporibus ducimus nulla
                                            minus.
                                        </div>
                                        <div class="col-12 mt-2 d-flex justify-content-left">
                                            <button class="btn btn-success button">Imprimir boleto</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane padding-20 sm-no-padding slide-left" id="tab3">
                <div class="row row-same-height padding-30">
                    <h2>
                        Obrigado por renovar, seu plano a Seminovos agradeçe.
                    </h2>
                </div>
            </div>
            <div class="padding-20 sm-padding-5 sm-m-b-20 sm-m-t-20 bg-white clearfix">
                <ul class="pager wizard no-style">
                    <li class="next">
                        <button class="btn btn-laranja text-white btn-cons pull-right" type="button">
                            <span>Próximo</span>
                        </button>
                    </li>
                    <li class="next finish hidden">
                        <button class="btn btn-laranja text-white btn-cons pull-right" type="button">
                            <span>Finalizar</span>
                        </button>
                    </li>
                    <li class="previous">
                        <button class="btn btn-default btn-cons pull-right" type="button">
                            <span>Anterioir</span>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<!-- <div class="row">
    <div class="col-md-12">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>Escolha o tempo que deseja pagar:</h5>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-4">
                    <h5>Forma de pagamento:</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <hr></hr>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-4">
                    <hr></hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <h5>Valor mensal do plano R$ </h5>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-4">
                    <h5>Clique no botão abaixo para selecionar a forma de pagamento e finalizar a compra. </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="radioTempoContrato1" name="radioTempoContrato"
                               value="<?= $dadosFinanceiro['value_checbox_mensal'] ?>">
                        <label class="form-check-label" for="radioTempoContrato1">
                            Plano Mensal <?= $dadosFinanceiro['maisSite'] ?>
                        </label>
                    </div>
                    <p>R$ <?= $dadosFinanceiro['valor_mensal'] ?></p>
                    <p>Desconto de <?= $dadosFinanceiro['desconto_mensal'] ?></p>
                    <p>Economia de R$ <?= $dadosFinanceiro['economia_mensal'] ?></p>
                </div>
                <div class="col-md-1">
                </div>
                <div class="col-md-4">
                    <button class="btn btn-default" type="button">FINALIZAR COMPRA</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="radioTempoContrato2" name="radioTempoContrato"
                               value="<?= $dadosFinanceiro['value_checbox_trimestral'] ?>">
                        <label class="form-check-label" for="radioTempoContrato1">
                            Plano Trimestral <?= $dadosFinanceiro['maisSite'] ?>
                        </label>
                    </div>
                    <p>R$ <?= $dadosFinanceiro['valor_trimestral'] ?></p>
                    <p>Desconto de <?= $dadosFinanceiro['desconto_trimestral'] ?></p>
                    <p>Economia de R$ <?= $dadosFinanceiro['economia_trimestral'] ?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="radioTempoContrato3" name="radioTempoContrato"
                               value="<?= $dadosFinanceiro['value_checbox_semestral'] ?>">
                        <label class="form-check-label" for="radioTempoContrato1">
                            Plano Semestral <?= $dadosFinanceiro['maisSite'] ?>
                        </label>
                    </div>
                    <p>R$ <?= $dadosFinanceiro['valor_semestral'] ?></p>
                    <p>Desconto de <?= $dadosFinanceiro['desconto_semestral'] ?></p>
                    <p>Economia de R$ <?= $dadosFinanceiro['economia_semestral'] ?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" id="radioTempoContrato4" name="radioTempoContrato"
                               value="<?= $dadosFinanceiro['value_checbox_anual'] ?>">
                        <label class="form-check-label" for="radioTempoContrato1">
                            Plano Anual <?= $dadosFinanceiro['maisSite'] ?>
                        </label>
                    </div>
                    <p>R$ <?= $dadosFinanceiro['valor_anual'] ?></p>
                    <p>Desconto de <?= $dadosFinanceiro['desconto_anual'] ?></p>
                    <p>Economia de R$ <?= $dadosFinanceiro['economia_anual'] ?></p>
                </div>
            </div>
        </div>
    </div>
</div> -->