<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$pagamentos = $this->historicoPagamentos;
$statusPagamento = $this->arrayStatus;
$arrFormaPagamento = $this->arrayFormaPagamento;

?>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <?php if ($this->tipoCadastro == 1) { ?>
                <thead>
                    <tr>
                        <th>Tempo</th>
                        <th>Valor</th>
                        <th>Desconto</th>
                        <th>Total</th>
                        <th>Forma de Pagamento</th>
                        <th>Parcelas</th>
                        <th>Status</th>
                        <th>Faturas</th>
                        <th>Datas</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($pagamentos as $pagamento): ?>
                        <tr>
                            <td><?= $pagamento['tempoContrato'] ?> mês</td>
                            <td>R$ <?= $pagamento['valor'] ?></td>
                            <td>R$ <?= $pagamento['desconto'] ?></td>
                            <td>R$ <?= $pagamento['total'] ?></td>
                            <td><?= $pagamento['formaPagamento'] ?></td>
                            <td><?= $pagamento['parcelas'] ?></td>
                            <td><?= $statusPagamento[$pagamento['status']] ?></td>
                            <td><a class="btn btn-default" href="/fatura/revenda/id/<?= $pagamento['idPagamento'] ?>"
                                   role="button" target="_blank">Ver Fatura</a></td>
                            <td>Cad.: <?= $pagamento['dataCadastro'] ?><br>Ren.: <?= $pagamento['dataRenovacao'] ?>
                                <br>Exp.: <?= $pagamento['dataExpiracao'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            <?php } elseif ($this->tipoCadastro == 2) { ?>
                <thead>
                    <tr>
                        <th>Anúncio</th>
                        <th>Valor</th>
                        <th>Status</th>
                        <th>Data</th>
                        <th>Faturas</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($pagamentos as $pagamento): ?>
                        <tr>
                            <td><?= $pagamento['marca'] . ' ' . $pagamento['modelo'] . ' ' . $pagamento['caracteristica']; ?>
                                <br><?= $pagamento['nomePlano'] ?></td>
                            <td>R$ <?= $pagamento['total'] ?></td>
                            <td><?= $statusPagamento[$pagamento['status']] ?><br>Forma de
                                pagamento: <?= $arrFormaPagamento[$pagamento['formaPagamento']] ?></td>
                            <td><?= $pagamento['dataCadastro'] ?></td>
                            <td><a class="btn btn-default" href="/fatura/particular/id/<?= $pagamento['idPagamento'] ?>"
                                   role="button" target="_blank">Ver Fatura</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            <?php } ?>
        </table>
    </div>
</div>
