<form class="pagamento-pix-form">
    <div class="form-group form-group-default" title="Termos de adesão">
        <label>
            <input type="checkbox" name="termos" required>
            Li e estou de acordo com o <a href="/termos/pessoa-fisica" target="_BLANK" class="text-laranja" title="Click para abrir o termo de adesão">Termo de adesão</a>
        </label>
    </div>
    <div class="form-group">
        <input type="hidden" name="metodo" value="pix" required aria-required="true">
        <button type="submit" class="btn btn-success btn-block btn-submit-pagt block">GERAR PIX</button>
    </div>
</form>