<?php
$anoFabricacao = substr((string) $this->veiculo['anoFabricacao'], -2);
$anoModelo = substr((string) $this->veiculo['anoModelo'], -2);

$marcaModelo = $this->veiculo['marca'] . ' '
    . $this->veiculo['modelo'] . ' '
    . $anoFabricacao . '/'
    . $anoModelo;

$url = 'https://www.seminovos.com.br/' . implode('-', [
        $this->veiculo['marca'],
        $this->veiculo['modelo'],
        $anoFabricacao,
        $anoModelo,
        '-' . $this->veiculo['idVeiculo']
    ]);
$url = strtolower($url);

?>
<div class="row share-container align-baseline">
    <div style="font-weight: bold;color:#acacac;"> Quer acelerar sua venda? Compartilhe com seus amigos &nbsp;&nbsp;</div>
        <div class="fb-share-button"
             data-href="<?= $url ?>"
             data-layout="button"
             data-size="large"
             data-mobile-iframe="true"></div>&nbsp; 
        <div><a href="https://twitter.com/share"
           class="twitter-share-button"
           data-url="<?= $url ?>"
           data-text="Vendo <?= $marcaModelo ?>"
           data-via="seminovosbh"
           data-size="large"
           data-related="seminovosbh"
           data-hashtags="seminovosbh"></a>
    </div>

</div>

<?php // Twitter   ?>
<script>!function(d, s, id){var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location)?'http':'https'; if (!d.getElementById(id)){js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); }}(document, 'script', 'twitter-wjs');</script>
<?php // Facebook   ?>
<script>(function (d, s, id) {var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id))return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8&appId=984805604894951"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
