<div class="col-md-12">Titular: <strong>Seminovos Ltda</strong><br>CNPJ: <strong>08.030.680/0001-06</strong></div>
    <div class="row text-center m-t-20 m-b-20">
        
        <div class="col-md-4">
            <div  title="Banco Itaú">
                <img src="/img/bancos/logo-itau.jpg" title="Banco Itaú" alt="Logo Banco Itau" style="width: 50px; height: 50px;">
                <div>Agência: 0781</div>
                <div>C/C: 46.900-2</div>
                
                
            </div>
        </div>
        <div class="col-md-4">
            <div title="Banco Bradesco">
                <img src="/img/bancos/logo-bradesco.jpg" title="Banco Bradesco" alt="Logo Banco Bradesco" style="width: 50px; height: 50px;">
                <div>Agência: 2286-1</div>
                <div>C/C: 18.193-5</div>
            </div>
        </div>
        <div class="col-md-4">
            <div title="Banco do Brasil">
                <img src="/img/bancos/logo-bb.jpg" title="Banco do Brasil" alt="Logo Banco do Brasil" style="width: 50px; height: 50px;">
                <div>Agência: 1614-4</div>
                <div>C/C: 15.062-2</div>
            </div>
        </div>
    </div>

<div class="col-md-12 m-t-20 m-b-20">
    <small>Após efetuar o depósito ou transferência é necessário anexar o comprovante no menu: <strong>Meus veículos > Enviar Comprovante.</strong><br>
        Ou entrar em contato conosco no número (31) 3077-5888 informando os dados do transação.
    </small>
</div>
<form class="pagamento-transferencia-form">
    <h5>Anexar Comprovante</h5>
    <div class="form-group">
        <input type="file" class="form-control-file" id="comprovanteAnexo" name="comprovanteAnexo">
    </div>
    <br>
    <div class="form-group form-group-default" title="Termos de adesão">
        <label>
            <input type="checkbox" name="termos" required>
            Li e estou de acordo com o <a href="/termos/pessoa-fisica" target="_BLANK">Termo de adesão</a>
        </label>
    </div>
    <div class="row">
        <!-- <div class="col-md-6">
            <div class="form-group" title="Já fiz a transferência">
                <input type="file" name="comprovanteAnexo" id="comprovanteAnexo" required>
                <input type="hidden" name="metodo" value="deposito">
                <input type="hidden" name="tipoEmail" value="comprovante">
                <input type="hidden" name="nome" value="nome">
                <input type="hidden" name="email" value="email">
                <button type="submit" class="btn btn-success btn-block btn-submit-pagt block">ENVIAR COMPROVANTE</button>
            </div>
        </div> -->
        
            
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group" title="">
                <input type="hidden" name="metodo" value="deposito">
                <button type="submit" class="btn btn-info btn-block btn-submit-pagt block">ENVIAR COMPROVANTE</button>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group" title="">
                <a href="#" class="pagamento-finalizar-deposito btn btn-success btn-block">FINALIZAR COMPRA</a>
            </div>
        </div>
    </div>
</form>