<div class="col-md-12">Titular: <strong>Seminovos Ltda</strong><br>CNPJ: <strong>08.030.680/0001-06</strong></div>
    <div class="d-flex text-center justify-content-between my-3 flex-wrap">
        <?php foreach(
            [/*[   
                "nome"=> "Itaú",
                "img"=> "/img/bancos/logo-itau.jpg",
                "agencia" => "0781",
                "conta" => "46.900-2",
                "link" => "https://app.adjust.com/ezb10an_eg0ygy9?&campaign=Home_Varejo&adgroup=&creative=&fallback=http%3A%2F%2Fwww.itau.com.br/conveniencia/celular/"
            ],
            [
                "nome"=> "Bradesco",
                "img"=> "/img/bancos/logo-bradesco.jpg",
                "agencia" => "2286-1",
                "conta" => "18.193-5",
                "link" => "https://www.bradescocelular.com.br/app_redirect/index.html?deeplink=app/listadeconta"                
            ],*/
            [
                "nome"=> "Caixa",
                "img"=> "/img/bancos/logo-caixa-eco.jpg",
                "agencia" => "2984",
                "conta" => "00003919-6",
                "link" => "https://internetbanking.caixa.gov.br/sinbc/#!nb/login"
            ],
            /*[
                "nome"=> "Brasil",
                "img"=> "/img/bancos/logo-bb.jpg",
                "agencia" => "1614-4",
                "conta" => "15.062-2",
                "operacao" => "003",
                "link" => "https://www.bb.com.br/AppBBFloat"

            ]*/]  as $banco): ?>
        <div class="w-50 mb-2">
            <div title="Banco <?=$banco['nome']?>">
                <a href="<?= $banco['link'] ?>" target="_BLANK">
                    <img src="<?=$banco['img']?>" title="Banco <?=$banco['nome']?>" alt="Logo <?=$banco['nome']?>" style="width: 50px; height: 50px;">
                </a>
                <div class="d-flex justify-content-center">
                    <div>Agência:</div>
                    <div><?=$banco['agencia']?></div>
                </div>
                <div class="d-flex justify-content-center">
                    <div>C/C:</div>
                    <div><?=$banco['conta']?></div>
                </div>
                <?php if($banco['operacao'] ?? false): ?>
                    <div class="d-flex justify-content-center">
                        <div>OP:</div>
                        <div><?=$banco['operacao']?></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php endforeach;?>
        <div class="w-50 mb-2">
            <div title="">
                <img src="/img/pagamento/pix.png" title="Banco Pix" alt="Logo Pix" style="width: 50px; height: 50px;">
                <div class="d-flex justify-content-center">
                    <div>Chave PIX:</div>
                </div>
                <div class="d-flex justify-content-center">
                    <div>08.030.680/0001-06</div>
                </div>
                <img src="/img/bancos/inter.png" title="Banco Inter" alt="Logo Inter" style="width: 25px; height: 25px;">
                AG: 0001 - C/C: 16952949-5
            </div>
        </div>
    </div>

<div class="d-flex m-t-20 m-b-20">
    <small>
        <div>
            Após efetuar o depósito ou transferência é necessário anexar o comprovante no menu: 
        </div>
        <div>
            <strong>Meus veículos > Enviar Comprovante.</strong>
        </div>
        <div>
            Ou entrar em contato conosco no número: <a href="tel://(31) 3077-5888" class=text-sucess>(31) 3077-5888</a>
        </div>
        <div>
           informando os dados do transação.
        </div>
    </small>
</div>
<form class="pagamento-transferencia-form">
    <h5>Anexar Comprovante</h5>
    <div class="form-group">
        <input type="file" class="form-control-file" id="comprovanteAnexo" name="comprovanteAnexo" required="required">
    </div>
    <br>
    <div class="form-group form-group-default d-flex align-items-center font-theme checkbox check-success" title="Termos de adesão">
        <input type="checkbox" name="termos" required="required" value="1" id="termo_ad_cdb">
        <label for="termo_ad_cdb"> 
            <span>
                Li e estou de acordo com os
                <div>
                    <a href="/termos/pessoa-fisica" target="_BLANK" class="text-laranja">Termos de adesão</a>
                </div>
            </span>
        </label>

    </div>
    <!-- <div class="row">
        <div class="col-md-6">
            <div class="form-group" title="Já fiz a transferência">
                <input type="file" name="comprovanteAnexo" id="comprovanteAnexo" required>
                <input type="hidden" name="metodo" value="deposito">
                <input type="hidden" name="tipoEmail" value="comprovante">
                <input type="hidden" name="nome" value="nome">
                <input type="hidden" name="email" value="email">
                <button type="submit" class="btn btn-success btn-block btn-submit-pagt block">ENVIAR COMPROVANTE</button>
            </div>
        </div> 
    </div> -->
    <div class="d-flex flex-wrap justify-content-around">
        <div class="w-100 my-3 text-center">
            <strong>ENVIAR COMPROVANTE</strong>
        </div>
        <div class="">
            <input class="d-none" type="hidden" name="metodo" value="deposito">
            <button type="submit" class="btn-submit-pagt btn btn-info d-flex h-auto">AGORA</button>
        </div>
        <button type="submit"  class="pagamento-finalizar-deposito btn btn-success d-flex h-auto">DEPOIS</button>
    </div>
</form>