<div class="container">
    <div class="row">
        <section class="chat-root offset-md-1 col-md-10">
            <div class="loading-container">
                <div class="text-center">
                    <div class="spinner-border text-laranja" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="feedback-text text-white animated pulse infinite">
                        Carregando...
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>