<form>
    <table>
        <thead>
            <tr>
                <th colspan="2">
                    <img src="/img/bancos/logo-itau.jpg" title="Banco Itau" alt="Logo Banco Itau" style="width: 50px; height: 50px;">
                </th>
                <th colspan="2">
                    <img src="/img/bancos/logo-bradesco.jpg" title="Banco Bradesco" alt="Logo Banco Bradesco" style="width: 50px; height: 50px;">
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Agência:</td>
                <td>0781</td>
                <td>Agência:</td>
                <td>2286-1</td>
            </tr>
            <tr>
                <td>C/C:</td>
                <td>46.900-2</td>
                <td>C/C:</td>
                <td>18.193-5</td>
            </tr>
            <tr>
                <td>CPNJ:</td>
                <td>08.030.680/0001-06</td>
                <td>CPNJ:</td>
                <td>08.030.680/0001-06</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
            <tr>
                <th colspan="2" width="50%">
                    <img src="/img/bancos/logo-bb.jpg" title="Banco de Brasil" alt="Logo Banco de Brasil" style="width: 50px; height: 50px;">
                </th>
                <th colspan="2">
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Agência:</td>
                <td>1614-4</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>C/C:</td>
                <td>15.062-2</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>CPNJ:</td>
                <td>08.030.680/0001-06</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
    <div class="form-group" title="Termos de adesão">
        <label>
            <input type="checkbox" required>
            Li e estou de acordo com o <a href="/termos/pessoa-fisica" target="_BLANK">Termo de adesão</a>
        </label>
    </div>
    <div class="form-inline">
        <div class="form-group" title="Já fiz a transferência">
            <input type="hidden" name="metodo" value="deposito">
            <input type="hidden" name="tipoEmail" value="comprovante">
            <button type="submit" class="btn btn-success btn-block btn-submit-pagt block">ENVIAR COMPROVANTE</button>
        </div>
        <div class="form-group" title="Ainda vou fazer a transferência">
            <a href="#" class="btn btn-success btn-block">FINALIZAR COMPRA</a>
        </div>
    </div>
</form>