<?php

use SnBH\ApiModel\Model\VeiculosStatus;

/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

$veiculo = $this->veiculo ?: false;

$rotasAnuncio = [
    'veiculo' => [
        'dados' => 'dados',
        'preco' => 'preco',
        'mais-informacoes' => 'mais-informacoes',
        'fotos' => 'fotos',
        'video' => 'video',
    ],
    'plano' => $this->url('criar-anuncio/anuncio/planos', $routeParams),
    'checkout' => $this->url('criar-anuncio/anuncio/pagamento', $routeParams),
];

if ($this->userInfo('tipoCadastro') == 1) {
    unset($rotasAnuncio['checkout']);
    $rotasAnuncio['finalizar'] = $this->url('criar-anuncio/anuncio/finalizar', $routeParams);
}

if ($veiculo && ($veiculo['idStatus'] == VeiculosStatus::STATUS_ATIVO || $veiculo['idStatus'] == VeiculosStatus::STATUS_FOTOS_ALTERADAS)) {
    switch ($_GET['editar'] ?? null) {
        case 'fotos':
            unset(
                $rotasAnuncio['veiculo']['video'],
                $rotasAnuncio['plano'],
                $rotasAnuncio['checkout']
            );
            break;
        case 'planos':
            unset(
                $rotasAnuncio['veiculo']['dados'],
                $rotasAnuncio['veiculo']['preco'],
                $rotasAnuncio['veiculo']['mais-informacoes'],
                $rotasAnuncio['veiculo']['fotos'],
                $rotasAnuncio['veiculo']['video']
            );
            break;

        default:
            unset(
                $rotasAnuncio['plano'],
                $rotasAnuncio['checkout']
            );
            break;
    }
}
    if($veiculo && ($veiculo['idStatus'] == VeiculosStatus::STATUS_PENDENTE)){
            echo 'Não tão rápido! Essa ação não é valida, estamos de olho.';
            unset(
                $rotasAnuncio['veiculo']['dados'],
                $rotasAnuncio['veiculo']['preco'],
                $rotasAnuncio['veiculo']['mais-informacoes'],
                $rotasAnuncio['veiculo']['fotos'],
                $rotasAnuncio['veiculo']['video']
            );
            die;
    }

foreach ($rotasAnuncio['veiculo'] as &$rota) {
    $rota = $this->url('criar-anuncio/anuncio/dados/pages', ['action' => $rota] + $routeParams);
}

if ($this->idVeiculo) {
    $this->headTitle()->append(strtoupper($this->placa) . ' ' . $this->marca . ' ' . $this->modelo);
} else {
    $this->headTitle()->append('Novo anúncio');
}

?>
<div id="dados-basicos" class="hide">
    <form>
        <input type="hidden" id="tipoCadastro" name="tipoCadastro" value="<?= $this->tipoCadastro ?>" class="tipoCadastro">
        <input type="hidden" id="idStatus" name="idStatus" value="<?= $this->idStatus ?>" class="idStatus">
        <input type="hidden" id="idVeiculo" name="idVeiculo" value="<?= $this->idVeiculo ?>" class="idVeiculo">
        <input type="hidden" id="idAnuncioVeiculo" name="idAnuncioVeiculo" value="<?= $this->idAnuncioVeiculo ?>" class="idAnuncioVeiculo">
        <input type="hidden" id="idPlano" name="idPlano" value="<?= $this->idPlano ?>" class="idPlano">
        <input type="hidden" id="total" name="total" value="<?= $this->total ?>" class="total">
        <input type="hidden" id="acao" name="acao" value="" class="acao">
        <input type="hidden" id="codFipe" name="codFipe" value="<?= $this->codFipe ?>" class="codFipe">
        <br>
    </form>
</div>
<div class="row">
    <div class="col-lg-8 offset-lg-2 col-xl-6 offset-xl-3 anuncio-steps step-container">

        <div class="step-0 step-veiculo step-container active">
            <?php
            $count = 0;
            unset($rota);
            $firstStep = true;
            foreach ($rotasAnuncio['veiculo'] as $name => $rota) {
                echo '<div class="' . ('step-' . $count++) . ' step-' . $name . ($firstStep ? ' active' : '') . '" data-step-label="' . $name . '" data-url="' . $rota . '"></div>';
                $firstStep = false;
            }

            ?>
        </div>
        <?php
        $count = 0;
        unset($rota);
        unset($rotasAnuncio['veiculo']); // Já foi impresso acima

        foreach ($rotasAnuncio as $name => $rota) {
            echo '<div class="' . ('step-' . $count++) . ' step-' . $name . '" '
            . 'data-step-label="' . $name . '" '
            . 'data-url="' . $rota . '"></div>';
        }

        ?>
    </div>
</div>

<div class="row step-controls">
    <div class="col-6 col-md-3 offset-md-3">
        <button class="btn-voltar btn btn-lg btn-secondary btn-block text-white" title="Voltar">VOLTAR</button>
    </div>
    <div class="col-6 col-md-3 offset--1">
        <button class="btn-continuar btn btn-lg btn-laranja btn-block text-white" title="Continuar">CONTINUAR</button>
    </div>
</div>
<br class="clearfix">
