<div class="container container-fixed-lg mb-5 pb-5">
    <div class="row">
        <div class="col text-center">
            <div class="h2">Seu anúncio foi criado!</div>
            <br>
            E agora? Já quer publicá-lo agora mesmo ou depois?
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <a href="#" class="btn btn-info btn-block btn-finalizar h-100" data-status="5" title="Você pode deixar para publicar esse veículo depois">
                Publicar mais tarde
            </a>
        </div>
        <div class="col">
            <a href="#" class="btn btn-success btn-block btn-finalizar h-100" data-status="2" title="Seu anúncio irá para o ar agora!">
                Publicar agora
            </a>
        </div>
    </div>
</div>
