<div class="sidebar-menu mt-md-5">
  <!-- BEGIN SIDEBAR MENU ITEMS-->
  <ul class="menu-items">
    <li class="mt-md-5 m-b-20">
      <div class="p-l-10 p-r-10">
        <a class="btn-block btn btn-laranja text-capitalize" data-toggle="collapse" href="#cirarAnuncio" role="button"
          aria-expanded="false" aria-controls="collapseExample">
          <span class="text-black title">
            Novo Anúncio
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
          </span>
        </a>
        <div class="collapse mt-2" id="cirarAnuncio">
          <div class="d-flex justify-content-around">
            <a class="link-white" href="/carro">
              <i class="fa-2x icon icon-type-car"></i>
            </a>
            <a class="link-white" href="/moto">
              <i class="fa-2x icon icon-type-moto"></i>
            </a>
            <a class="link-white" href="/caminhao">
              <i class="fa-2x icon icon-type-truck"></i>
            </a>
          </div>
        </div>
      </div>
    </li>
    <li class="m-t-30 hide">
      <a href="<?= $this->url('restrito') ?>" class="detailed">
        <span class="title">Home</span>
      </a>
      <span class="bg-success icon-thumbnail"><i class="fa fa-home"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/meus-veiculos') ?>">
        <span class="title">Meus Veículos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-car" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/historico-pagamentos') ?>">
        <span class="title">Histórico Pagamentos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-history"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/meus-dados') ?>">
        <span class="title">Meus Dados</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-user-circle" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('logout') ?>">
        <span class="title">Sair</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-sign-out" aria-hidden="true"></i></span>
    </li>

    <li>
      <?php  foreach ($arrayPlanos as $i => $plano): list($slug, $plano, $fotos, $nivel, $video, $preco, $classValue, $totalAnuncio, $totalAnuncioPublicado) = $plano; ?>
      <div class="mx-3 justify-content-start d-flex align-items-center bg-color-menu-dark my-1 p-2">
        <div class="linha-plano size-3x plano-<?= $slug ?> m-0">
          <div class="icon-plano m-0">
            <span class="bar-1"></span>
            <span class="bar-2"></span>
            <span class="bar-3"></span>
            <span class="bar-4"></span>
            <span class="bar-4"></span>
          </div>
        </div>
        <div class="text-left ml-2">
          <div>
            <b><?= $plano ?></b>
          </div>
          <div>
            <?php echo $totalAnuncioPublicado . "/" . $totalAnuncio ?>
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </li>
  </ul>
  <div class="clearfix"></div>

</div>