<div class="sidebar-menu">
  <!-- BEGIN SIDEBAR MENU ITEMS-->
  <ul class="menu-items">
    <li class="m-t-30 m-b-20">
      <div class="p-l-10 p-r-10">
        <a href="/carro" class="btn-block btn btn-laranja">
          <span class="text-black">
            Novo Anúncio
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
          </span>
        </a>
      </div>
    </li>
    <li class="m-t-30 m-b-20">
      <div class="p-l-10 p-r-10">
        <a href="/criar-anuncio-flow" class="">
          <span class="text-muted">
            Anúncios Flow
          </span>
        </a>
      </div>
    </li>
    <li class="m-t-30 hide">
      <a href="<?= $this->url('restrito') ?>" class="detailed">
        <span class="title">Home</span>
      </a>
      <span class="bg-success icon-thumbnail"><i class="fa fa-home"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/meus-veiculos') ?>">
        <span class="title">Meus Veículos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-car" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/historico-pagamentos') ?>">
        <span class="title">Histórico Pagamentos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-history"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/meus-dados') ?>">
        <span class="title">Meus Dados</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-user-circle" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('logout') ?>">
        <span class="title">Sair</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-sign-out" aria-hidden="true"></i></span>
    </li>
  </ul>
  <div class="clearfix"></div>
</div>