<?php

/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */
global $container;
$url = $container->get('Config')['SnBH']['urls']['site'] ?? "/meus_veiculos";
?>
<div class="sidebar-menu mt-md-5">
    <!-- BEGIN SIDEBAR MENU ITEMS-->
    <ul class="menu-items">
        <li class="mt-md-5 m-b-20">
            <div class="p-l-10 p-r-10">
                <a class="btn-block btn btn-laranja text-capitalize" href="/criar-anuncio" title="Novo Anúncio">
                    <span class="text-black">
                        <span class="title">Novo Anúncio</span>
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                    </span>
                </a>
            </div>
        </li>
        <li class="m-t-30 hide">
            <a href="<?= $this->url('restrito') ?>" class="detailed" title="Home">
                <span class="bg-success icon-thumbnail"><i class="fa fa-home"></i></span>
                <span class="title">Home</span>
            </a>
        </li>
        <?php if (SHOW_CHAT) : ?>
            <li class="menu-chat">
                <a href="<?= $this->url('restrito/chat') ?>" title="Chat">
                    <span class="icon-thumbnail"><i class="fa fa-comments" aria-hidden="true"></i></span>
                    <span class="title">Chat</span>
                </a>
            </li>
        <?php endif; ?>
        <li class="">
            <a href="<?= $this->url('restrito/meus-veiculos') ?>" title="Meus Veículos">
                <span class="icon-thumbnail"><i class="fa fa-car" aria-hidden="true"></i></span>
                <span class="title">Meus Veículos</span>
            </a>
        </li>
        <li class="">
            <a href="<?= $this->url('restrito/historico-pagamentos') ?>" title="Histórico Pagamentos">
                <span class="icon-thumbnail"><i class="fa fa-history"></i></span>
                <span class="title">Histórico Pagamentos</span>
            </a>
        </li>
        <li class="">
            <a href="<?= $this->url('restrito/central-informacoes') ?>" title="Central de Informações">
                <span class="icon-thumbnail"><i class="fa fa-newspaper" aria-hidden="true"></i></span>
                <span class="title">Central de Informações</span>
            </a>
        </li>
        <li class="qtd-anuncios-menu">
            <?= $this->partial('partials/qtd-anuncios-menu.phtml') ?>
        </li>
        <li>
            <a href="<?= $url . '?' . substr(random_int(0, mt_getrandmax()), 0, 4) ?>" title="Ir para o site">
                <span class="icon-thumbnail">
                    <img src="/favicon.ico">
                </span>
                <span class="title">Ir para o site</span>
            </a>
        </li>
        <li>
            <a href="http://wa.me/5531996071787" target="_blank" title="Atendimento por WhatsApp">
                <span class="icon-thumbnail"><i class="fa-brands fa-whatsapp" aria-hidden="true"></i></span>
                <span class="title">Atendimento por WhatsApp</span>
            </a>
        </li>
    </ul>
    <div class="clearfix"></div>
    <div class="btn-sidebar-collapse">
        <div class="btn-collapse" title="Fechar menu">
            <i class="fa fa-chevron-left" aria-hidden="true"></i>
        </div>
        <div class="btn-expand" title="Abrir menu">
            <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </div>
    </div>
</div>
