<?php /* @var $this \AreaRestrita\View\Helper\AutocompleteClass */ 
$fraseExpiracao = "Expira Hoje";
if($diasParaExpirar > 0){
  $fraseExpiracao = "Expira em ".$diasParaExpirar." dias";
}
if($diasParaExpirar > 7){
  $fraseExpiracao = "Expirará em ".$dataExpiracaoRevenda;
}

?>
<div class="sidebar-menu mt-3">
  <!-- BEGIN SIDEBAR MENU ITEMS-->
  <ul class="menu-items mt-5">
    <li class="m-t-30 m-b-20">
      <div class="p-l-10 p-r-10">
        <a class="btn-block btn btn-laranja text-capitalize" data-toggle="collapse" href="#cirarAnuncio" role="button"
          aria-expanded="false" aria-controls="collapseExample">
          <span class="text-black title">
            Novo Anúncio
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
          </span>
        </a>
        <div class="collapse mt-2" id="cirarAnuncio">
          <div class="d-flex justify-content-around">
            <a class="link-white" href="/carro">
              <i class="fa-2x icon icon-type-car"></i>
            </a>
            <a class="link-white" href="/moto">
              <i class="fa-2x icon icon-type-moto"></i>
            </a>
            <a class="link-white" href="/caminhao">
              <i class="fa-2x icon icon-type-truck"></i>
            </a>
          </div>
        </div>
      </div>
    </li>
    <li class="m-t-30 hide">
      <a href="<?= $this->url('restrito') ?>" class="detailed">
        <span class="title">Home</span>
      </a>
      <span class="bg-success icon-thumbnail"><i class="fa fa-home"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/meus-veiculos') ?>">
        <span class="title">Meus Veículos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-car b-transparent-white" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/historico-pagamentos') ?>">
        <span class="title">Histórico Pagamentos</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-history"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/financeiro') ?>">
        <span class="title">Financeiro</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-money" aria-hidden="true"></i></span>
    </li>
    <li class="">
      <a href="<?= $this->url('restrito/contrato-revenda') ?>">
        <span class="title">Contrato</span>
      </a>
      <span class="icon-thumbnail"><i class="fa fa-address-book-o" aria-hidden="true"></i></span>
    </li>

    <li class="qtd-anuncios-menu">
        <?=
        $this->partial('partials/qtd-anuncios-menu.phtml', [
            'arrayPlanos' => $arrayPlanos
        ])

        ?>
    </li>
    <li class="text-white mb-4 pl-3 ml-2 ml-md-0 mb-md-0 d-flex align-items-center">
      <h4 class="mr-2">
          <i class="text-white fa fa-clock-o" aria-hidden="true"></i>
      </h4>
      <h5 class="text-white">
        O seu plano <?= $fraseExpiracao ?>
      </h5>
    </li>
  </ul>
  <div class="clearfix"></div>
</div>