<!-- Modal -->
<div class="hide dados-basicos d-none">
    <form method="POST" name="formdadosBasicos" id="formdadosBasicos" action="/" class="hide d-none">
        <input type="hidden" name="tipoCadastro" disabled>
        <input type="hidden" name="cpfCnpj" disabled>
        <input type="hidden" name="idCadastro" disabled>
        <input type="hidden" name="email" disabled>
    </form>
</div>

<div class="modal fade" id="modalErroSenha" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="w-100 text-center mb-2"><h5 class="m-0 text-danger">Atenção!</h5></div>
            </div>
            <div class="modal-body">
                <div class="text-left">
                    <p class="text-laranja msg-principal">Usuário e/ou Senha estão incorretos</p>
                    <p>Confira os campos de usuário e senha e tente novamente</p>
                </div>
            </div>
            <div class="modal-footer mt-3 mb-2">
                <button type="submit" data-dismiss="modal" aria-label="Fechar" class="btn btn-default">Ok</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCuidado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção!!</b></h5>
                <div class="mt-4 text-left">
                    <p>Detectamos Ações Maliciosas!!</p>
                    <p>Sua sessão foi inválidada faça login novamente e tenha cuidado com o que tenta acessar!</p>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
        </div>
    </div>
</div>

<!-- Modal email e senha from cpf -->
<div class="modal fade" id="modalLembrarSenha" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaLabel"
     aria-hidden="true">
    <form method="POST" name="formContatosCpfCpnj" id="formEmailTelFromCpf" action="email-telefone-from-cpf">
        <input type="hidden" class="d-none" disabled name="tipoCadastro" value="2">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <?php /*<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button> */?>
                <div class="modal-header">
                    <span>Informe seu <b>CPF</b> ou seu <b>E-MAIL</b></span>
                </div>
                <div class="modal-body mt-2">
                    <div class="">
                        <span>CPF</span>
                        <input type="hidden" name="tokenResetarSenha" value="">
                        <input type="text" id="cpfOuCpnj" data-mask="000.000.000-00" name="cpfOuCpnj"  class="form-control" placeholder="000.000.000-00" minlength="10" maxlength="15">
                    </div>

                    <div class="mt-2">
                        <span>E-mail</span>
                        <input type="email" id="resetPasswordEmail" name="email" class="form-control" minlength="10" maxlength="256">
                    </div>
                </div>
                <div class="modal-footer mt-3">
                    <button type="submit" class="btn btn-default">Enviar</button>
                </div>
                <div class="text-center mt-3">
                    <b><a href="#" data-dismiss="modal" aria-label="Fechar" class="link-laranja">CANCELAR</a></b>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Modal escolha resetar senha -->
<div class="modal fade" id="modalRecuperarSenha" tabindex="-1" role="dialog" aria-labelledby="modalRecuperarSenhaLabel"
     aria-hidden="true">
    <form method="POST" name="formLembrarSenha" id="formLembrarSenha" action="remember-pass">
        <input type="hidden" name="cpfCnpjRetorno" id="cpfCnpjRetorno" class="hide">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <?php /*<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button> */?>
                <div class="modal-header">
                    <div class="w-100 text-center mb-2"><h2 class="m-0">Recupere sua senha!</h2></div>
                </div>

                <div class="modal-body mt-2 options">
                    <div class="sms w-100 d-flex flex-column">
                        <div class="w-100 pt-2 border-0 h4">
                            Receber código por SMS para criar uma nova senha:
                        </div>
                        <a href="" class="w-100 py-2">
                            <span class="btn btn-success">
                                <b class="mr-2">Enviar código:</b>
                                <span><b><span disabled data-retorno-telefone></span></b> </span>
                            </span>
                            <div class="text-left "><span>O código pode demorar alguns minutos para chegar.</span></div>
                        </a>
                    </div>
                    <div class="token w-100 d-flex">
                        <a href="" class="w-100 py-2">
                            <b class="mr-2 btn btn-success">Já tem um código?</b>
<!--                            <span>já possuo o código enviado para: </br><b><span disabled data-retorno-telefone></span></b> </span>-->
                            <br>
                            <span>Click aqui para inserir o código recebido</br>
                        </a>
                    </div>
                    <hr>
                    <div class="email w-100 d-flex flex-column">
                        <div class="w-100 pt-2 border-0 h4">Receber nova senha:</div>
                        <div class="w-100 pt-2 border-0">É gerado uma nova senha e enviado para o seu <b>e-mail</b> de cadastro.</div>
                        <a href="" class="w-100 pt-2 border-0">
                            <span class="btn btn-success">
                            <b class="mr-2">Email:</b>
                            <span><b><span data-retorno-email></span></b> </span>
                            </span>
                        </a>
                    </div>

                </div>
                <div class="text-center mt-3">
                    <b><a href="#" data-dismiss="modal" aria-label="Fechar" class="link-laranja">CANCELAR</a></b>
                </div>
            </div>
        </div>
    </form>
</div>


<!-- Modal lembrar senha revenda -->
<div class="modal fade" id="modalLembrarSenhaRevenda" tabindex="-1" role="dialog" aria-labelledby="modalLembrarSenhaRevendaLabel"
     aria-hidden="true">
    <form method="POST" name="formContatosCpfCpnj" id="formEmailTelFromCpnj" action="email-telefone-from-cpf">
        <input type="hidden" class="d-none" disabled name="tipoCadastro" value="1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <span>Informe seu <b>CNPJ</b> para receber uma nova senha</span>
                </div>
                <div class="modal-body mt-2">
                    <div class="">
                        <span>CNPJ</span>

                        <input type="text" id="cpfOuCpnj" name="cpfOuCpnj" data-mask="00.000.000/0000-00"  class="form-control" placeholder="00.000.000/0000-00" required="required" minlength="14" maxlength="18">
                    </div>
                </div>
                <div class="modal-footer mt-3">
                    <button type="submit" class="btn btn-default">Enviar</button>
                </div>
                <div class="text-center mt-3">
                    <b><a href="#" data-dismiss="modal" aria-label="Fechar" class="link-laranja">CANCELAR</a></b>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Modal recuperar senha via telefone -->
<div class="modal fade" id="modalValidaToken" tabindex="-1" role="dialog" aria-labelledby="modalValidaTokenLabel" aria-hidden="true">
    <form method="POST" name="formValidaToken" id="formValidaToken" action="validate-token">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="w-100 text-center mb-2"><h5 class="m-0">Informe o código de verificação</h5></div>
                    <div class="text-left d-flex"><span>Digite abaixo o código recebido por <b>SMS</b> em: </br><span data-retorno-telefone></span></span></div>
                </div>
                <div class="modal-body mt-3">
                    <div class="w-100 d-flex justify-content-center">                        
                        <input type="text" id="token" name="token" data-mask="0000"  class="form-control w-50 text-center" placeholder="0000" required="required" minlength="4" maxlength="4">
                    </div>
                </div>
                <div class="modal-footer mt-3">
                    <button type="submit" class="btn btn-default">Validar</button>
                </div>
                <div class="text-center mt-3">
                    <b><a href="#" data-dismiss="modal" aria-label="Fechar" class="link-laranja">CANCELAR</a></b>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Modal nova senha -->
<div class="modal fade" id="modalNovaSenha" tabindex="-1" role="dialog" aria-labelledby="modalNovaSenhaLabel" aria-hidden="true">
    <form method="POST" name="formNovaSenha" id="formNovaSenha" action="remember-pass-save">
        <input type="hidden" name="idCadastro" class="hide" disabled>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="w-100 text-center mb-2"><h5 class="m-0">Cadastre a sua nova senha</h5></div>
                </div>
                <div class="modal-body mt-2">
                    <div class="">
                        <span>Senha</span>
                        <div class="input-group group-senha">
                            <input type="password" id="senha" name="senha" class="form-control" placeholder="*****" required="required" minlength="4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-eye-slash" aria-hidden="true"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <span>Confirme sua senha</span>
                        <div class="input-group group-senha">
                            <input type="password" id="senhaConf" name="senhaConf" class="form-control" placeholder="*****" required="required" minlength="4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-eye-slash" aria-hidden="true"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer mt-3">
                    <button type="submit" class="btn btn-default">Salvar Senha</button>
                </div>
                <div class="text-center mt-3">
                    <b><a href="#" data-dismiss="modal" aria-label="Fechar" class="link-laranja">CANCELAR</a></b>
                </div>
            </div>
        </div>
    </form>
</div>