<?php
/* @var $this Zend\View\Renderer\PhpRenderer */

?>

<div class="snbh-logo-container">
  <!--<img src="/img/svg/snbh_logo.svg" alt="logo" class="snbh-logo" width="180" height="66">-->
  <svg viewBox="0 0 180 66" width="180" height="66" class="snbh-logo">
    <use xlink:href="/img/svg/snbh_logo.svg#layer_car" class="layer-car"></use>
    <use xlink:href="/img/svg/snbh_logo.svg#layer_letters" class="layer-letters"></use>
  </svg>
</div>

<div class="forms-container">
  <p class="p-t-35">Preencha corretamente os campos abaixo e clique no botão entrar para acessar sua área restrita.</p>
  <br class="clearfix">


  <form class="tipo-cadastro-container container">
    <div class="row">
      <div class="col-6">
        <div class="form-check form-check-inline" title="Entrar usando minha conta particular">
          <input type="radio" class="form-check-input" id="radioTipoCadastroParticular" name="tipoCadastro"
            value="container-form-particular" checked>
          <label class="form-check-label" for="radioTipoCadastroParticular">
            Particular
          </label>
        </div>
      </div>
      <div class="col-6">
        <div class="form-check form-check-inline" title="Entrar usando minha conta de revendedor">
          <input type="radio" class="form-check-input" id="radioTipoCadastroRevenda" name="tipoCadastro"
            value="container-form-revenda">
          <label class="form-check-label" for="radioTipoCadastroRevenda">
            Revenda
          </label>
        </div>
      </div>
    </div>
  </form>
  <?php
  $this->particularForm->get('entrar')->setAttribute('class', 'btn-warning btn-block btn-lg');
  $this->revendaForm->get('entrar')->setAttribute('class', 'btn-warning btn-block btn-lg');

  ?>
  <div class="forms-group">
    <div class="container-form-particular">
      <?= $this->form($this->particularForm) ?>
    </div>
    <div class="container-form-revenda hide">
      <?= $this->form($this->revendaForm) ?>
    </div>
  </div>
    <div class="row">
        <div class="col-md-6 no-padding sm-p-l-10"></div>
        <div class="col-md-6 d-flex align-items-center justify-content-end">
            <a href="#" class="text-info small"><small class="semi-bold">Esqueceu sua senha?</small></a>
        </div>
    </div>
    <br>
    <div id="novo-cadastro">
        <div class="row">
            <h6 class="text-amarelo bold">Não sou cadastrado</h6>
            <p class="text-justify">Para anunciar seu veículo, é necessário se cadastrar em nosso banco de dados. Digite
                abaixo seu CPF, e clique no botão indicado para continuar.</p>
        </div>
        <form id="form-login" class="p-t-15" role="form" action="">
            <div class="row">
                <div class="col-md-12 no-padding sm-p-l-12">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" required="">
                    </div>
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-primary btn-cons m-t-10" type="submit">Cadastrar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalErroSenha" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção</b></h5>
        <div class="mt-4 text-left">
          <p>Usuário e/ou Senha estão incorretos</p>
          <p>Confira os campos de usuário e senha e tente novamente</p>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modalCuidado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><b class="text-danger">Atenção!!</b></h5>
        <div class="mt-4 text-left">
          <p>Detectamos Ações Maliciosas!!</p>
          <p>Sua sessão foi inválidada faça login novamente e tenha cuidado com o que tenta acessar!</p>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
      </div>
    </div>
  </div>
</div>