<?php $urlCadastrar = ($this->cadastroSimples ?? false) ? '/cadastro-simples' : '/me-cadastrar' ?>
<div class="login-area">
    <div class="titulo text-center py-4">
        Entre com suas informações para ver e gerenciar sua conta
    </div>

    <div class="switch-container">
        <div class="switch-field">
            <input type="radio" id="radioTipoCadastroParticular" class="radioTipoCadastro" name="tipoCadastro" data-cookie="particular" value="container-form-particular" checked/>
            <label class="m-0" for="radioTipoCadastroParticular" title="Entrar como particular">Particular</label>
            
            <input type="radio" id="radioTipoCadastroRevenda" class="radioTipoCadastro" name="tipoCadastro" data-cookie="revenda" value="container-form-revenda" />
            <label class="m-0" for="radioTipoCadastroRevenda"  title="Entrar como revenda">Revenda</label>
        </div>
    </div>
    <div class="conteudo">
        <div class="forms">
            <div class="loading-container hide">
                <div class="spinner-border"></div>
                <div class="feedback-text"></div>
            </div>
            <div class="container-form-particular">
                <?=
                $this->partial('./partials/form-particular', [
                    'formLogin' => $this->particularForm
                ])
                ?>
            </div>
            <div class="container-form-revenda hide">
                <?=
                $this->partial('./partials/form-revenda', [
                    'formLogin' => $this->revendaForm
                ])
                ?>
            </div>
            <div class="separador">
                <span></span>ou<span></span>
            </div>
            <div class="cadastrar mt-3">
                <a href="<?= $urlCadastrar ?>" title="Criar uma conta" class="btn btn-laranja btn-cadastrar text-center">
                    Não tem uma conta? Criar conta
                </a>
            </div>
        </div>
    </div>
    <div class="aviso mt-3">
        <div class="esquerda">
            <div class="text-center">
                <img src="/img/icons/warning.png" alt="" srcset="">
            </div>
            <div class="text-center mt-2">
                <span>Atenção</span>
            </div>
        </div>
        <div class="direita">
            
            <span class="mt-2">
                A Seminovos <b>NÃO</b> faz contato por <b>telefone</b> ou
                <b>whatsapp</b> solicitando código de verificação de
                anúncio ou similar.
            </span>

            <div>
                <span class="mt-2"><b>Cuidado para não cair em golpes</b></span>
            </div>

            <span class="mt-3">Estamos à disposição para esclarecer dúvidas</span>
        </div>

    </div>
</div>