<div class="container container-fixed-lg bg-white">
    <div class="row">
        <div class="col-12 m-t-20 text-center">
            <h3 style="color:#da5228;">PARABÉNS!</h3>
            <h4>O SEU ANÚNCIO FOI CRIADO COM SUCESSO.</h4>
        </div>
        <div class="col-md-12 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
    </div>
    <div class="mx-auto py-2" style="width: 75%; background-color: lightgray;">

        <p class="mx-5"><b>Falta pouco</b> para seu veículo ser publicado no SeminovosBH.</p>

        <p class="mx-5">Agora ele <b>aguarda a conferência</b> de nossos operadores. Após a conferencia será publicado em <b>até 2 dias úteis</b>.</p>

        <p class="mx-5">Caso seu anúncio não seja publicado, verifique os dados cadastrados e atente a possíveis irregularidades.</p>
    </div>
    <div class="mx-auto py-4 text-center">
        <p style="font-weight: bold;color:#333;">Obrigado por anunciar conosco.</p>
        <p style="color:#acacac; font-size:14px;font-weight: bold;">Equipe SeminovosBH!</p>
    </div>
</div>
