<div class="container">
    <h4 class="text-center">
        PAGAMENTO
    </h4>
    <div class="text-center my-3">
        <small class="align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar seu
            anúncio.
            <br />Campos com * são de preenchimento obrigatório.
        </small>
    </div>
    <div class="row">
        <div class="col-md-5">
            <div class="container-fixed-lg">
                <div class="text-left"><strong>RESUMO DA SUA COMPRA</strong></div>
                <?php foreach ($planos as $plano) { ?>
                <div id="planos<?=$plano['idPlano']?>" class="form-group form-group-default align-items-center row">
                    <div class="col-md-8">
                        <div><strong><?= $plano['nomePlano']=="Grátis"?"Simples":$plano['nomePlano'] ?></strong></div>
                        <div><small>Até a venda</small></div>
                    </div>
                    <div class="col-md-4">
                        <?php if ($this->idStatus == 2) : ?>
                            <?php $valorPagar = (double)($plano['valorPlano'] - $this->valorPlanoAtual) ?>
                            <strong>R$ <?= number_format($valorPagar, 2, ',', '.') ?></strong>
                        <?php else: ?>
                            <strong>R$ <?= number_format($plano['valorPlano'], 2, ',', '.') ?></strong>
                        <?php endif; ?>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="col-md-7 checkout-metodos-container p-l-0">
            <div class="text-left"><strong>FORMA DE PAGAMENTO</strong></div>
            <div class="accordion" id="accordion-payment">
                <div class="card">
                    <div class="card-header" id="cartao-de-credito-label">

                        <button class="h-25 btn btn-link text-left" type="button" data-toggle="collapse"
                            data-target=".cartao-de-credito">
                            <strong>Cartão de crédito</strong><br>
                            <small class="text-capitalize">Ativação imediata</small>
                        </button>


                    </div>
                    <div class="cartao-de-credito collapse show" aria-labelledby="cartao-de-credito-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/cartao-de-credito.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="boleto-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#boleto">
                            <strong>Boleto Bancário</strong><br>
                            <small class="text-capitalize">Ativação em até 3 dias úteis</small>
                        </button>

                    </div>
                    <div id="boleto" class="collapse" aria-labelledby="boleto-label" data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/boleto.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="transferencia-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#transferencia">
                            <strong>Transferencia ou depósito em conta</strong><br>
                            <small class="text-capitalize">Ativação mediante confirmação de depósito</small>
                        </button>
                    </div>
                    <div id="transferencia" class="collapse" aria-labelledby="transferencia-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/transferencia.phtml') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="processando">
                <div class="alert alert-info">
                    <div class="alert-img">
                        <i class="fa fa-circle-o-notch fa-spin fa-fw"></i>
                    </div>
                    <div class="alert-text">
                        Aguarde enquanto estamos processando seu pagamento
                    </div>
                </div>
            </div>
            <div class="error-output">
                <div class="alert alert-danger">
                    <div class="alert-img">
                        <i class="fa fa-exclamation-triangle animated flash" aria-hidden="true"></i>
                    </div>
                    <div class="alert-text error-message"></div>
                </div>
                <br>
                <button type="button" class="btn btn-success pull-right tentar-novamente">Tentar novamente <i
                        class="fa fa-repeat" aria-hidden="true"></i></button>

            </div>
        </div>
    </div>
</div>