<div class="container">
    <h4 class="text-center">
        PAGAMENTO
    </h4>
    <div class="text-center my-3">
        <small class="align-center">Os dados do seu veículo foram cadrastrados com sucesso!
            <br />Agora escolha a melhor forma de pagamento para concluir seu anúncio.
        </small>
    </div>
    <div class="row">
        <div class="col-md-5">
            <div class="container-fixed-lg">
                <div class="text-left"><strong>RESUMO DA SUA COMPRA</strong></div>
                <?php foreach ($planos as $plano) { ?>
                <div id="planos<?=$plano['idPlano']?>" class="form-group form-group-default align-items-center row">
                    <div class="col-md-8">
                        <div><strong><?= $plano['nomePlano']=="Grátis"?"Simples":$plano['nomePlano'] ?></strong></div>
                        <div><small>Até a venda</small></div>
                    </div>
                    <div class="col-md-4">
                        <?php if (($this->idStatus == 2 || $this->idStatus == 9) && $this->idPlano != 4) : ?>
                            <?php $valorPagar = (double)($plano['valorPlano'] - $this->valorPlanoAtual) ?>
                            <strong>R$ <?= number_format($valorPagar, 2, ',', '.') ?></strong>
                        <?php else: ?>
                            <strong>R$ <?= number_format($plano['valorPlano'], 2, ',', '.') ?></strong>
                        <?php endif; ?>
                    </div>
                </div>
                <?php } ?>
            </div>
            <div class="">
                <div class="text-left"><strong class="text-capitalize">Atenção</strong></div>
                <span>
                    Necessário renovar a cada 30 dias, renovação gratuita, exceto veículo 0km
                </span>  
            </div>
        </div>
        <div class="col-md-7 checkout-metodos-container p-l-0">
            <div class="text-left"><strong>FORMA DE PAGAMENTO</strong></div>
            <div class="accordion" id="accordion-payment">
                <div class="card">
                    <div class="card-header" id="cartao-de-credito-label">

                        <button class="h-25 btn btn-link text-left" type="button" data-toggle="collapse"
                            data-target=".cartao-de-credito">
                            <strong>Cartão de crédito</strong><br>
                            <small class="text-capitalize">Ativação imediata</small>
                        </button>


                    </div>
                    <div class="cartao-de-credito collapse show" aria-labelledby="cartao-de-credito-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/cartao-de-credito.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="boleto-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#boleto">
                            <strong>Boleto Bancário</strong><br>
                            <small class="text-capitalize">Ativação em até 3 dias úteis</small>
                        </button>

                    </div>
                    <div id="boleto" class="collapse" aria-labelledby="boleto-label" data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/boleto.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="transferencia-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#transferencia">
                            <div class="d-flex text-left justify-content-start">
                                <strong>
                                    <div>
                                        Transferencia ou 
                                    </div>
                                    <div>
                                        depósito em conta
                                    </div>
                                </strong>
                            </div>
                            <div>
                                <small class="text-capitalize">Ativação mediante confirmação de depósito</small>
                            </div>
                        </button>
                    </div>
                    <div id="transferencia" class="collapse" aria-labelledby="transferencia-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/transferencia.phtml') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="processando">
                <div class="alert alert-info">
                    <div class="alert-img">
                        <i class="fa fa-circle-o-notch fa-spin fa-fw"></i>
                    </div>
                    <div class="alert-text">
                        Aguarde enquanto estamos processando seu pagamento
                    </div>
                </div>
            </div>
            <div class="error-output">
                <div class="alert alert-danger">
                    <div class="alert-img">
                        <i class="fa fa-exclamation-triangle animated flash" aria-hidden="true"></i>
                    </div>
                    <div class="alert-text error-message"></div>
                </div>
                <br>
                <button type="button" class="btn btn-success pull-right tentar-novamente">Tentar novamente <i
                        class="fa fa-repeat" aria-hidden="true"></i></button>
            </div>
        </div>
    </div>
</div>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '408763516364456');
  fbq('track', 'Anunciofinalizado');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=408763516364456&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->