<input type="checkbox" class="d-none flagCertificado" name="flagCertificado" id="">

<div class="modal-sobre-certificado">
    <div class="content">
        <div class="close"><i class="fa fa-times-circle-o" aria-hidden="true"></i></div>
        <div class="topo">
            <h3>O que é o certificado documental?</h3>
        </div>
        <div class="corpo">
            <p>
                É um documento emitido pela empresa OLHO NO CARRO, terceirizada, que faz a busca no banco de dados nacional do Denatran. 
                Esse histórico é emitido através de uma consulta realizado pela placa cadastrada no momento de criar o anúncio. 
                Então deve ser inserida a placa correta do mesmo.
            </p>
            <p>NÃO SE TRATA DE UMA VERIFICAÇÃO ESTRUTURAL.</p>

            <div class="sobre-checktudo">
                <h5>Sobre a CheckTudo : </h5>
                <p><i class="fa fa-circle" aria-hidden="true"></i> O Historicar é a mais completa plataforma de busca a histórico veicular do Brasil.</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> De forma ágil, fácil e segura, o usuário tem acesso a mais de 60 informações sobre um veículo pesquisado.</p>
            </div>
            <div class="informacoes-consulta">
                <h5>Quais as informações que possuem neste certificado?</h5>
                <p>Descritivo do pacote:</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Base Nacional</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Base Estadual</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Indício de Sinistro</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Oferta em Leilão</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Risco de Recusa em Comercialização</p>
                <p><i class="fa fa-circle" aria-hidden="true"></i> Possui risco em aceitação de Seguros</p>
                <p class="mt-2">IMPORTANTE</p>
                <p>
                    Algumas informações podem não estar disponíveis no momento da consulta devido a instabilidades da base de dados dos prestadores de serviço,
                    mas serão reconsultadas (sem custo adicional) e enviadas assim que possível ao usuário.
                </p>
            </div>
            <div class="como-relatorio">
                <h5>Segue exemplo do laudo que será adquirido:</h5>
                <div class="img">
                    <img class="img-fluid" src="/img/exemplo/certficado_exemplo.png" alt="" srcset=""> PRINT
                </div>
            </div>
            <p>Não nos responsabilizamos por informações errôneas enviadas, tanto do usuário quanto da empresa OLHO NO CARRO.</p>
        </div>
    </div>
</div>

<div class="container">
    <h4 class="text-center">
        PAGAMENTO
    </h4>
    <div class="text-center my-3">
        <small class="align-center">Os dados do seu veículo foram cadrastrados com sucesso!
            <br />Agora escolha a melhor forma de pagamento para concluir seu anúncio.
        </small>
    </div>
    <div class="row">
        <div class="col-md-5 d-flex flex-wrap align-content-between">
            <div class="w-100 resumo-compra">
                <div class="w-100">
                    <div class="titulo"><strong>RESUMO DA SUA COMPRA</strong></div>
                    <?php foreach ($planos as $plano) { ?>
                    <div id="planos<?=$plano['idPlano']?>" class="plano card-style" data-valor-plano="<?= number_format($plano['valorPlano'], 2, ',', '.') ?>">
                        <div class="nome-plano-ate-venda">
                            <div class="nome-plano"><strong><?= $plano['nomePlano']=="Grátis"?"Simples":$plano['nomePlano'] ?></strong></div>
                            <div class="ate-venda"><small>Até a venda</small></div>
                        </div>
                        <div class="valor-plano">
                            <?php if (($this->idStatus == 2 || $this->idStatus == 9) && $this->idPlano != 4) : ?>
                                <?php $valorPagar = (double)($plano['valorPlano'] - $this->valorPlanoAtual) ?>
                                <strong>R$ <?= number_format($valorPagar, 2, ',', '.') ?></strong>
                            <?php else: ?>
                                <strong>R$ <?= number_format($plano['valorPlano'], 2, ',', '.') ?></strong>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <div class="w-100 renovacao">
                    <div class="text-left"><strong class="text-capitalize">Atenção</strong></div>
                    <span>
                        Necessário renovar a cada 30 dias, renovação gratuita, exceto veículo 0km
                    </span>  
                </div>
                <div class="w-100 certificado card-style">
                    <div class="titulo">
                        Certificado
                    </div>
                    <div class="valor">
                        <b>
                            R$ 24,90
                        </b>
                    </div>
                </div>
                <div class="w-100 valor-total">
                    <div class="titulo">
                        Total
                    </div>
                    <div class="valor">
                        <b>R$ </b>
                        <b data-valor-total="">0,00</b>
                    </div>
                </div>
            </div>
           <div class="w-100 handle-certificado">
                <div>
                    <span class="bold">VALOR PROMOCIONAL DE LANÇAMENTO</span>
                </div>
                <div class="titulo titulo-add">
                    <span>Adquirira o certificado documental junto com seu plano.</span>
                </div>
                <div class="titulo titulo-remove">
                    <span>Remover certificado documental</span>
                </div>

                <div class="btn-control-certificado">
                    <a class="add-certificado" href="">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        <span> R$ 24,90</span>
                    </a>
                    <a class="remove-certificado" href="">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                        <span>remover</span>
                    </a>
                </div>
                <div class="saiba-mais">
                    <a href="">
                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                        <span>SAIBA MAIS</span>
                    </a>

                </div>
            </div>
        </div>
        <div class="col-md-7 checkout-metodos-container pt-3 pl-2 pt-md-0 pl-md-0">
            <div class="text-left"><strong>FORMA DE PAGAMENTO</strong></div>
            <div class="accordion" id="accordion-payment">
                <div class="card">
                    <div class="card-header" id="cartao-de-credito-label">

                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target=".cartao-de-credito">
                            <strong>Cartão de crédito</strong><br>
                            <small class="text-capitalize">Ativação imediata</small>
                        </button>


                    </div>
                    <div class="cartao-de-credito collapse" aria-labelledby="cartao-de-credito-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/cartao-de-credito.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="boleto-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#boleto">
                            <strong>Boleto Bancário</strong><br>
                            <small class="text-capitalize">Ativação em até 3 dias úteis</small>
                        </button>

                    </div>
                    <div id="boleto" class="collapse" aria-labelledby="boleto-label" data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/boleto.phtml') ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="transferencia-label">
                        <button class="h-25 btn btn-link text-left collapsed" type="button" data-toggle="collapse"
                            data-target="#transferencia">
                            <div class="d-flex text-left justify-content-start">
                                <strong>
                                    <div>
                                        Transferencia ou 
                                    </div>
                                    <div>
                                        depósito em conta
                                    </div>
                                </strong>
                            </div>
                            <div>
                                <small class="text-capitalize">Ativação mediante confirmação de depósito</small>
                            </div>
                        </button>
                    </div>
                    <div id="transferencia" class="collapse" aria-labelledby="transferencia-label"
                        data-parent="#accordion-payment">
                        <div class="card-body">
                            <?= $this->partial('partials/transferencia.phtml') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="processando">
                <div class="alert alert-info">
                    <div class="alert-img">
                        <i class="fa fa-circle-o-notch fa-spin fa-fw"></i>
                    </div>
                    <div class="alert-text">
                        Aguarde enquanto estamos processando seu pagamento
                    </div>
                </div>
            </div>
            <div class="error-output">
                <div class="alert alert-danger">
                    <div class="alert-img">
                        <i class="fa fa-exclamation-triangle animated flash" aria-hidden="true"></i>
                    </div>
                    <div class="alert-text error-message"></div>
                </div>
                <br>
                <button type="button" class="btn btn-success pull-right tentar-novamente">Tentar novamente <i
                        class="fa fa-repeat" aria-hidden="true"></i></button>
            </div>
        </div>
    </div>
</div>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '408763516364456');
  fbq('track', 'Anunciofinalizado');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=408763516364456&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->