<div class="container container-fixed-lg bg-white text-center">

    <div class="col-12 m-t-20">
        <h5>Seu código PIX está disponível para pagamento.</h5>
        <div>
            <b>Copie</b> ou <b>escaneie</b> o código <b>PIX</b> abaixo e finalize o pagamento no seu <b>aplicativo de pagamento</b>.
        </div>
    </div>
    <div class="col-12 mt-2">

        <div class="pix-timer ">
            O código expira em:<br>
            <span class="timer h2">--:--</span>
        </div>
    </div>
    <div class="col-12 offset-md-2 col-md-8 mb-2">
        <div class="qrcode-container">
            <img class="qrcode-img" style="width:100%; height:auto; max-width: 400px;" src="https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl=<?php echo trim((string) $_GET['code']); ?>"/>
        </div>
        <div class="col-12 m-2">
            <p id="text-code" style="font-size: 15px; font-weight: bold; overflow: scroll; padding: 15px 0; white-space: nowrap;">
                <?php echo trim((string) $_GET['code']); ?>
            </p>
        </div>
        <div class="col-12 align-center">
            <button id="copy" class="btn btn-laranja text-white btn-lg btn-block">
                Copiar código <i class="fa fa-clone" aria-hidden="true"></i>
            </button>
        </div>
        <div class="col-12 m-t-20 align-center">
            <p>Pagamento processado através da <br><b>Zoop Tecnologia e Meios de Pagamentos Ltda.</b></p>
        </div>
    </div>
    <div class="mx-auto py-2 mt-2">
        <p class="mx-5 my-1">Após confirmação automática, seu anúncio será ativado na hora!</p>
    </div>
    <div class="mx-auto py-4">
            <p style="font-weight: bold;color:#333;">Obrigado por anunciar conosco.</p>
            <p style="color:#acacac; font-size:14px;font-weight: bold;">Equipe SeminovosBH!</p>
    </div>
</div>
<script>
    dataLayer.push({'codTransacao': "<?=$_GET['idPagamento']?>"});
function selectText(){
    if(window.getSelection) {
        var range = document.createRange();
        range.selectNode(document.getElementById('text-code'));
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
    }
}
var btn = document.querySelector('#copy');
btn.addEventListener('click', function(e) {
  try{
    navigator.clipboard.writeText('<?= trim((string) $_GET['code']) ?>');
  }catch(err){
    newrelic && newrelic.noticeError(err);
  }
  //alert("Código copiado");
  alerta('success', 'Seu código PIX foi copiado.', 'Atenção!', 5000);
  try{
    document.execCommand('copy');
  }catch(err){
    
    newrelic && newrelic.noticeError(err);
  }
  selectText();

});

function alerta (type, text, title, time) {
        if (title === null || title === undefined) {
            title = '';
        }
        time = time || this.options.time;
        var count = Math.floor(time / 1000);
        var spanCount = $('<span class="text-count"></span>').text('(' + count + ')');
        var close = $('<button class="btn btn-primary" data-dismiss="modal">')
            .html('<span class="text-close">Fechar</span> ')
            .append(spanCount);

        var intervalID = setInterval(function () {
            spanCount.text('(' + count + ')');
            count--;
            if (count < 0) {
                clearInterval(intervalID);
            }

        }, 1000);

        setTimeout(function () {
            modal.modal('hide');
        }, time);

        var modal = $.jsBsModal({
            contents: {
                'close': '',
                'modal-title': title,
                'modal-body': text,
                'modal-footer': [
                    close
                ],
            }
        }).on('hidden.bs.modal', function () {
            modal.modal('dispose').remove();
        });

        modal.find('.modal-content').addClass('alert alert-' + type);

        return modal;
    }
</script>