<div class="container container-fixed-lg bg-white">
    <div class="row">
        <div class="col-12 m-t-20 text-center">
            <h3 style="color:#da5228;">Aguardando Pagamento.</h3>
        </div>
        <div class="col-md-12 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
    </div>
    <div class="col-12 m-t-20 text-center">
        <h4>Seu código PIX está disponível para pagamento.</h4>
    </div>
    <div class="col-12 offset-md-2 col-md-8 text-center pb-3 mb-2 border border-danger">
        <div class="col-12 col-md-12 m-t-20 text-center text-pix" style="font-size: 15px; font-weight: bold; word-wrap: break-word;">
            <?php echo trim($_GET['code']); ?>
        </div>
        <div class="col-12 m-t-20 text-center align-center">
            <button id="copy"
                style="
                font-family: 'PT Sans', sans-serif;
                margin-top: 16px;
                font-size: 16px;
                text-decoration: none;
                color:white;
                padding-top:2.4%;
                padding-bottom:2.4%;
                background-color: #ED9902;
                border-radius: 4px;
                /*display: block;*/
                width: 60%;
                font-weight: bold;">
                Copiar
            </button>
        </div>
        <div class="col-12 m-t-20 text-center align-center">
            <p style="font-weight: bold;color:red;">Pagamento processado pela empresa Zoop Tecnologia e Meios de Pagamentos Ltda.</p>
        </div>
    </div>
    <div class="mx-auto py-2 mt-2" style="width: 75%; background-color: lightgray;">
        <p class="mx-5 my-1">Após confirmação do pagamento no prazo de 10 minutos o anúncio será ativado.</p>
    </div>
    <div class="mx-auto py-4 text-center">
            <p style="font-weight: bold;color:#333;">Obrigado por anunciar conosco.</p>
            <p style="color:#acacac; font-size:14px;font-weight: bold;">Equipe SeminovosBH!</p>
    </div>
</div>
<script>
let btn = document.querySelector('#copy');
btn.addEventListener('click', function(e) {
  let textArea = document.querySelector('.text-pix').innerText;
  console.log(textArea);
  navigator.clipboard.writeText(textArea);
  //alert("Código copiado");
  alerta('success', 'Seu código PIX foi copiado.', 'Atenção!', 5000);
  document.execCommand('copy');
  
});

function alerta (type, text, title, time) {
        if (title === null || title === undefined) {
            title = '';
        }
        time = time || this.options.time;
        var count = Math.floor(time / 1000);
        var spanCount = $('<span class="text-count"></span>').text('(' + count + ')');
        var close = $('<button class="btn btn-primary" data-dismiss="modal">')
            .html('<span class="text-close">Fechar</span> ')
            .append(spanCount);

        var intervalID = setInterval(function () {
            spanCount.text('(' + count + ')');
            count--;
            if (count < 0) {
                clearInterval(intervalID);
            }

        }, 1000);

        setTimeout(function () {
            modal.modal('hide');
        }, time);

        var modal = $.jsBsModal({
            contents: {
                'close': '',
                'modal-title': title,
                'modal-body': text,
                'modal-footer': [
                    close
                ],
            }
        }).on('hidden.bs.modal', function () {
            modal.modal('dispose').remove();
        });

        modal.find('.modal-content').addClass('alert alert-' + type);

        return modal;
    }
</script>