<?php

/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */
/** @psalm-scope-this \AreaRestrita\View\Helper\AutocompleteClass */

use AreaRestrita\View\Helper\Data;
use SnBH\Common\Helper\StringFuncs;

$formatDate = new Data();
$urls = [
    'editarAnuncio' => $this->url('criar-anuncio', [
        'tipo' => strtolower((string) $veiculo['tipo']),
        'idVeiculo' => $veiculo['idVeiculo'],
    ]),
];
$nome = $this->userInfo('responsavelNome') ?? $this->userInfo('nomeFantasia') ?? "Não informado";

?>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script>
    <?= file_get_contents(__DIR__ . '/highcharts-lang.js') ?>
</script>
<div class="container-fluid painel-anuncio">
    <div class="row step step-titulo">
        <div class="col-12 row mb-3 bg-white p-0 justify-content-center plano-<?= $veiculo['idPlano'] ?> status-<?= $veiculo['idStatus'] ?> veiculo" data-id-veiculo="<?= $veiculo['idVeiculo'] ?>" data-veiculo-placa="<?= $veiculo['placa'] ?>" data-veiculo-marca="<?= $veiculo['marca'] ?>" data-veiculo-modelo="<?= $veiculo['modelo'] ?>" <?= $veiculo['idStatus'] == 3 || $veiculo['idStatus'] == 10 ? "data-veiculo-finalizar" : "" ?>>
            <div class="col-12 col-md-4 col-lg-2 d-flex pt-3 justify-content-center">
                <a href="/meus-veiculos/<?= $veiculo['idVeiculo'] ?>">
                    <img class="img-fluid" src="<?= $veiculo['imagem'] ?>" alt="" />
                </a>
            </div>
            <div class="col-12 col-md-8 col-lg-7">
                <div class="row justify-content-between m-t-10 active px-2 py-2">
                    <div class="justify-content-center row col-12 h-auto justify-content-md-between border-bottom-c border-s-2 border-<?= $veiculo['idPlano'] ?>-20 pb-2">
                        <p class="col-12 col-md-6 m-0 p-0 text-uppercase h4 text-cinza-escuro d-flex align-items-center">
                            <span class="mr-2">
                                <?= $veiculo['marca'] . ' ' . $veiculo['modelo'] . ' ' . $veiculo['caracteristica']; ?>
                            </span>
                            <?php if ($veiculo['codFipe'] == 0 || empty($veiculo['codFipe'])) : ?>
                                <small class="small d-none d-md-block">
                                    <?= $veiculo['motor'] . ' ' ?>
                                    <?= !empty($veiculo['valvula']) && $veiculo['valvula'] != '0' ? $veiculo['valvula'] . 'V' : '' ?>
                                </small>
                            <?php endif; ?>
                        </p>
                        <h4 class="d-flex justify-content-start justify-content-md-end col-12 col-md-6 m-0 p-0 h4 text-cinza-escuro">
                            R$ <?= $veiculo['valorFormatado'] ?>
                        </h4>
                    </div>
                    <div class="col-12 col-lg-6 mt-2">
                        <ul class="h-auto">
                            <li>
                                Visualizações:
                                <span class="text-uppercase"><?= $veiculo['acessos'] ?></span>
                            </li>
                            <li>
                                Placa:
                                <span class="text-uppercase"><?= $veiculo['placa'] ?></span>
                            </li>
                            <li>
                                Cadastrado:
                                <?php
                                if ($veiculo['dataCadastro'] !== '') {
                                    echo $formatDate->converterDataBR($veiculo['dataCadastro']);
                                } else {
                                    echo '-';
                                }

                                ?>
                            </li>
                            <?php if ((int) $this->userInfo('tipoCadastro') == 2) : ?>
                                <li>
                                    Renovado:
                                    <?php
                                    if ($veiculo['dataRenovacao'] !== '') {
                                        echo $formatDate->converterDataBR($veiculo['dataRenovacao']);
                                    } else {
                                        echo '-';
                                    }

                                    ?>
                                </li>
                            <?php endif; ?>
                            <li>
                                Kilometragem:
                                <?= $veiculo['kilometragemFormatada'] ?>
                            </li>
                            <li>
                                Código:
                                <?= $veiculo['idVeiculo'] ?>
                            </li>
                        </ul>

                        <div class="btn-group">
                            <?php if ($veiculo["botoes"]["editar_dados"]) { ?>
                                <a href="<?= $urls['editarAnuncio'] ?>" class="btn bg-cinza text-white icon-2 btn-acao-editar-dados" title="Editar Anúncio" target="_blank">
                                    <i class=" fa fa-pencil"></i>
                                </a>
                            <?php } ?>

                            <?php if ($veiculo["botoes"]["editar_fotos"]) { ?>
                                <?php
                                $editarFotosUrl = $urls['editarAnuncio'];
                                if ($veiculo['idStatus'] == SnBH\ApiModel\Model\VeiculosStatus::STATUS_ATIVO || $veiculo['idStatus'] == SnBH\ApiModel\Model\VeiculosStatus::STATUS_FOTOS_ALTERADAS) {
                                    $editarFotosUrl .= '?editar=fotos';
                                }
                                $editarFotosUrl .= '#fotos';

                                ?>
                                <a href="<?= $editarFotosUrl ?>" class="btn bg-cinza text-white icon-2 btn-acao-editar-fotos" title="Editar Fotos" target="_blank">
                                    <i class=" fa fa-camera"></i>
                                </a>
                            <?php } ?>
                            <?php if ($veiculo["botoes"]["vendido"] ?? false) { ?>
                                <a href="#" class="btn-acao-vendido ml-4 vendido" data-confirm data-confirm-url="/meus-veiculos/vendido/<?= $veiculo['idVeiculo'] ?>" title="Marcar como vendido">
                                    <button class="btn btn-sm btn-complete ml-2 ">Vendido</button>
                                </a>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-3 mt-2  p-0 m-0 row justify-content-center">
                        <!-- <div class="col-6 col-lg-12 mt-1 padding-15  bg-master-lightest">
                                    <div class="pl-3 bold no-margin">
                                        <?php //= $veiculo['cliques'] ? : 0
                                        ?>
                                     cliques
                                    </div>
                                </div>
                                <div class="col-6 col-lg-12 mt-1 padding-15  bg-master-lightest">
                                    <div class="pl-3 bold no-margin">
                                        <?php //= $veiculo['acessos'] ? : 0
                                        ?>
                                       acessos
                                    </div>
                                </div> -->
                        <?php if ($veiculo['combinarValor'] == 1) : ?>
                            <div class="col-12 col-lg-12 ">
                                <div class="bg-master-lightest  mt-1 padding-15">
                                    <!--<a href="/meus-veiculos/propostas/<?= $veiculo['idVeiculo'] ?>" class="text-dark">-->
                                    <div class="row d-flex justify-content-between pl-3">
                                        <div class="bold no-margin d-flex align-items-center link-danger">
                                            <span class="fa fa-circle text-warning fs-11 mr-1"></span>
                                            Valor a Combinar
                                        </div>
                                    </div>
                                    <!--</a>-->
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="col-12 col-lg-12 ">
                            <div class="bg-master-lightest  mt-1 padding-15">
                                <!--<a href="/meus-veiculos/propostas/<?= $veiculo['idVeiculo'] ?>" class="text-dark">
                                    <div class="row d-flex justify-content-between pl-3">
                                        <div class="bold no-margin d-flex align-items-center link-danger">
                                            <!-- <span class="fa fa-envelope fs-16 mr-1"></span> -- >
                                            Propostas: <?= $veiculo['qdtPropostas'] ?? 0 ?>
                                            <?php

                                            /** @todo
                                             *  Trazer o numero de propostas
                                             *  Trazer bolinha verde quando há nova proposta
                                             */

                                            ?>
                                        </div>
                                        <a href="/meus-veiculos/propostas/<?= $veiculo['idVeiculo'] ?>">
                                            <span class=" label bg-verde text-white p-t-3 p-b-3 inline fs-12 mr-2">
                                                Ver
                                            </span>
                                        </a>
                                    </div>
                                </a>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-12 col-lg-3">
                <div data-index="0" class="company-stat-box m-t-10 px-4 py-3 bg-master-lightest">
                    <div class="d-flex justify-content-between align-items-center">
                        <p class="pull-left d-flex text-uppercase bold align-items-center mb-0">
                            <?php if (
                                $veiculo["idStatus"] != SnBH\ApiModel\Model\VeiculosStatus::STATUS_CADASTRANDO
                                && $veiculo["idStatus"] != SnBH\ApiModel\Model\VeiculosStatus::STATUS_AGUARDANDO_PAGAMENTO
                            ) { ?>
                                <span class="fa fa-circle text-p-<?= $veiculo['idPlano'] ?> fs-11 mr-1"></span>
                                <?= $veiculo['nomePlano'] ?>
                            <?php } ?>
                        </p>

                    </div>
                </div>

                <div class="pb-2">
                    <div data-index="0" class="company-stat-box m-t-10 bg-master-lightest active px-4 pt-3 h-100 ">
                        <div class="d-flex justify-content-between">
                            <p class="company-name pull-left text-uppercase bold no-margin d-flex align-items-center">
                                <span class="fa fa-circle text-s-<?= $veiculo['idStatus'] ?> fs-11 mr-1"></span>
                                <?= $veiculo['tituloStatus'] ?>
                            </p>
                        </div>
                        <div class=" d-flex mt-1">
                            <small class="hint-text"><?= $veiculo["frase"] ?></small>
                        </div>
                        <?php if ($veiculo['idStatus'] == 2 && (int) $this->userInfo('tipoCadastro') == 2) : ?>
                            <div class="d-flex mt-1">
                                <small class="hint-text mt-1">
                                    <?php if ($veiculo["intervaloData"] == 0) { ?>
                                        Expira Hoje
                                    <?php } elseif ($veiculo["intervaloData"] >= 1) { ?>
                                        Expira em <?= $veiculo["intervaloData"] ?> dias
                                    <?php } else { ?>
                                        Expirado em <?= $veiculo["dataExpiracao"] ?>
                                    <?php } ?>
                                </small>
                            </div>
                        <?php endif; ?>
                        <div class="justify-content-end d-flex m-t-15 pb-2">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row step step-resumo">

        <div class="col-12 col-md-12 d-flex align-items-center justify-content-center justify-content-md-end pr-md-0">
            <!-- <div class="form-group mt-2">
                <div class='input-group date'>
                    <input type='text' class="form-control input date-timer-picker" />
                    <span class="input-group-addon text-black">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </span>
                </div>
            </div>
            <a href="#" class="btn btn-laranja">ok</a> -->
        </div>
        <div class="col-12 mb-4">
            <form method="get" class="form-inline filtro-date">
                <span class="px-2">Filtra dados por data: </span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">De:</span>
                    </div>
                    <label>
                        <input type="date" name="date-start" class="form-control" value="<?= $_GET['date-start'] ?? '' ?>" max="<?= date('Y-m-d') ?>"/>
                    </label>
                    <div class="input-group-prepend">
                        <span class="input-group-text">Até:</span>
                    </div>
                    <label>
                        <input type="date" name="date-end"   class="form-control" value="<?= $_GET['date-end'] ?? '' ?>" max="<?= date('Y-m-d') ?>" value="<?= date('Y-m-d') ?>" />
                    </label>
                </div>
                <label>
                    <button type="submit" class="btn btn-laranja">Filtrar</button>
                </label>
            </form>
        </div>
        <div class="col-6 col-md-4 card">
            <div class="card-header text-center">Impressão no resultado de busca resultados de busca</div>
            <div class="card-body"><?= StringFuncs::nF($this->metricas['impressao']['total']) ?></div>
        </div>
        <div class="col-6 col-sm col-md-4 card">
            <div class="card-header text-center">Vizualizações dos dados do veículo</div>
            <div class="card-body"><?= $this->metricas['acesso']['total'] ?></div>
        </div>

        <div class="col-6 col-md-4 card">
            <div class="card-header text-center">Cliques em ver telefone</div>
            <div class="card-body"><?= $this->contato ?> </div>
        </div>
    </div>

    <div class="graficos">
        <div class="row">
            <div class="col-12">
                <div id="container-highcharts"></div>
                <script>
                    var series = <?php
                                    // ob_clean();
                                    $seriesOptions = [
                                        'acesso' => [
                                            'name' => 'Clique',
                                            'yAxis' => 1,
                                            'data' => [],
                                        ],
                                        'impressao' => [
                                            'name' => 'Impressão',
                                            'yAxis' => 0,
                                            'data' => [],
                                        ],
                                    ];
                                    $series = [];

                                    //foreach ($this->metricas as $metrica => $data) {
                                    foreach ($seriesOptions as $metricaKey => $serieOptions) {
                                        $sum = 0;
                                        foreach ($this->metricas[$metricaKey]['data'] as $key => $value) {
                                            $series[$metricaKey]  ??= $serieOptions;
                                            $sum += $value;
                                            $series[$metricaKey]['data'][] = [
                                                'x' => $this->dateHelper()->dateToJsTimestamp($key),
                                                'y' => $sum,
                                            ];
                                        }
                                    }
                                    echo json_encode(array_values($series));
                                    ?>;
                    Highcharts.chart('container-highcharts', {
                        chart: {
                            type: 'area'
                        },
                        title: {
                            text: 'Cliques x Impressões'
                        },
                        /*subtitle: {
                            text: 'Source: ' +
                                '<a href="https://en.wikipedia.org/wiki/List_of_cities_by_average_temperature" ' +
                                'target="_blank">Wikipedia.com</a>'
                        },
                        /**/
                        xAxis: {
                            type: 'datetime',
                            type: "datetime",

                            /*labels: {
                                formatter: function() {
                                    console.log(this.value)
                                    return Highcharts.dateFormat('%e/%b', this.value);
                                }
                            }*/
                            //categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                        },
                        yAxis: {

                            title: {
                                text: ''
                            }
                        },
                        yAxis: [{
                                title: {
                                    text: 'Impressoes'
                                },
                                opposite: true,
                                allowDecimals: false,
                            },
                            {
                                title: {
                                    text: 'Cliques'
                                },
                                allowDecimals: false,
                            }
                        ],
                        tooltip: {
                            crosshairs: true,
                            shared: true
                        },
                        plotOptions: {
                            line: {
                                dataLabels: {
                                    enabled: true
                                },
                            },
                            series: {
                                animation: false
                            }
                        },
                        series: series,
                    });
                </script>
            </div>
        </div>

    </div>
</div>
