<?php
    $formatDate = new \AreaRestrita\View\Helper\Data();
?>
<div class="container-fluid painel-anuncio">
    <div class="row step step-titulo">
        <div class="col-9 col-md-9">
            <div class="title">
                <h1><?= $veiculo['marca'] ?> <?= $veiculo['modelo'] ?>
                    <?= $veiculo['anoFabricacao'] ?>/<?= $veiculo['anoModelo'] ?>
                </h1>
            </div>
            <div class="details">
                <div>
                    <span>
                        Placa <?= $veiculo['placa'] ?>
                    </span>
                </div>
                <div>
                    <b>Cadastrado desde:</b>
                    <span>
                        <?= $formatDate->converterDataBR($veiculo['dataCadastro']) ?>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-3 col-md-3">
            <div class="box">
                STATUS: <?= $veiculo['tituloStatus'] ?>
            </div>
            <div class="box">
                PLANO: <?= $veiculo['nomePlano'] ?>
            </div>
        </div>
    </div>
    <div class="row step step-resumo">
        <div class="col-12 col-md-6 d-none d-md-block">
            <div class="title">
                <span>
                    Resumo
                </span>
            </div>
        </div>
        <div class="col-12 col-md-6 d-flex align-items-center justify-content-center justify-content-md-end pr-md-0">
            <!-- <div class="form-group mt-2">
                <div class='input-group date'>
                    <input type='text' class="form-control input date-timer-picker" />
                    <span class="input-group-addon text-black">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </span>
                </div>
            </div>
            <a href="#" class="btn btn-laranja">ok</a> -->
            Janeiro de 2020
        </div>
        <div class="col-6 col-md-4 card">
            <div class="card-header">Cliques</div>
            <div class="card-body"><?= $this->cliques ?></div>
        </div>
        <div class="col-6 col-md-4 card">
            <div class="card-header">Impressões</div>
            <div class="card-body"><?= $this->impressoes ?></div>
        </div>
        <div class="col-6 col-md-4 card">
            <div class="card-header">Cliques em ver telefone</div>
            <div class="card-body"><?= $this->contato ?> </div>
        </div>
    </div>
    <div class="row step step-grafico-clique">
        <div class="col-12">
            <h5>Cliques</h5>
            <div class="grafico">
                <canvas class="grafacesso"></canvas>
            </div>
        </div>
    </div>
    <div class="row step step-grafico-proposta">
        <div class="col-12">
            <h5>Impressões</h5>
            <div class="grafico">
                <canvas class="grafimpressao"></canvas>
            </div>
        </div>
    </div>
    <div class="row step step-grafico-telefone">
        <div class="col-12">
            <h5>Cliques em ver telefone</h5>
            <div class="grafico">
                <canvas class="grafcontato"></canvas>
            </div>
        </div>
    </div>
</div>