<?php

/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */

use AreaRestrita\View\Helper\Data;
use SnBH\Common\Helper\StringFuncs;

if ($this->userInfo('tipoCadastro') == 1) {
    $arrayPlanos = [
        1 => ['nitro', 'Nitro', '12', 'alta', '', '', 'nitro-value', $this->qtdAnuncios()->totalNitro, $this->qtdAnuncios()->totalNitroPublicados],
        2 => ['turbo', 'Turbo', '09', 'média', '', '', 'turbo-value', $this->qtdAnuncios()->totalTurbo, $this->qtdAnuncios()->totalTurboPublicados],
        3 => ['basico', 'Básico', '06', 'baixa', '', '', 'basic-value', $this->qtdAnuncios()->totalBasico, $this->qtdAnuncios()->totalBasicoPublicado],
    ];
} elseif ($this->userInfo('tipoCadastro') == 2) {
    $arrayPlanos = [
        1 => ['nitro-home', 'Nitro Home', '12', 'máxima', '', 'R$ 49,90', 'nitro-home-value', $this->qtdAnuncios()->totalNitroHome, $this->qtdAnuncios()->totalNitroHomePublicados],
        2 => ['nitro', 'Nitro', '12', 'alta', '', 'R$ 39,90', 'nitro-value', $this->qtdAnuncios()->totalNitro, $this->qtdAnuncios()->totalNitroPublicados],
        3 => ['turbo', 'Turbo', '09', 'média', '', 'R$ 29,90', 'turbo-value', $this->qtdAnuncios()->totalTurbo, $this->qtdAnuncios()->totalTurboPublicados],
        4 => ['basico', 'Básico', '06', 'baixa', '', 'R$ 14,90', 'basic-value', $this->qtdAnuncios()->totalBasico, $this->qtdAnuncios()->totalBasicoPublicado],
        5 => ['simples', 'Simples', '03', 'mínima', '', 'Grátis', 'simple-value', $this->qtdAnuncios()->totalGratuito, $this->qtdAnuncios()->totalGratuitoPublicado],
    ];
}

$hoje = new DateTime();
$formatDate = new Data();
$arrowUp = '<i class="fa fa-arrow-up text-warning"></i>';
$arrowDown = '<i class="fa fa-arrow-down text-success"></i>';
$veiculos = $this->veiculos['data'];

usort($veiculos, fn ($a, $b) => $a['prioridadePlano'] <=> $b['prioridadePlano']);


?>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script>
    <?= file_get_contents(__DIR__ . '/highcharts-lang.js') ?>
</script>

<div class="container-fluid painel-revenda">
    <div class="row step step-geral justify-content-between">
        <?php

        echo $this->partial('partials/card.phtml', [
            'header' => 'PLANO',
            'textA' =>
            "Total anúncios<br>
                <h2 class=\"text-white\">" . $this->qtdAnuncios()->totalAnuncios . "</h2>",
            'textB' => "<span class=\"text-white\">R$ " . (StringFuncs::nF($this->valorPlanoRevenda, 2)) . "</span>",
        ]);

        echo $this->partial('partials/card.phtml', [
            'header' => 'QUANTIDADE BÁSICOS',
            'textA' =>
            "Possui
                <div class=\"text-white h3\">{$this->qtdAnuncios()->totalBasico}</div>",
            'textB' =>
            "Faltam
                    <div class=\"text-white h3\">" . ($this->qtdAnuncios()->totalBasico - $this->qtdAnuncios()->totalBasicoPublicado) . "</div>",
        ]);

        echo $this->partial('partials/card.phtml', [
            'header' => 'QUANTIDADE TURBO',
            'textA' =>
            "Possui
                <div class=\"text-white h3\">" . $this->qtdAnuncios()->totalTurbo . "</div>",
            'textB' =>
            "Faltam
                <div class=\"text-white h3\">" . ($this->qtdAnuncios()->totalTurbo - $this->qtdAnuncios()->totalTurboPublicados) . "</div>",
        ]);

        echo $this->partial('partials/card.phtml', [
            'header' => 'QUANTIDADE NITRO',
            'textA' =>
            "Possui
                <div class=\"text-white h3\">" . $this->qtdAnuncios()->totalNitro . "</div>",
            'textB' =>
            "Faltam
                <div class=\"text-white h3\">" . ($this->qtdAnuncios()->totalNitro - $this->qtdAnuncios()->totalNitroPublicados) . "</div>",
        ]);

        echo $this->partial('partials/card.phtml', [
            'header' => 'VEÍCULOS ATIVOS',
            'textA' =>
            "<h1 class=\"col-12 text-white\">" . $this->totalVeiculosAtivos . "</h1>",
            'textB' => false,
        ]);
        ?>
    </div>

    <div class="row">
        <div class="col-12">
            <?= $this->partial('partials/graficos/metricas-totais.phtml', [
                'veiculos' => $veiculos,
                'metricasPorData' => $metricasPorData
            ]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <?= $this->partial('partials/graficos/mais-acessados.phtml', [
                'maisAcessados' => $maisAcessados,
            ]) ?>
            <br>
            <div class="d-none">
                <figure class="highcharts-figure">
                    <div id="container"></div>
                </figure>

                <script>
                    (function() {
                        var data = {
                            "Fiat": [{
                                "x": "2024-02-04",
                                "y": 5244
                            }, {
                                "x": "2024-02-03",
                                "y": 4819
                            }, {
                                "x": "2024-02-02",
                                "y": 5501
                            }, {
                                "x": "2024-02-01",
                                "y": 5990
                            }, {
                                "x": "2024-01-31",
                                "y": 6310
                            }, {
                                "x": "2024-01-30",
                                "y": 6412
                            }, {
                                "x": "2024-01-29",
                                "y": 6684
                            }, {
                                "x": "2024-01-28",
                                "y": 5538
                            }, {
                                "x": "2024-01-27",
                                "y": 5478
                            }],
                            "Volkswagen": [{
                                "x": "2024-02-04",
                                "y": 4064
                            }, {
                                "x": "2024-02-03",
                                "y": 3813
                            }, {
                                "x": "2024-02-02",
                                "y": 4279
                            }, {
                                "x": "2024-02-01",
                                "y": 4417
                            }, {
                                "x": "2024-01-31",
                                "y": 4817
                            }, {
                                "x": "2024-01-30",
                                "y": 5164
                            }, {
                                "x": "2024-01-29",
                                "y": 5261
                            }, {
                                "x": "2024-01-28",
                                "y": 4500
                            }, {
                                "x": "2024-01-27",
                                "y": 4262
                            }],
                            "Chevrolet": [{
                                "x": "2024-02-04",
                                "y": 3542
                            }, {
                                "x": "2024-02-03",
                                "y": 3265
                            }, {
                                "x": "2024-02-02",
                                "y": 3773
                            }, {
                                "x": "2024-02-01",
                                "y": 3886
                            }, {
                                "x": "2024-01-31",
                                "y": 4103
                            }, {
                                "x": "2024-01-30",
                                "y": 4253
                            }, {
                                "x": "2024-01-29",
                                "y": 4271
                            }, {
                                "x": "2024-01-28",
                                "y": 3877
                            }, {
                                "x": "2024-01-27",
                                "y": 3717
                            }],
                            "Honda": [{
                                "x": "2024-02-04",
                                "y": 2904
                            }, {
                                "x": "2024-02-03",
                                "y": 2738
                            }, {
                                "x": "2024-02-02",
                                "y": 3030
                            }, {
                                "x": "2024-02-01",
                                "y": 3073
                            }, {
                                "x": "2024-01-31",
                                "y": 3419
                            }, {
                                "x": "2024-01-30",
                                "y": 3406
                            }, {
                                "x": "2024-01-29",
                                "y": 3569
                            }, {
                                "x": "2024-01-28",
                                "y": 3130
                            }, {
                                "x": "2024-01-27",
                                "y": 3033
                            }],
                            "Toyota": [{
                                "x": "2024-02-04",
                                "y": 2342
                            }, {
                                "x": "2024-02-03",
                                "y": 2255
                            }, {
                                "x": "2024-02-02",
                                "y": 2445
                            }, {
                                "x": "2024-02-01",
                                "y": 2627
                            }, {
                                "x": "2024-01-31",
                                "y": 2779
                            }, {
                                "x": "2024-01-30",
                                "y": 2770
                            }, {
                                "x": "2024-01-29",
                                "y": 2989
                            }, {
                                "x": "2024-01-28",
                                "y": 2761
                            }, {
                                "x": "2024-01-27",
                                "y": 2522
                            }]
                        };
                        var series = [];
                        for (var key in data) {
                            series.push({
                                name: key,
                                data: data[key].map(function(point) {
                                    return {
                                        x: new Date(point.x).getTime(),
                                        y: point.y
                                    };

                                    return [point.x, point.y];
                                }),
                            });
                        }

                        Highcharts.chart('container', {
                            chart: {
                                type: 'line'
                            },
                            title: {
                                text: 'Marcas mais buscadas'
                            },
                            xAxis: {
                                type: 'datetime',
                            },
                            yAxis: {

                                title: {
                                    text: 'Número de buscas'
                                }
                            },
                            plotOptions: {
                                line: {
                                    dataLabels: {
                                        enabled: true
                                    },
                                },
                                series: {
                                    animation: false
                                }
                            },
                            series: series

                        });
                        console.log(series)
                    })();
                </script>
            </div>
        </div>
    </div>
    <div class="row step step-seminovos d-none">
        <div class="col-12 col-md-8">
            <h5>
                Informações portal SEMINOVOSBH
            </h5>
        </div>
        <div class="col-12 col-md-4 d-flex align-items-center justify-content-center justify-content-md-end pr-md-0">
            <div class="form-group mt-2">
                <div class='input-group date'>
                    <!-- <input type='text' class="form-control input date-timer-picker" />
                    <span class="input-group-addon text-black">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </span> -->
                    Janeiro de 2020
                </div>
            </div>
            <!-- <a href="#" class="btn btn-laranja">ok</a> -->
        </div>
        <div class="col-12 col-md-4 list list-marcas border-right border-dark">
            <div class="list-header">
                Marcas mais clicadas
            </div>
            <!--  -->
        </div>
        <div class="col-12 col-md-4 list list-modelos border-right border-dark">
            <div class="list-header">
                Modelos mais clicados
            </div>
        </div>
        <div class="col-12 col-md-4 list list-categorias">
            <div class="list-header">
                Categorias mais clicadas
            </div>
        </div>
    </div>
    <div class="row step step-tabela-fipe d-none">
        <div class="col-12 col-md-8">
            <h5>
                Tabela Fipe
            </h5>
        </div>
        <div class="col-12">
            <form class="row form-tabela-fipe">
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-2 mt-md-2 mt-xl-0 mt-2">
                    <select name="tipoVeiculo" placeholder="Selecione Marca" class="form-control" required>
                        <option value="1">Carro</option>
                        <option value="2">Caminhão</option>
                        <option value="3">Moto</option>
                    </select>
                </div>

                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-2 mt-md-2 mt-xl-0 mt-2">
                    <select name="idMarca" placeholder="Selecione Marca" class="form-control" required></select>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3 mt-md-2 mt-xl-0 mt-2">
                    <select name="modeloCarro" placeholder="Selecione Modelo" class="form-control" required></select>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-2 col-xl-2  mt-xl-0 mt-md-2 mt-2">
                    <select type="text" name="ano" placeholder="Selecione Ano" class="form-control" require>
                        <option value="">Selecione</option>
                        <?php
                        for ($i = date('Y'); $i >= 1931; $i--) {
                            echo "<option value='$i'>$i</option>";
                        }
                        ?>
                    </select>
                </div>

                <div class="col-sm-6 col-sm-4 col-md-2 col-lg-2 col-xl-2 mt-xl-0 mt-md-2 mt-2">
                    <button class="btn btn-success">Buscar</button>
                </div>

                <div class="col-12 mt-2 preco-fipe row">

                </div>
            </form>
        </div>

    </div>
    <div class="row step step-meus-veiculos">
        <div class="col-12 col-md-8">
            <h5>
                Meus Veículos
            </h5>
        </div>
        <div class="col-12 col-md-4 pr-md-0">
            <div class="form-group d-flex justify-content-end">
                <select name="ordenacao" class="form-control">
                    <option value="Ordenar por">Ordenar por</option>
                    <option value="Mais recentes">Mais recentes</option>
                    <option value="Mais antigos">Mais antigos</option>
                    <option value="Mais clicados">Mais clicados</option>
                    <option value="Menos clicados">Menos clicados</option>
                </select>
                <select name="status" class="form-control">
                    <option value="Status">Status</option>
                    <option value="Ativo">Ativo</option>
                    <option value="Inativo">Inativo</option>
                </select>
                <button class="btn btn-laranja filtrar-veiculos">ok</button>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group col-md-4">
                <label for="filtar-meus-veiculos">Filtrar:</label>
                <input type="text" id="filtar-meus-veiculos" class="form-control" placeholder="Filtrar por placa ou veículo">
            </div>
            <table id="table-meus-veiculos" class="table tableveiculos table-striped table-bordered sortable">
                <thead class="thead-dark">
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Placa</th>
                        <th>Veículo</th>
                        <th>Preço</th>
                        <th>Data cadastro</th>
                        <th>Plano</th>
                        <th>Tempo cadastro</th>
                        <th>Cliques</th>
                        <th>Impressões</th>
                        <th class="d-none d--md-table-cell">Cliques Telefone</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($veiculos as $key => $veiculo) : ?>
                        <?php
                        $isVeiculoAtivo = $veiculo['idStatus'] == 2;
                        $tempoCadastro = $formatDate->dias($veiculo['dataCadastro']);

                        $acessoTotal = $veiculo['metricas']['acesso']['total'] ?? 0;
                        $impressaoTotal = $veiculo['metricas']['impressao']['total'] ?? 0;
                        ?>
                        <tr>
                            <td class="status-veiculo" data-status='<?= $veiculo['idStatus'] ?>'>
                                <div class="<?= $isVeiculoAtivo ? 'text-success' : 'text-danger' ?>" title="<?= $isVeiculoAtivo ? 'Ativo' : 'Inativo' ?>">
                                    <i class="fa fa-circle" aria-hidden="true"></i>
                                </div>
                            </td>
                            <td class="status-veiculo">
                                <img style="width: 80px;height: 60px;" src="<?= $veiculo['thumb'] ?>" loading="lazy">
                            </td>
                            <td class="data-placa"><?= StringFuncs::placaFormat($veiculo['placa'] ?? '') ?></td>
                            <td class="data-marca-modelo">
                                <?= $veiculo['marca'] . ' <br>' . $veiculo['modelo'] . ' <br>' . $veiculo['anoFabricacao'] ?>/<?= $veiculo['anoModelo'] ?>
                            </td>
                            <td class="text-right" data-sort="<?= $veiculo['valor'] ?>">
                                <?php echo 'R$ ' . StringFuncs::nF((float) $veiculo['valor'], 2); ?>
                                <br>
                                <small title="Média Seminovos">
                                    <?php
                                    if ($veiculo['precoInfo']['mediaValor']) {
                                        echo 'R$ ' . StringFuncs::nF($veiculo['precoInfo']['mediaValor'], 2);
                                    } else {
                                        echo '<span class="text-muted">Média indisponível</span>';
                                    }
                                    ?>
                                </small>
                                <?php
                                if ($veiculo['precoInfo']['mediaValor']) {
                                    if ($veiculo['precoInfo']['mediaValor'] < $veiculo['valor']) {
                                        echo '<span title="Preço acima da média da Seminovos">';
                                        echo $arrowUp;
                                        echo '</span>';
                                    } else {
                                        echo '<span title="Preço abaixo da média da Seminovos">';
                                        echo $arrowDown;
                                        echo '</span>';
                                    }
                                }
                                ?>
                                <br>
                                <?php if ($veiculo['precoInfo']['fipe']) : ?>
                                    <small><?= 'R$ ' . StringFuncs::nF($veiculo['precoInfo']['fipe']['valor'], 2) ?></small>
                                    <?php
                                    if ($veiculo['precoInfo']['fipe']['valor'] < $veiculo['valor']) {
                                        echo '<span title="Preço acima da tabela FIPE">';
                                        echo $arrowUp;
                                        echo '</span>';
                                    } else {
                                        echo '<span title="Preço abaixo da tabela FIPE">';
                                        echo $arrowDown;
                                        echo '</span>';
                                    }
                                    ?>
                                <?php else : ?>
                                    <small class="text-muted">FIPE indisponível</small>
                                <?php endif ?>
                            </td>
                            <td class="data-cadastro" data-sort="<?= $veiculo['dataCadastro'] ?>"><?= $formatDate->converterDataBR($veiculo['dataCadastro']) ?></td>
                            <td data-sort="<?= $veiculo['prioridadePlano'] ?? 0 ?>">
                                <?= $veiculo['nomePlano'] ?? '' ?>
                            </td>
                            <td data-sort="<?= time() - strtotime($veiculo['dataCadastro']) ?>">
                                <?php

                                $diff = $hoje->diff(new DateTime($veiculo['dataCadastro']));

                                $diffValues = [
                                    'anos' => (int) $diff->format('%Y'),
                                    'meses' => (int) $diff->format('%m'),
                                    'dias' => (int) $diff->format('%d')
                                ];
                                if ($diffValues['anos']) {
                                    echo $diffValues['anos'] . ' ' . ($diffValues['anos'] > 1 ? ' anos' : ' ano') . ', ';
                                }
                                if ($diffValues['meses']) {
                                    echo $diffValues['meses'] . ($diffValues['meses'] > 1 ? ' meses' : ' mês') . ' e ';
                                }
                                if ($diffValues['dias']) {
                                    echo $diffValues['dias'] . ($diffValues['dias'] > 1 ? ' dias' : ' dia');
                                }

                                ?>
                            </td>

                            <td data-sort="<?= $acessoTotal ?>">
                                <?php

                                echo StringFuncs::nF($acessoTotal);

                                if ($acessoTotal) {
                                    echo '<br>';
                                    echo StringFuncs::nF($acessoTotal / $tempoCadastro) . '/dia';
                                }
                                ?>
                            </td>
                            <td data-sort="<?= $impressaoTotal ?>">
                                <?php
                                echo StringFuncs::nF($impressaoTotal);
                                if ($impressaoTotal) {
                                    echo '<br>';
                                    echo StringFuncs::nF($impressaoTotal / $tempoCadastro) . '/dia';
                                }
                                ?>
                            </td>
                            <td class="d-none cliques">
                                -
                            </td>
                            <td>
                                <div class="icon-1-5x text-success">
                                    <a href="<?= 'painel/' . $veiculo['idVeiculo'] ?>">
                                        <i class="fa fa-eye" aria-hidden="true">
                                        </i>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="icon-1-5x text-success">
                                    <a href="<?= strtolower((string) $veiculo['tipo']) . '/' . $veiculo['idVeiculo'] ?>">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    </a>

                                </div>
                            </td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
