<?php
$this->headTitle("Cadastro Área Restrita");

$dadosForm = $formCadastro;
$dadosForm->prepare();
$fields = $dadosForm->getElements();
?>

<?= $this->form()->openTag($dadosForm) ?>
<div class="container d-flex justify-content-center">
    <div class="row col-12 col-md-6 pt-3 bg-white">
        <div class="col-12">
            <h1>
                Cadastre-se
            </h1>
        </div>
        <div class="col-12">
            <?php if ($this->erro): ?>
                <div class="alert alert-danger" role="alert">
                <?= $this->erro ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-12">
            <div class="form-group required">
                <?= $this->formLabel($fields['email'])  ?>
                <?= $this->formEmail($fields['email'])  ?>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group required">
                <?= $this->formLabel($fields['confirmacaoEmail'])  ?>
                <?= $this->formEmail($fields['confirmacaoEmail'])  ?>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="form-group required">
                <?= $this->formLabel($fields['responsavelNome'])  ?>
                <?= $this->formText($fields['responsavelNome'])  ?>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="form-group">
                <?= $this->formLabel($fields['cpfResponsavel'])  ?>
                <?= $this->formText($fields['cpfResponsavel'])  ?>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="form-group required mb-0">
                <?= $this->formLabel($fields['senha'])  ?>
                <?= $this->formPassword($fields['senha'])  ?>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="form-group required mb-0">
                <?= $this->formLabel($fields['confirmacaoSenha'])  ?>
                <?= $this->formPassword($fields['confirmacaoSenha'])  ?>
            </div>
        </div>
        <div class="col-12 mb-2">
            <small>(Recomendamos que a senha tenha no mínimo <b>4 caracteres</b> incluindo letras e números)</small>
        </div>
        <div class="col-12">
            <div class="row d-flex align-items-end">
                <div class="form-group required col-12 col-md-4 required">
                    <?= $this->formLabel($fields['telefone_2']) ?>
                    <?= $this->formText($fields['telefone_2']) ?>
                </div>
                <div class="form-group col-6 col-md-4 required">
                    <?= $this->formLabel($fields['operadora_2']) ?>
                    <?= $this->formSelect($fields['operadora_2']) ?>
                </div>
                <div class="form-group col-6 col-md-4">
                    <div class="checkbox check-success m-0">
                        <?= $this->formCheckbox($fields['telefone_2_is_wpp']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <button type="submit" name="submit" class="btn btn-block btn-laranja text-white" value="Cadastrar">Cadastrar</button>
            </div>
        </div>
        <div class="col mt-3 mb-3">
            <span class="text-danger h3">*</span> Esses campos são obrigatórios
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>