<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
//echo $this->form($this->formCadastro);

$dadosForm = new \AreaRestrita\Form\MeusDados\ParticularForm();

$dadosForm->prepare();

$fields = $dadosForm->getElements();

$fields['responsavelNome']->setAttribute('readonly', false);
$fields['email']->setAttribute('readonly', false);
$fields['cpfResponsavel']->setAttribute('readonly', false);
$fields['telefone_2_is_wpp']->setChecked(false);
$fields['telefone_3_is_wpp']->setChecked(false);

?>
<form method="POST" name="form_particularSite" class="form-group" role="form" id="form_particularSite" action="me-cadastrar">
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <!-- START card -->
            <div class="card card-default">
                <div class="snbh-logo-container">
                    <!--<img src="/img/svg/snbh_logo.svg" alt="logo" class="snbh-logo" width="180" height="66">-->
                    <svg viewBox="0 0 180 66" width="180" height="66" class="snbh-logo">
                        <use xlink:href="/img/svg/snbh_logo.svg#layer_car" class="layer-car"></use>
                        <use xlink:href="/img/svg/snbh_logo.svg#layer_letters" class="layer-letters"></use>
                    </svg>
                </div>
                <div class="card-header ">
                    <div class="card-title">SeminovosBH - Cadastro de Usuário</div>
                </div>
                <div class="card-body">
                    <p><small>Preencha corretamente os dados abaixo e clique noo botão entrar para criar seu cadastro</small></p>
                    <form role="form">
                        <div class="form-group">
                            <?= $this->formLabel($fields['responsavelNome']) ?>
                            <?= $this->formText($fields['responsavelNome']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['email']) ?>
                            <?= $this->formText($fields['email']) ?>
                        </div>
                        <div class="form-group">
                            <label>Confirme o e-mail</label>
                            <input type="email" class="form-control" placeholder="seuemail@example.com.br" required>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['cpfResponsavel']) ?>
                            <?= $this->formText($fields['cpfResponsavel']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['rg']) ?>
                            <?= $this->formText($fields['rg']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['idEstado']) ?>
                            <?= $this->formSelect($fields['idEstado']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['idCidade']) ?>
                            <?= $this->formSelect($fields['idCidade']) ?>
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <?= $this->formLabel($fields['telefone_1']) ?>
                                <?= $this->formText($fields['telefone_1']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <?= $this->formLabel($fields['telefone_2']) ?>
                                <?= $this->formText($fields['telefone_2']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['operadora_2']) ?>
                            <?= $this->formSelect($fields['operadora_2']) ?>
                        </div>
                        <div class="form-group">
<!--                            --><?//= $this->formLabel($fields['telefone_2_is_wpp']) ?>
                            <?= $this->formCheckbox($fields['telefone_2_is_wpp']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['telefone_3']) ?>
                            <?= $this->formText($fields['telefone_3']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['operadora_3']) ?>
                            <?= $this->formSelect($fields['operadora_3']) ?>
                        </div>
                        <div class="form-group">
<!--                            --><?//= $this->formLabel($fields['telefone_3_is_wpp']) ?>
                            <?= $this->formCheckbox($fields['telefone_3_is_wpp']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['senha']) ?>
                            <?= $this->formPassword($fields['senha']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($fields['confirmacaoSenha']) ?>
                            <?= $this->formPassword($fields['confirmacaoSenha']) ?>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn-warning btn-block btn-lg" >Entrar</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END card -->
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
</form>
