<?php
/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */

$this->headTitle("Cadastre-se");


/** @var AreaRestrita\Form\MeusDados\ParticularForm $dadosForm  */
$dadosForm->prepare();

$fields = $dadosForm->getElements();

$fields['responsavelNome']->setAttribute('readonly', false);
$fields['email']->setAttribute('readonly', false);
$fields['email']->setAttribute('class', 'form-group-default');
$fields['telefone_2_is_wpp']->setChecked(false);
$fields['senha']->setAttributes(['autocomplete' => 'off', 'minlength'  => '4']);
?>
<form method="POST" name="form_particularSite" class="container-fluid" role="form" id="form_particularSite" action="me-cadastrar">
    <div class="container-fluid container-fixed-lg">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4 mt-md-4">
                <!-- START card -->
                <div class="card card-default m-0">
                    <div class="snbh-logo-container d-flex justify-content-center mt-3">
                        <!--<img src="/img/svg/snbh_logo.svg" alt="logo" class="snbh-logo" width="180" height="66">-->
                        <a href="/" title="Voltar e fazer login">
                            <svg viewBox="0 0 180 66" width="180" height="66" class="snbh-logo">
                                <use xlink:href="/img/svg/logo.svg#layer_car" class="layer-car"></use>
                                <use xlink:href="/img/svg/logo.svg#layer_letters" class="layer-letters"></use>
                            </svg>
                        </a>
                    </div>
                    <div class="card-header ">
                        <div class="text-center">
                            <span class="h1">Cadastre-se</span>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-12 col-md-12">
                                <?= $this->formLabel($fields['responsavelNome']) ?>
                                <?= $this->formText($fields['responsavelNome']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12">
                                <?= $this->formLabel($fields['email']) ?>
                                <?= $this->formEmail($fields['email']) ?>
                            </div>
                        </div>
                        <div class="row row-senha">
                            <div class="form-group col-12">
                                <?= $this->formLabel($fields['senha']) ?>
                                <div class="input-group group-senha">
                                    <?= $this->formPassword($fields['senha']) ?>
                                    <div class="input-group-prepend show-password">
                                        <div class="input-group-text"><i class="fa fa-eye" aria-hidden="true"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <div class="form-group col-8">
                                <?= $this->formLabel($fields['telefone_2']) ?>
                                <?= $this->formText($fields['telefone_2']) ?>
                            </div>
                            <div class="form-group col-4">
                                <div class="checkbox check-success m-0">
                                    <?= $this->formCheckbox($fields['telefone_2_is_wpp']) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <?= $this->formLabel($fields['idEstado']) ?>
                                <?= $this->formSelect($fields['idEstado']) ?>
                            </div>
                            <div class="form-group col-6">
                                <?= $this->formLabel($fields['idCidade']) ?>
                                <?= $this->formSelect($fields['idCidade']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 mb-3">
                                <small>
                                    Clicando em "Cadastrar" você estará de acordo com os
                                    <a href="https://seminovos.com.br/termo-de-responsabilidade" target="_blank" class="text-warning no-wrap">
                                        termos de responsibilidade
                                    </a>.
                                </small>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12">
                                <button type="submit" class="btn btn-warning btn-block btn-lg">Cadastrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>
</form>
<!-- Facebook Pixel Code -->
<script>
    ! function(f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function() {
            n.callMethod ?
                n.callMethod.apply(n, arguments) : n.queue.push(arguments)
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s)
    }(window, document, 'script',
        'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '408763516364456');
    fbq('track', 'cadastro');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=408763516364456&ev=PageView&noscript=1" /></noscript>
<!-- End Facebook Pixel Code -->
