<?php

$this->headTitle("Cadastro Área Restrita");


$dadosForm = new \AreaRestrita\Form\MeusDados\ParticularForm();

$dadosForm->prepare();

$fields = $dadosForm->getElements();

$fields['responsavelNome']->setAttribute('readonly', false);
$fields['email']->setAttribute('readonly', false);
$fields['email']->setAttribute('class', 'form-group-default');
$fields['cpfResponsavel']->setAttribute('readonly', false);
$fields['telefone_2_is_wpp']->setChecked(false);
$fields['telefone_3_is_wpp']->setChecked(false);
$fields['senha']->setAttribute('autocomplete', 'off');
?>
<form method="POST" name="form_particularSite" class="container-fluid" role="form" id="form_particularSite"
    action="me-cadastrar">
    <div class="container-fluid container-fixed-lg">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4 mt-md-4">
                <!-- START card -->
                <div class="card card-default m-0">
                    <div class="snbh-logo-container d-flex justify-content-center mt-3">
                        <!--<img src="/img/svg/snbh_logo.svg" alt="logo" class="snbh-logo" width="180" height="66">-->
                        <a href="/" title="Voltar e fazer login">
                            <svg viewBox="0 0 180 66" width="180" height="66" class="snbh-logo">
                                <use xlink:href="/img/svg/logo.svg#layer_car" class="layer-car"></use>
                                <use xlink:href="/img/svg/logo.svg#layer_letters" class="layer-letters"></use>
                            </svg>
                        </a>
                    </div>
                    <div class="card-header ">
                        <div class="card-title">
                            <span class="">SeminovosBH - Cadastro de Usuário</span> 
                        </div>
                    </div>
                    <div class="card-body">
                        <p>
                            <small>Preencha os dados abaixo e clique no botão cadastrar para criar seu cadastro</small>
                        </p>
                        <div class="row">
                            <div class="form-group col-6 required">
                                <?= $this->formLabel($fields['cpfResponsavel']) ?>
                                <?= $this->formText($fields['cpfResponsavel']) ?>
                            </div>
                            <div class="form-group col-6 col-md-6 required">
                                <?= $this->formLabel($fields['responsavelNome']) ?>
                                <?= $this->formText($fields['responsavelNome']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 required">
                                <?= $this->formLabel($fields['rg']) ?>
                                <?= $this->formText($fields['rg']) ?>
                            </div>
                            <div class="form-group col-6 col-md-6">
                                <div class="d-none d-md-block">
                                    <?= $this->formLabel($fields['dataNascimento']) ?>
                                </div>
                                <div class="d-block d-md-none">
                                    <?= str_replace('Data de Nascimento','Nascimento',$this->formLabel($fields['dataNascimento'])) ?>
                                </div>
                                <?= str_replace('class="', 'placeholder="31/12/1980" class="', $this->formElement($fields['dataNascimento'])) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12 col-md-6 required">
                                <?= $this->formLabel($fields['email']) ?>
                                <?= $this->formEmail($fields['email']) ?>
                            </div>
                            <div class="form-group col-12 col-md-6 required">
                                <label>Confirme o e-mail</label>
                                <input type="email" name="confirmacao-email" class="form-control"
                                    placeholder="seuemail@example.com.br" required>
                            </div>
                        </div>
                        <div class="row row-senha">
                            <div class="form-group required col-6 mb-0">
                                <?= $this->formLabel($fields['senha']) ?>
                                <?= $this->formPassword($fields['senha']) ?>
                            </div>
                            <div class="form-group required col-6 mb-0">
                                <?= $this->formLabel($fields['confirmacaoSenha']) ?>
                                <?= $this->formPassword($fields['confirmacaoSenha']) ?>
                            </div>
                            <div class="col-12">
                                <small class="text-success">
                                    sua senha deve conter no
                                    mínimo 4 caractéres
                                </small>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 required">
                                <?= $this->formLabel($fields['idEstado']) ?>
                                <?= $this->formSelect($fields['idEstado']) ?>
                            </div>
                            <div class="form-group col-6 required">
                                <?= $this->formLabel($fields['idCidade']) ?>
                                <?= $this->formSelect($fields['idCidade']) ?>
                            </div>
                        </div>
                        <div class="row d-flex align-items-end">
                            <div class="p-0 form-group col-4 required">
                                <?= $this->formLabel($fields['telefone_2']) ?>
                                <?= $this->formText($fields['telefone_2']) ?>
                            </div>
                            <div class="p-0 form-group col-4 required">
                                <?= $this->formLabel($fields['operadora_2']) ?>
                                <?= $this->formSelect($fields['operadora_2']) ?>
                            </div>
                            <div class="p-0 pl-1 pl-md-2 form-group col-4">
                                <div class="checkbox check-success m-0">
                                    <?= $this->formCheckbox($fields['telefone_2_is_wpp']) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row d-flex align-items-end">
                            <div class="p-0 form-group col-4">
                                <?= $this->formLabel($fields['telefone_3']) ?>
                                <?= $this->formText($fields['telefone_3']) ?>
                            </div>
                            <div class="p-0 form-group col-4">
                                <?= $this->formLabel($fields['operadora_3']) ?>
                                <?= $this->formSelect($fields['operadora_3']) ?>
                            </div>
                            <div class="p-0 pl-1 pl-md-2 form-group col-4">
                                <div class="checkbox check-success m-0">
                                    <?= $this->formCheckbox($fields['telefone_3_is_wpp']) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12">
                                <?= $this->formLabel($fields['telefone_1']) ?>
                                <?= $this->formText($fields['telefone_1']) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="checkbox check-success termo_responsabilidade m-0">
                                    <input type="hidden" name="termo_responsabilidade" value="0">
                                    <input type="checkbox" required name="termo_responsabilidade" value="1"
                                        id="termo_responsabilidade">
                                    <label for="termo_responsabilidade"> Li e aceito os <a
                                            href="https://seminovos.com.br/termo-de-responsabilidade"
                                            target="_blank">termos de
                                            responsibilidade</a>.</label>
                                </div>
                            </div>
                            <div class="col-12 obrigatorios mb-2">
                                <small>
                                    <span class="text-danger">*</span> Esses campos são obrigatórios
                                </small>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-12">
                                <button type="submit" class="btn btn-warning btn-block btn-lg">Cadastrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>
</form>
<!-- Facebook Pixel Code -->
<script>
! function(f, b, e, v, n, t, s) {
    if (f.fbq) return;
    n = f.fbq = function() {
        n.callMethod ?
            n.callMethod.apply(n, arguments) : n.queue.push(arguments)
    };
    if (!f._fbq) f._fbq = n;
    n.push = n;
    n.loaded = !0;
    n.version = '2.0';
    n.queue = [];
    t = b.createElement(e);
    t.async = !0;
    t.src = v;
    s = b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t, s)
}(window, document, 'script',
    'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '408763516364456');
fbq('track', 'cadastro');
</script>
<noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=408763516364456&ev=PageView&noscript=1" /></noscript>
<!-- End Facebook Pixel Code -->