<div class="topo d-flex align-items-end px-3 pb-2">
    <h1 class="mr-3 mb-0">Central de Informações</h1>
    <span class="mb-1">Clique nos itens para saber mais!</span>
</div>
<div class="opcoes d-flex justify-content-between flex-wrap px-3">
    <a href="#" class="opcao" data-target=".golpe">
        <div class="texto"><span class="text-danger">Cuidado!</span><br/>Novo golpe no mercado</div>
        <div class="icone"><i class="fa fa-bell-o" aria-hidden="true"></i></div>
    </a>
    <a href="#" class="opcao" data-target=".anuncio">
        <div class="texto">Como fazer seu anúncio</div>
        <div class="icone"><i class="fa fa-bell-o" aria-hidden="true"></i></div>
    </a>
    <a href="#" class="opcao" data-target=".atendimento">
        <div class="texto">Como melhorar o atendimento da sua loja!</div>
        <div class="icone"><i class="fa fa-bell-o" aria-hidden="true"></i></div>
    </a>
    <a href="#" class="opcao" data-target=".selo">
        <div class="texto">Funcionalidade Selo Delivery</div>
        <div class="icone"><i class="fa fa-bell-o" aria-hidden="true"></i></div>
    </a>
</div>
<div class="conteudo">
    <div class="golpe collapsed" style="display: none;">
        <h2 class="titulo"><span class="text-danger">Cuidado!</span> Novo golpe no mercado</h2>
        <div class="texto">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos, deleniti blanditiis id exercitationem soluta ducimus non nihil perferendis mollitia! Doloremque illum ratione odit excepturi aperiam quidem eaque quas dolorem est!
        </div>
        <div class="infos container-video">
            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/WNR_xrXJpWo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    <div class="anuncio collapsed" style="display: none;">
        ANUNCIO
    </div>
    <div class="atendimento collapsed" style="display: none;">
        ATENDIMENTO
    </div>
    <div class="selo collapsed" style="display: none;">
        <h2 class="titulo"><span class="text-laranja">Funcionalidade:</span> Selo Delivery</h2>
        <div class="texto">
            <p>Criamos uma funcionalidade para comodidade do seus clientes.</p>
            <p>Ao criar o anúncio do seu veículo, selecione a opção LEVAMOS ATÉ VOCÊ.</p>
            <p>Esta opção infoma ao cliente que aquele veículo pode ser levado ao seu cliente. Claro que com todas as condições que a sua revenda precise.</p>
            <p>Lembre-se que é você quem estipula essas condições como horário, taxa, disponibilidade e etc.</p>
            <p>Veja abaixo como selecionar esta opção.</p>
        </div>
        <div class="infos">
            <div>
                <b>Marque a opção conforme a imagem abaixo:</b>
            </div>
            <img src="/img/exemplo/sample_selo_delivery_01.jpg" alt="" srcset=""/>

            <div>
                <b>Essa informação aparecerá para o usuário da seguinte forma:</b>
            </div>
            <img src="/img/exemplo/sample_selo_delivery_02.jpg" alt="" srcset=""/>
        </div>
    </div>
    
</div>