<div class="container">
    <div class="row">
        <div class="col-10 align-self-end">
            <div class="d-flex">
                <h3 class="font-montserrat all-caps hint-text">MEUS DADOS</h3>
            </div>
            <div class="card card-default d-flex">
                <div class="card-header ">
                    <div class="card-title">Alterar Senha</div>
                </div>
                <div class="card-body">
                    <form action="/alterar-senha" method="POST">
                        <div class="d-flex">
                            <div class="w-50">
                                <div class="form-group form-group-default required">
                                    <label>Senha Atual</label>
                                    <input type="password" name="senhaAtual" class="form-control" value="">
                                </div>
                            </div>
                        </div>
                        <div class="d-flex">
                            <div class="w-50">
                                <div class="form-group form-group-default required">
                                    <label>Nova Senha</label>
                                    <input type="password" name="senha" class="form-control" value="">
                                </div>
                            </div>
                            <div class="w-50">
                                <div class="form-group form-group-default required">
                                    <label>Confirmar Senha</label>
                                    <input type="password" name="confirmacaoSenha" class="form-control" value="">
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button class="btn btn-laranja text-white block-btn " type="submit">
                                ENVIAR
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>