<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */

usort($planos, function ($a, $b) {
    return $b['ordem'] <=> $a['ordem'];
});

$prioridade = [
    1 => 'máxima',
    2 => 'alta',
    3 => 'média',
    4 => 'baixa',
    5 => 'mínima',
];

$class = [
    1 => 'nitro-home-value',
    2 => 'nitro-value',
    3 => 'turbo-value',
    4 => 'basic-value',
    5 => 'simple-value',
];

$boxes = [
    1 => 'nitro-home',
    2 => 'nitro',
    3 => 'turbo',
    4 => 'basico',
    5 => 'simples',
];

?>
<div class="container">
    <h4 class="text-center">
        PLANOS DE ANÚNCIOS
    </h4>
    <div class="text-center my-3">
        <small class="align-center">Preencha corretamente os campos abaixo e clique no botão próximo para criar seu
            anúncio.
            <br />Campos com * são de preenchimento obrigatório.
        </small>
    </div>

    <div class="row">
        <form name="form_Plano">
            <div class="row-full">
                <div class="container">
                    <div class="row grupo-planos">
                        <?php
                        $planoJaEscolhido = false;
                        foreach ($planos as $k => $plano) :
                            if ($plano['idPlano'] == $idPlanoAtual) {
                                $planoJaEscolhido = true;
                            }
                            $desabilitarPlano = false;
                            if ($planoJaEscolhido && $plano['idPlano'] != $idPlanoAtual) {
                                $desabilitarPlano = true;
                            }

                            ?>
                            <div class="col-12 col-sm col-md col-lg">
                                <div class="plano-box plano-box-<?= $boxes[$plano['prioridade']] ?>" <?= $desabilitarPlano ? 'title="Não é possível diminuir o plano"' : '' ?>>
                                    <div class="linha-plano size-2x plano-<?= $boxes[$plano['prioridade']] ?>">
                                        <div class="plano-number"><?= $k + 1 . 'º' ?></div>
                                        <div class="icon-plano">
                                            <span class="bar-1"></span>
                                            <span class="bar-2"></span>
                                            <span class="bar-3"></span>
                                            <span class="bar-4"></span>
                                            <span class="bar-4"></span>
                                        </div>
                                        <h3><?= $plano['nomePlano'] ?></h3>
                                    </div>
                                    <ul class="list list-styled list-<?= $boxes[$plano['prioridade']] ?>">
                                        <li>
                                            <span>
                                                <strong><?= $plano['quantidadeFotos']; ?></strong>
                                                fotos por anúncio
                                            </span>
                                        </li>
                                        <?php
                                        if ($boxes[$plano['prioridade']] == 'nitro-home' || $boxes[$plano['prioridade']] == 'nitro' || $boxes[$plano['prioridade']] == 'turbo') {
                                            echo '<li><span>1 vídeo</span></li>';
                                        } else {
                                            echo '<li><span class="text-black-50"><s>0 vídeos</s></span></li>';
                                        }

                                        if ($boxes[$plano['prioridade']] == 'simples') {
                                            $anuncioTempo = 'Exibição no site por 10 dias';
                                        } else {
                                            $anuncioTempo = 'Exibição no site até a venda*';
                                        }

                                        ?>
                                        <li><span><?= $anuncioTempo; ?></span></li>

                                        <li><span>Prioridade <strong><?= $prioridade[$plano['prioridade']] ?></strong> de
                                                exibição</span></li>
                                    </ul>
                                    <div class="nitro-home-label <?= $class[$plano['prioridade']] ?>">R$
                                        <?= number_format((float) $plano['valorPlano'], 2, ',', '.') ?></div>
                                    <input type="radio"
                                           id="radio-idPlano-<?= $k + 1 ?>"
                                           name="idPlano"
                                           value="<?= $plano['idPlano'] ?>"
                                           class="hidden"
                                           <?= $plano['idPlano'] == $idPlanoAtual ? 'checked' : '' ?>
                                           <?= $desabilitarPlano ? 'disabled' : '' ?>
                                           data-valor-plano="<?= $plano['valorPlano'] ?>">
                                    <label class="btn btn-block btn-sm bg-light text-dark" for="radio-idPlano-<?= $k + 1 ?>" <?= $desabilitarPlano ? 'data-plano-desativado' : '' ?>>
                                        Selecione
                                    </label>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="form-group ">
                        <input type="submit">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>