<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: center;">
    <span style="font-size:16px;"><strong>TERMO DE ADES&Atilde;O SEMINOVOSBH - PESSOA F&Iacute;SICA&nbsp;</strong></span></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A SeminovosBH</strong>&nbsp;por se tratar de um portal de classificados virtuais de anuncios de veiculos, n&atilde;o se responsabiliza por qualquer dano e/ou preju&iacute;zo que o usu&aacute;rio possa sofrer ao realizar uma negocia&ccedil;&atilde;o com outros usu&aacute;rios deste web site tendo em vista que a negocia&ccedil;&atilde;o e pagamento s&atilde;o feitas entre as partes n&atilde;o tendo o site nenhuma participa&ccedil;&atilde;o. O objetivo do portal &eacute; a exibi&ccedil;&atilde;o p&uacute;blica dos an&uacute;ncios feitos pelo anunciante, sendo assim todos os dados inseridos por ele tais como informa&ccedil;&otilde;es e fotos s&atilde;o de inteira responsabilidade do mesmo, tornando-se estes dados p&uacute;blicos<br />
    <strong>&bull;&nbsp;</strong>As vendas , entregas e informa&ccedil;&otilde;es dos ve&iacute;culos anunciados , s&atilde;o de inteira responsabilidade do anunciante. A <strong>SeminovosBH</strong> n&atilde;o realiza a intermedia&ccedil;&atilde;o das vendas, compras, trocas ou qualquer outro tipo de transa&ccedil;&atilde;o feita pelos usu&aacute;rios de seu web site, somente disponibiliza informa&ccedil;&otilde;es lan&ccedil;adas pelo anunciante para que os interessados fa&ccedil;am contato.</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Disposi&ccedil;&otilde;es Iniciais</strong></span></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; O anunciante &eacute; o &uacute;nico respons&aacute;vel pela veracidade das informa&ccedil;&otilde;es contidas nos an&uacute;ncios que contratar, bem como pela confer&ecirc;ncia dos dados, cadastrados por ele, neste web site. A veicula&ccedil;&atilde;o de informa&ccedil;&otilde;es falsas ou de titularidade de terceiros implicar&aacute; na suspens&atilde;o imediata da veicula&ccedil;&atilde;o do an&uacute;ncio, sujeitando o anunciante &agrave;s a&ccedil;&otilde;es legais cab&iacute;veis e perda do an&uacute;ncio</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &Eacute; proibido anunciar ve&iacute;culos de maneira que leve o <span style="font-size:12px;">comprador</span> a erro ou que ludibrie o mesmo tais como ve&iacute;culo recuperado sem a informa&ccedil;&atilde;o, quilometragem adulterada e envolvimento em acidente que causou danos que n&atilde;o foram totalmente reparados sem a pr&eacute;via informa&ccedil;&atilde;o. Caso chegue a nosso conhecimento este tipo de problema e seja verificado o anunciante ser&aacute; banido do site. No caso de descumprimento destas normas ser&atilde;o tomadas medidas legais, c&iacute;veis e criminais contra o anunciante e caso o site seja processado em conjunto com o anunciante ser&aacute; movida a&ccedil;&atilde;o de regresso cobrando pelas despesas acarretadas pelo ato.</strong></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A <strong>SeminovosBH</strong> n&atilde;o se responsabiliza por quaisquer danos diretos e/ou indiretos causados a terceiros, advindos da exibi&ccedil;&atilde;o dos an&uacute;ncios em desacordo com as leis, pois se trata de portal e os anunciantes que inserem todos os dados.</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A <strong>SeminovosBH</strong> n&atilde;o garante o &ecirc;xito de qualquer transa&ccedil;&atilde;o realizada pelos usu&aacute;rios deste web site. Esta empresa n&atilde;o se responsabiliza tamb&eacute;m pelo conte&uacute;do das correspond&ecirc;ncias entre usu&aacute;rios em negocia&ccedil;&atilde;o, nem pelos contratos que estes venham a estabelecer com terceiros.nenhuma conversa de negocia&ccedil;&atilde;o &eacute; monitorada e toda a negocia&ccedil;&atilde;o &eacute; feita diretamente entre as partes (comprador e vendedor)</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An&uacute;ncios provenientes de revendedores, ag&ecirc;ncias de autom&oacute;veis ou que estejam em lojas sob forma de consigna&ccedil;&atilde;o,caso&nbsp;esteja anunciado no site como particular ser&atilde;o removidos do site deliberadamente sem ressarcimento do valor pago,caso seja confirmado tal a&ccedil;&atilde;o.</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Prazo para renova&ccedil;&atilde;o</strong></span></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Todo an&uacute;ncio feito no Portal por um dos planos pagos tem direito a veicula&ccedil;&atilde;o no site at&eacute; a venda, n&atilde;o sendo poss&iacute;vel a substitui&ccedil;&atilde;o por outro ve&iacute;culo no mesmo an&uacute;ncio entretanto o cliente dever&aacute; renov&aacute;-lo sem &ocirc;nus a cada 30 dias visando a atualiza&ccedil;&atilde;o do site. Caso o cliente n&atilde;o&nbsp; reative ou renove seu anuncio depois de 30 dias expirado, o mesmo ser&aacute; exclu&iacute;do do banco de dados perdendo o direito de renova&ccedil;&atilde;o gratuita.<br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An&uacute;ncios de ve&iacute;culos 0KM ou quilometragem at&eacute; 500km tem prazo de veicula&ccedil;&atilde;o de 30 dias n&atilde;o podendo ser renovado sem um novo pagamento.<br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Caso o anunciante coloque como vendido ou remova o an&uacute;ncio, o mesmo perder&aacute; o direito de renova&ccedil;&atilde;o sem &ocirc;nus.<br />
    <br />
    &nbsp;</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Seguran&ccedil;a das Informa&ccedil;&otilde;es</strong></span></p>
<p style="margin-left: 4.2pt; text-align: justify;">
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Todos os dados pessoais informados ao nosso site s&atilde;o armazenados em um banco de dados criptografado, reservado e com acesso restrito.<br />
    Todos os dados cadastrados no sistema pelos seus usu&aacute;rios, ser&atilde;o armazenados em nosso banco de dados n&atilde;o cabendo ao usu&aacute;rio a remo&ccedil;&atilde;o do mesmo. Assegurar a sua privacidade &eacute; mais um compromisso da <strong>SeminovosBH</strong> com voc&ecirc;.</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Apenas veiculos particulares ser&atilde;o aceitos neste formato de anuncio.&nbsp;</strong></span></p>
<p style="margin-top:5.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:
   3.75pt;text-align:justify">
    <br />
    <b style="font-size: 14px;"><span style="font-family: Arial, sans-serif;">Particulares&nbsp;</span></b><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></p>
<p style="margin-top:5.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:
   4.2pt;text-align:justify">
    <em><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&Eacute; todo anuncio, publicado feito por pessoa f&iacute;sica sem fins lucrativos, que seja e esteja em posse do vendedor com DUT do veiculo em seu nome.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></em><span style="font-size: 9pt; font-family: Arial, sans-serif;"><o:p></o:p></span></p>
<p style="margin-top:5.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:
   4.2pt;text-align:justify">
    <em><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp;N&atilde;o &eacute; permitido a veicula&ccedil;&atilde;o de an&uacute;ncios de revendas, lojistas ou quem fa&ccedil;a da venda de veiculos seu neg&oacute;cio fim, fora da sua &aacute;rea espec&iacute;fica.</span></em><span style="font-size: 9pt; font-family: Arial, sans-serif;"><o:p></o:p></span></p>
<p style="margin: 5pt 0cm 12pt 4.2pt; text-align: justify;">
    <em><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Caso um ve&iacute;culo seja anunciado no portal como particular e o mesmo seja de revenda ou lojista ou tenha algum vinculo com os mesmos, ( fotos, telefones etc..) este ser&aacute; removido do sistema sem o ressarcimento da import&acirc;ncia paga.</span></em><span style="font-size: 9pt; font-family: Arial, sans-serif;"><o:p></o:p></span></p>
<p style="margin-left: 4.2pt; text-align: justify;">
    <em><span style="font-size: 9pt; font-family: Arial, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An&uacute;ncios de carta de cr&eacute;dito ou cons&oacute;rcio s&oacute; podem ser feitos por revendas nos termos do contrato&nbsp;aceito.</span></em><span style="font-size: 9pt; font-family: Arial, sans-serif;"><o:p></o:p></span></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Publica&ccedil;&atilde;o e Altera&ccedil;&atilde;o de Imagens</strong></span></p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Todo an&uacute;ncio no site tem a op&ccedil;&atilde;o de altera&ccedil;&atilde;o de imagens do ve&iacute;culo, entretanto s&oacute; poder&aacute; ser solicitado a altera&ccedil;&atilde;o de imagens a cada 30 dias&nbsp;<strong>n&atilde;o&nbsp;</strong>sendo permitido a publica&ccedil;&atilde;o de imagens com textos, descri&ccedil;&otilde;es do veiculo ou qualquer informa&ccedil;&atilde;o publicit&aacute;ria.</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An&uacute;ncios gratuitos <strong>n&atilde;o</strong> tem a op&ccedil;&atilde;o de altera&ccedil;&atilde;o ou inser&ccedil;&atilde;o&nbsp;de novas imagens no site.&nbsp;&nbsp;Informamos ainda que apenas as iniciais da placa ser&atilde;o exibidas. Mas aconselhamos o cliente a editar as fotos antes da publica&ccedil;&atilde;o, visando omitir nas fotos os n&uacute;meros da placa.</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Solicitamos tamb&eacute;m, que o cliente antes de fazer seu anuncio, tire varias fotos do ve&iacute;culo a ser anunciado, pois&nbsp;n&atilde;o ser&atilde;o aceitos fotos ilustrativas, fotos de ve&iacute;culos que j&aacute; estejam publicados , anuncio sem fotos, anuncio com fotos em ambiente de lojas de autom&oacute;veis ou revenda.<br />
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Tamb&eacute;m n&atilde;o ser&atilde;o aceitas imagens que n&atilde;o sejam do veiculo a venda.</p>
<p style="margin-left: 4.2pt; text-align: justify;">
    <br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    <span style="font-size:14px;"><strong>Tipos de ve&iacute;culos anunciados</strong></span><br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Trabalhamos apenas com a divulga&ccedil;&atilde;o espec&iacute;fica de autom&oacute;veis, motocicletas e caminh&otilde;es desde que n&atilde;o estejam sinistrados, batidos ou sem condi&ccedil;&otilde;es de uso. &nbsp;Caso tenha algum outro produto para venda como acess&oacute;rios, implementos agr&iacute;colas ou similares, favor n&atilde;o prosseguir no an&uacute;ncio pois o mesmo ser&aacute; removido.<br />
    <br />
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Em caso de suspeita de fraude, inconsist&ecirc;ncia nas informa&ccedil;&otilde;es ou den&uacute;ncia de terceiros com fundamentos, o an&uacute;ncio do ve&iacute;culo poder&aacute; ser suspenso e somente poder&aacute; ser reativado mediante o envio de c&oacute;pia do documento do ve&iacute;culo (DUT) que comprove a propriedade do mesmo. A <strong>SeminovosBH</strong> poder&aacute;, a qualquer momento, solicitar a voc&ecirc; documentos pessoais ou relacionados ao ve&iacute;culo anunciado.</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N&atilde;o ser&atilde;o aceitos nenhum tipo de servi&ccedil;o anexo ao veiculo publicado, tais como, carta de cr&eacute;dito,financiamento, consorcio contemplado ou n&atilde;o, ou qualquer tipo de servi&ccedil;o que n&atilde;o seja especificamente a venda do veiculo em quest&atilde;o.</p>
<p style="margin-left: 3.75pt; text-align: justify;">
    &nbsp;</p>
<p style="margin-left: 3.75pt;">
    <span style="font-size:14px;"><strong>Caso n&atilde;o se cumpra um &uacute;nico paragrafo dos itens acima mencionados, solicitamos que n&atilde;o prossiga no anuncio, sob pena de remo&ccedil;&atilde;o do mesmo sem o ressarcimento da importancia paga.</strong></span></p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    <span style="font-size:14px;"><strong>Formas de pagamento:</strong></span></p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dep&oacute;sito e ou Transfer&ecirc;ncia nos bancos Bradesco ou Ita&uacute;</p>
<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Boleto banc&aacute;rio (atrav&eacute;s do Pag Seguro)</p>
<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cart&atilde;o de d&eacute;bito e cr&eacute;dito (cielo , m&aacute;ster card e visa)</p>
<p>
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    <span style="font-size:14px;"><strong>Disposi&ccedil;&otilde;es Finais</strong></span></p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;&nbsp;&nbsp;Este Termo ter&aacute; vig&ecirc;ncia durante o per&iacute;odo de dura&ccedil;&atilde;o do an&uacute;ncio, <strong>podendo ser rescindido sem pr&eacute;via comunica&ccedil;&atilde;o</strong>, por descumprimento de obriga&ccedil;&otilde;es legais e/ ou das condi&ccedil;&otilde;es aqui previstas, incluindo: atos que possam configurar ind&iacute;cios de ocorr&ecirc;ncia dos crimes previstos nas leis? veicula&ccedil;&atilde;o de informa&ccedil;&otilde;es falsas? reaproveitamento de an&uacute;ncio? mal uso do espa&ccedil;o destinado a coloca&ccedil;&atilde;o de informa&ccedil;&otilde;es adicionais.</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp; Os direitos autorais e intelectuais do PORTAL pertencem exclusivamente &agrave; <strong>SeminovosBH</strong>, sendo vedada a c&oacute;pia, comercializa&ccedil;&atilde;o ou qualquer tipo de utiliza&ccedil;&atilde;o que n&atilde;o esteja prevista neste Termo ou no PORTAL.</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Voc&ecirc; declara que teve acesso, leu e n&atilde;o tem nenhuma d&uacute;vida sobre os Termos de Uso do Portal <strong>SeminovosBH</strong></p>
<p style="text-align: justify;">
    &nbsp;</p>
<p style="text-align: justify;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Por estarem de acordo com as condi&ccedil;&otilde;es estipuladas neste instrumento, as PARTES firmam o presente Contrato.</p>
<p>
    &nbsp;</p>
