<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
$this->headTitle('Termo de Adesão');

?>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-10 text-left">
            <h3 class="font-montserrat all-caps hint-text">TERMO DE RESPONSABILIDADE</h3>
        </div>
    </div>
</div>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div id="card-advance" class="card-default bg-white border">
                <div class="card-header bg-white border-white">
                    <div class="card-title">
                        <h2>TERMO DE ADESÃO SEMINOVOS - PESSOA FÍSICA</h2>
                    </div>
                </div>
                <div class="card-body">
                    <p class="text-justify">A <strong>Seminovos</strong> por se tratar de um portal de classificados virtuais de anuncios de veiculos, não se responsabiliza por qualquer dano e/ou prejuízo que o usuário possa sofrer ao realizar uma negociação com outros usuários deste web site tendo em vista que a negociação e pagamento são feitas entre as partes não tendo o site nenhuma participação. O objetivo do portal é a exibição pública dos anúncios feitos pelo anunciante, sendo assim todos os dados inseridos por ele tais como informações e fotos são de inteira responsabilidade do mesmo, tornando-se estes dados públicos.</p>
                    <p class="text-justify">As vendas, entregas e informações dos veículos anunciados , são de inteira responsabilidade do anunciante. A Seminovos não realiza a intermediação das vendas, compras, trocas ou qualquer outro tipo de transação feita pelos usuários de seu web site, somente disponibiliza informações lançadas pelo anunciante para que os interessados façam contato.</p>

                    <h3>1.Disposições Iniciais</h3>
                    <p class="text-justify">O anunciante é o único responsável pela veracidade das informações contidas nos anúncios que contratar, bem como pela conferência dos dados, cadastrados por ele, neste web site. A veiculação de informações falsas ou de titularidade de terceiros implicará na suspensão imediata da veiculação do anúncio, sujeitando o anunciante às ações legais cabíveis e perda do anúncio.</p>
                    <p class="text-justify"><strong>É proibido anunciar veículos de maneira que leve o comprador a erro ou que ludibrie o mesmo tais como veículo recuperado sem a informação, quilometragem adulterada e envolvimento em acidente que causou danos que não foram totalmente reparados sem a prévia informação. Caso chegue a nosso conhecimento este tipo de problema e seja verificado o anunciante será banido do site. No caso de descumprimento destas normas serão tomadas medidas legais, cíveis e criminais contra o anunciante e caso o site seja processado em conjunto com o anunciante será movida ação de regresso cobrando pelas despesas acarretadas pelo ato.</strong></p>
                    <p class="text-justify">A <strong>Seminovos</strong> não se responsabiliza por quaisquer danos diretos e/ou indiretos causados a terceiros, advindos da exibição dos anúncios em desacordo com as leis, pois se trata de portal e os anunciantes que inserem todos os dados.</p>
                    <p class="text-justify"> A <strong>Seminovos</strong> não garante o êxito de qualquer transação realizada pelos usuários deste web site. Esta empresa não se responsabiliza também pelo conteúdo das correspondências entre usuários em negociação, nem pelos contratos que estes venham a estabelecer com terceiros.nenhuma conversa de negociação é monitorada e toda a negociação é feita diretamente entre as partes (comprador e vendedor).</p>
                    <p class="text-justify"> Anúncios provenientes de revendedores, agências de automóveis ou que estejam em lojas sob forma de consignação,caso esteja anunciado no site como particular serão removidos do site deliberadamente sem ressarcimento do valor pago,caso seja confirmado tal ação.</p>

                    <h3>2.Prazo para renovação</h3>
                    <p class="text-justify">Todo anúncio feito no Portal por um dos planos pagos tem direito a veiculação no site até a venda, não sendo possível a substituição por outro veículo no mesmo anúncio entretanto o cliente deverá renová-lo sem ônus a cada 30 dias visando a atualização do site. Caso o cliente não  reative ou renove seu anuncio depois de 30 dias expirado, o mesmo será excluído do banco de dados perdendo o direito de renovação gratuita.</p>
                    <p class="text-justify"> Anúncios de veículos 0KM ou quilometragem até 500km tem prazo de veiculação de 30 dias não podendo ser renovado sem um novo pagamento.</p>
                    <p class="text-justify">Caso o anunciante coloque como vendido ou remova o anúncio, o mesmo perderá o direito de renovação sem ônus.</p>

                    <h3>3.Segurança das Informações</h3>
                    <p class="text-justify">Todos os dados pessoais informados ao nosso site são armazenados em um banco de dados criptografado, reservado e com acesso restrito.
                        Todos os dados cadastrados no sistema pelos seus usuários, serão armazenados em nosso banco de dados não cabendo ao usuário a remoção do mesmo. Assegurar a sua privacidade é mais um compromisso da <strong>Seminovos</strong> com você.</p>

                    <h4 class="text-justify text-amarelo bold">Apenas veiculos particulares serão aceitos neste formato de anuncio. </h4>

                    <h3>4.Particulares</h3>
                    <p class="text-justify font-italic">É todo anuncio, publicado feito por pessoa física sem fins lucrativos, que seja e esteja em posse do vendedor com DUT do veiculo em seu nome.</p>
                    <p class="text-justify font-italic">Não é permitido a veiculação de anúncios de revendas, lojistas ou quem faça da venda de veiculos seu negócio fim, fora da sua área específica.</p>
                    <p class="text-justify font-italic">Caso um veículo seja anunciado no portal como particular e o mesmo seja de revenda ou lojista ou tenha algum vinculo com os mesmos, (fotos, telefones etc..) este será removido do sistema sem o ressarcimento da importância paga.</p>
                    <p class="text-justify font-italic">Anúncios de carta de crédito ou consórcio só podem ser feitos por revendas nos termos do contrato aceito.</p>

                    <h3>5.Publicação e Alteração de Imagens</h3>
                    <p class="text-justify">Todo anúncio no site tem a opção de alteração de imagens do veículo, não sendo permitido a publicação de imagens com textos, descrições do veiculo ou qualquer informação publicitária.</p>
                    <p class="text-justify">Anúncios gratuitos não tem a opção de alteração ou inserção de novas imagens no site.  Informamos ainda que apenas as iniciais da placa serão exibidas. Mas aconselhamos o cliente a editar as fotos antes da publicação, visando omitir nas fotos os números da placa.</p>
                    <p class="text-justify">Solicitamos também, que o cliente antes de fazer seu anuncio, tire varias fotos do veículo a ser anunciado, pois não serão aceitos fotos ilustrativas, fotos de veículos que já estejam publicados , anuncio sem fotos, anuncio com fotos em ambiente de lojas de automóveis ou revenda.
                        Também não serão aceitas imagens que não sejam do veiculo a venda.</p>


                    <h36.>Tipos de veículos anunciados</h3>
                    <p class="text-justify">Trabalhamos apenas com a divulgação específica de automóveis, motocicletas e caminhões desde que não estejam sinistrados, batidos ou sem condições de uso.  Caso tenha algum outro produto para venda como acessórios, implementos agrícolas ou similares, favor não prosseguir no anúncio pois o mesmo será removido</p>
                    <p class="text-justify">Em caso de suspeita de fraude, inconsistência nas informações ou denúncia de terceiros com fundamentos, o anúncio do veículo poderá ser suspenso e somente poderá ser reativado mediante o envio de cópia do documento do veículo (DUT) que comprove a propriedade do mesmo. A <strong>Seminovos</strong> poderá, a qualquer momento, solicitar a você documentos pessoais ou relacionados ao veículo anunciado.</p>
                    <p class="text-justify">Não serão aceitos nenhum tipo de serviço anexo ao veiculo publicado, tais como, carta de crédito,financiamento, consorcio contemplado ou não, ou qualquer tipo de serviço que não seja especificamente a venda do veiculo em questão.</p>

                    <h4 class="text-justify text-amarelo bold">Caso não se cumpra um único paragrafo dos itens acima mencionados, solicitamos que não prossiga no anuncio, sob pena de remoção do mesmo sem o ressarcimento da importância paga.</h4>

                    <h3>7.Formas de pagamento</h3>
                    <p class="text-justify">Depósito e ou Transferência nos bancos Caixa Econômica e Inter</p>
                    <p class="text-justify">Boleto bancário</p>
                    <p class="text-justify">Cartão de crédito (cielo , máster card e visa)</p>

                    <h3>8.Disposições Finais</h3>
                    <p class="text-justify">Este Termo terá vigência durante o período de duração do anúncio, <strong>podendo ser rescindido sem prévia comunicação</strong>, por descumprimento de obrigações legais e/ ou das condições aqui previstas, incluindo: atos que possam configurar indícios de ocorrência dos crimes previstos nas leis? veiculação de informações falsas? reaproveitamento de anúncio? mal uso do espaço destinado a colocação de informações adicionais.</p>
                    <p class="text-justify">Os direitos autorais e intelectuais do PORTAL pertencem exclusivamente à <strong>Seminovos</strong>, sendo vedada a cópia, comercialização ou qualquer tipo de utilização que não esteja prevista neste Termo ou no PORTAL.</p>
                    <p class="text-justify text-center">Você declara que teve acesso, leu e não tem nenhuma dúvida sobre os Termos de Uso do Portal <strong>Seminovos</strong>.</p>
                    <p class="text-justify text-center">Por estarem de acordo com as condições estipuladas neste instrumento, as PARTES firmam o presente Contrato.</p>
                </div>
            </div>
        </div>
    </div>
</div>