<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headTitle('Termo de Adesão');

?>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-10 text-left">
            <h3 class="font-montserrat all-caps hint-text">POLÍTICA DE PRIVACIDADE</h3>
        </div>
    </div>
</div>
<div class=" container-fluid   container-fixed-lg">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div id="card-advance" class="card-default bg-white border">
                <div class="card-header bg-white border-white">
                    <div class="card-title">
                        <h2>POLÍTICA DE PRIVACIDADE - SEMINOVOS</h2>
                    </div>
                </div>
                <div class="card-body">
                    <h3>1.Informações do usuário</h3>
                    <p class="text-justify">Suas informações são importantes, pois nos ajudam a tornar o site um lugar
                        melhor e cada vez mais direcionado à você, usuário, na busca de sua total satisfação.</p>
                    <p class="text-justify"><strong>Sua privacidade é nossa preocupação. Temos o compromisso de
                            preservá-la.</strong></p>
                    <p class="text-justify">Nossa política de privacidade visa assegurar a garantia de que, quaisquer
                        informações relativas aos usuários, não serão fornecidas, publicadas ou comercializadas em
                        quaisquer circunstâncias. A Seminovos obtém informações dos usuários de duas maneiras:
                        Cadastro e Cookies.</p>

                    <h3>2.Cadastro</h3>
                    <p class="text-justify">Para usufruir dos benefícios adicionais do site e receber o email com
                        Ofertas Exclusivas, você precisa se cadastrar na Seminovos. Este cadastro é armazenado em um
                        banco de dados criptografado,protegido e sigiloso não sendo possivel a remoção do mesmo pelo
                        usuario. Qualquer comunicação enviada para seu email será através do boletim periódico da
                        Seminovos. Seu email não será divulgado.</p>

                    <h3>3.Cookies</h3>
                    <p class="text-justify">A Seminovos coleta informações através de cookies (informações enviadas
                        pelo servidor da Seminovos ao computador do usuário, para identificá-lo). Os cookies servem
                        unicamente para controle interno de audiência e de navegação e jamais para controlar,
                        identificar ou rastrear preferências do internauta, exceto quando este desrespeitar alguma regra
                        de segurança ou exercer alguma atividade prejudicial ao bom funcionamento do site, como por
                        exemplo tentativas de hackear o serviço. A aceitação dos cookies pode ser livremente alterada na
                        configuração de seu navegador.</p>

                    <h3>4.Segurança das informações</h3>
                    <p class="text-justify">Todos os dados pessoais informados ao nosso site são armazenados em um banco
                        de dados criptografado, reservado e com acesso restrito a alguns funcionários habilitados, que
                        são obrigados, por contrato, a manter a confidencialidade das informações e não utilizá-las
                        inadequadamente.</p>
                    <p class="text-justify">Todos os dados cadastrados no sistema pelos seus usuarios, serão armazenados
                        em nosso banco de dados não cabendo ao usuario a remoção do mesmo.Assegurar a sua privacidade é
                        mais um compromisso da Seminovos com você.</p>

                    <h3>5.Segurança do anunciante</h3>
                    <p class="text-justify">Se possivel leve o veículo pretendido a alguma empresa de sua confiança que
                        comprove a procedencia.</p>
                    <div class="">
                        <ul class="">
                            <li class="">Jamais faça depósitos ou efetive a compra do veículo sem antes fazer uma pré
                                vistoria no Detran da sua cidade ou algum órgão de vistoria veicular.
                            </li>
                            <li>Procure levantar o histórico do veículo através da placa, existem empresas
                                especializadas em checar o histórico do veículo.
                            </li>
                            <li>Sorteio? Herança? Brinde? Adiantamentos? Cuidado: essas são algumas das artimanhas
                                usadas para explicar preços "imperdíveis". Não caia nessa!
                            </li>
                            <li>Pesquise a veracidade do endereço e telefone do anunciante.</li>
                            <li>Descarte as ofertas de pessoas que afirmam serem funcionárias ou intermediárias de
                                fabricantes.
                            </li>
                            <li>Não forneça dados importantes em computadores públicos. Para saber se o ambiente
                                utilizado é seguro, o ícone do cadeado deve ser exibido na parte inferior na tela.
                            </li>
                            <li>Forneça seus dados apenas pessoalmente.</li>
                            <li>Exija que o documento esteja em nome do vendedor.</li>
                            <li>O comprador de um carro usado tem que conter sua empolgação de fechar um negócio que
                                parece irresistível, pois é preciso desconfiar de preços muito baixos e vantagens
                                milagrosas.
                            </li>
                            <li>Evite carros com "sinistrado" ou "REM" (chassi remarcado) no documento. Valem 30%
                                menos.
                            </li>
                            <li>Desconfie de ofertas abaixo do preço de mercado para veículos novos ou usados.</li>
                            <li>Nunca leve o veículo até o comprador.</li>
                            <li>Sempre solicite a ele ver o carro no local a ser escolhido por você.</li>
                            <li>Não forneça o endereço de sua casa.</li>
                            <li>Procure mostrar o veículo em local público de dia e acompanhado.</li>
                        </ul>
                    </div>

                    <h3>6.Aúncios e prazos</h3>
                    <p class="text-justify">Cada plano de anúncio particular permite o anúncio de um único veículo, não
                        podendo o usuário aproveitar-se do mesmo para negociar outro veículo.</p>

                    <h3>7.Prazo de renovação</h3>
                    <p class="text-justify">Todo anúncio feito no Portal por um dos planos pagos tem direito a
                        veiculação no site até a venda, ( exceto veículos Zero KM ou com quilometragem até 500KM )
                        entretanto o cliente deverá renová-lo sem ônus a cada 30 dias visando a atualização do site.
                        Caso o cliente não reative ou renove o anúncio após 30 dias de expirado, o mesmo será excluído
                        do banco de dados perdendo o direito de renovação gratuita.</p>
                    <p class="text-justify">Após publicados os anúncios não poderão ser suspensos ou pausados por
                        período determinado. Caso o cliente interrompa ou comunique venda do veículo, o anúncio não
                        poderá retornar ao ar sendo necessário um novo pagamento.</p>
                    <p class="text-justify">A <strong>Seminovos</strong> não se responsabiliza por qualquer dano e/ou
                        prejuízo que o usuário possa sofrer ao realizar uma negociação com outros usuários deste web
                        site.</p>
                    <p class="text-justify"><strong>Não nos responsabilizamos pelas imagens publicadas no site, bem como
                            seu conteúdo e subtração por terceiros com a finalidade de serem re-publicadas.</strong></p>
                    <p class="text-justify">As vendas e entregas dos veículos anunciados a terceiros, usuários deste web
                        site, são de inteira responsabilidade do anunciante. A Seminovos não realiza a intermediação
                        das vendas, compras, trocas ou qualquer outro tipo de transação feita pelos usuários de seu web
                        site.</p>
                    <p class="text-justify">O anunciante é o único responsável pela veracidade das informações contidas
                        nos anúncios que contratar, bem como pela conferência dos dados, cadastrados por ele, neste web
                        site. A veiculação de informações falsas ou de titularidade de terceiros implicará na suspensão
                        imediata da veiculação do anúncio, sujeitando o anunciante às ações legais cabíveis.</p>
                    <p class="text-justify">A Seminovos não se responsabiliza por quaisquer danos diretos e/ou
                        indiretos causados a terceiros, advindos da exibição dos anúncios em desacordo com as Leis
                        Criminal, Civil e em especial ao Código Brasileiro de Defesa do Consumidor, por parte do
                        anunciante.</p>
                    <p class="text-justify">A Seminovos não garante o êxito de qualquer transação realizada pelos
                        usuários deste web site. Esta empresa não se responsabiliza também pelo conteúdo das
                        correspondências entre usuários em negociação, nem pelos contratos que estes venham a
                        estabelecer com terceiros.</p>
                    <p class="text-justify">Anúncios provenientes de revendedores, agências de automóveis ou que estejam
                        em lojas sob forma de consignação,caso esteja anunciado no site como particular serão removidos
                        do site deliberadamente sem ressarcimento do valor pago,caso seja confirmado tal ação.</p>
                    <p class="text-justify">Anuncios feitos como forma de pagamento deposito em conta, tem prazo maximo
                        de 30 dias para informação dos dados bancarios para publicação.</p>

                    <h3>8.Revenda X Particular</h3>
                    <h5>8.1.Particular</h5>
                    <p class="text-justify">É todo anuncio, publicado feito por pessoa física sem fins lucrativos, que
                        seja e esteja em posse do vendedor com DUT do veiculo em seu nome.</p>
                    <p class="text-justify">Não é permitido a veiculação de anúncios de revendas, lojistas ou quem faça
                        da venda de veiculos seu negócio fim, fora da sua área específica.</p>
                    <p class="text-justify">Caso um veículo seja anunciado no portal como particular e o mesmo seja de
                        revenda ou lojista ou tenha algum vinculo com os mesmos, ( fotos, telefones etc...) este será
                        removido do sistema sem o ressarcimento da importância paga.</p>
                    <p class="text-justify">Anúncios de carta de crédito ou consórcio só podem ser feitos por revendas
                        nos termos do contrato aceito.</p>
                    <p class="text-justify">Não trabalhamos com Anuncio de carta de crédito ou consórcio sendo
                        publicados como particulares.</p>
                    <p class="text-justify">Anuncio de veiculos Zero Km particulares diferentemente dos veiculos
                        semi-novos, terão prazo de publicação maxima de 30 dias.</p>
                    <h5>8.2.Revenda</h5>
                    <p class="text-justify">Anuncios publicados por Logistas ou revendedores em area expecifica para
                        venda, desde que devidamente inscrito no cadastro nacional da pessoa juridica comprovando sua
                        situação cadastral ativa.</p>

                    <h3>9.Publicação e alteração de imagens</h3>
                    <p class="text-justify">Todo anúncio no site tem a opção de alteração de imagens do veículo, não sendo permitido a
                        publicação de imagens com textos, descrições do veiculo ou qualquer informação publicitaria.</p>
                    <p class="text-justify">Anúncios gratuitos não tem a opção de alteração ou inserção de novas imagens
                        no site. Informamos ainda que apenas as iniciais da placa serão exibidas. Mas aconselhamos o
                        cliente a editar as fotos antes da publicação, visando omitir nas fotos os numeros da placa.</p>
                    <p class="text-justify">Solicitamos também, que o cliente antes de fazer seu anúncio, tire várias
                        fotos do veículo a ser anunciado, <strong>pois não serão aceitas fotos ilustrativas, fotos que
                            não sejam do veículo em questão, fotos retiradas de outros portais de internet, fotos que
                            contenham dizeres ou exponham pessoas, fotos de veículos que já estejam publicados ou
                            anúncios sem fotos</strong>.</p>
                    <p class="text-justify"><strong>Não serão aceitas imagens que não sejam do veiculo a venda.</strong>
                    </p>
                    <p class="text-justify">Em caso de suspeita de fraude, inconsistência nas informações ou denúncia de
                        terceiros, o anúncio do veículo será suspenso e somente poderá ser reativado mediante o envio de
                        cópia do documento do veículo (DUT) juntamente com documentação do anunciante para que se
                        comprove a propriedade do mesmo.</p>

                    <h3>10.Tipos de veículos anunciados</h3>
                    <p class="text-justify">Trabalhamos apenas com divulgação específica de automóveis, motocicletas e
                        caminhões desde que não estejam sinistrados. Infelizmente não publicamos no site veículos
                        batidos, avariados ou sem condições de uso.</p>
                    <p class="text-justify">Não serão aceitos nenhum tipo de serviço anexo ao veiculo publicado, tais
                        como, carta de credito,financiamento, consorcio contemplado ou não, ou qualquer tipo de serviço
                        que não seja expecificamente a venda do veiculo em questão.</p>

                </div>
            </div>
        </div>
    </div>
</div>