<?php

$prioridadeNomes = [
    1 => 'máxima',
    2 => 'máxima',
    3 => 'alta',
    4 => 'média',
    5 => 'mínima',
];

$slug = [
    1 => 'nitro',
    2 => 'nitro',
    3 => 'turbo',
    4 => 'flex',
    5 => 'simples',
];

$corTxt = [
    1 => 'text-nitro',
    2 => 'text-nitro',
    3 => 'text-turbo',
    4 => 'text-flex',
    5 => 'text-simples',
];

$desabilitarPlano = false;
$desabilitarPlanoRenda = false;
$planoAtual = ($idPlanoAtual == $plano['idPlano']);
$isGratis = $plano['idPlano'] == 1;

$diminuirPlano = $prioridadePlano >= $plano['prioridade'];
if ($isRevenda && $plano['qtd']['publicado'] == $plano['qtd']['total']) {
    $desabilitarPlanoRenda = true;
}
if (($idStatusAnuncio ?? false) && ($idStatusAnuncio == 6 || $idStatusAnuncio == 10 || $idStatusAnuncio == 3 || ($idStatusAnuncio == 4 && $zeroKm))) {
    $diminuirPlano = true;
    $planoAtual = false;
}
if (($idStatusAnuncio ?? false) && ($plano['idPlano'] ?? 0) == 1 && $idStatusAnuncio == 4 && $zeroKm) {
    $desabilitarPlano = true;
}
if ($isRevenda) {
    $diminuirPlano = true;
}

$nomePlano = $plano['nomePlano'] == "Grátis" ? "Grátis" : $plano['nomePlano'];
$nomePlano = mb_strtoupper($nomePlano);

$valorPlano = explode(',', number_format((float) $plano['valorPlano'], 2, ',', '.'));

?>

	<div class="plano-card">

		<div class="plano-inner-card">

			<h3>
				<span>Plano</span>
				<?= $nomePlano ?>
			</h3>

			<!-- PREÇO -->
			<div class="preco">
				<span class="moeda">R$</span>
				<span class="valor"><?= $valorPlano[0] ?></span>
				<span class="centavos">,<?= $valorPlano[1] ?></span>
			</div>

			<!-- LISTA -->
			<ul>
				<?php if ($plano['prioridade'] == 1 && !$isRevenda): ?>
					<li>
						<i class="fa fa-plus-square"></i>
						<div class="item-texto">
							Exibição na Home por 30 dias<br>(renováveis)
						</div>
					</li>
				<?php endif; ?>

				<li>
					<i class="fa fa-plus-square"></i>
					<div class="item-texto">
						<?= $isGratis ? 'Apenas ' : '' ?><?= $plano['quantidadeFotos'] ?> fotos
					</div>
				</li>

				<li>
					<i class="fa fa-plus-square"></i>
					<div class="item-texto">
						<?= $slug[$plano['prioridade']] == 'nitro' ? '1 vídeo' : 'Sem vídeos' ?>
					</div>
				</li>

				<?php if (!$isRevenda): ?>
					<li>
						<i class="fa fa-plus-square"></i>
						<div class="item-texto">
							<?php
							if ($isGratis) {
								echo "Exibição no site por <b>{$plano['dias']} dias</b>";
							} else {
								echo "Exibição no site até a venda*";
							}
							?>
						</div>
					</li>
				<?php endif; ?>

				<li>
					<i class="fa fa-plus-square"></i>
					<div class="item-texto">
						Prioridade <b><?= $prioridadeNomes[$plano['prioridade']] ?></b>
					</div>
				</li>

				<?php if ($isGratis && !$isRevenda): ?>
					<li>
						<i class="fa fa-plus-square"></i>
						<div class="item-texto">
							O mesmo veículo só pode ser anunciado uma única vez gratuitamente.
						</div>
					</li>
				<?php endif; ?>
			</ul>

		</div>

		<!-- INPUT RADIO -->
		<input
			type="radio"
			id="radio-idPlano-<?= $plano['idPlano'] ?>"
			name="idPlano"
			value="<?= $plano['idPlano'] ?>"
			class="input-radio-plano"
			<?= ($desabilitarPlano || $desabilitarPlanoRenda || !$diminuirPlano) ? 'disabled' : '' ?>
			data-valor-plano="<?= $plano['valorPlano'] ?>"
			style="height:0!important"
		>

		<!-- BOTÃO -->
        <label
            class="btn-escolher"
            for="radio-idPlano-<?= $plano['idPlano'] ?>"
            <?= $diminuirPlano ? '' : 'data-plano-desativado' ?>
            <?= $desabilitarPlanoRenda ? 'data-plano-revenda-desativado' : '' ?>
            <?= $planoAtual ? 'data-plano-atual' : '' ?>>
            <?= $planoAtual ? 'SEU PLANO ATUAL' : 'Escolher <strong>' . $nomePlano . '</strong>' ?>
        </label>

	</div>