<?php
/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

$isRevenda = $this->userInfo('tipoCadastro') == 1;
$isParticular = !$isRevenda;

$idPlanoAtual ??= false;
$idStatusAnuncio ??= false;
$zeroKm ??= false;

usort($planos, function ($a, $b) {
    return $b['ordem'] <=> $a['ordem'];
});



if ($isRevenda) {
    $qtdAnuncios = $this->qtdAnuncios()->getData();

    $planosMap = [
        5 => [
            'publicado' => 'totalBasicoPublicado',
            'total' => 'totalBasico',
        ],
        2 => [
            'publicado' => 'totalTurboPublicados',
            'total' => 'totalTurbo',
        ],
        3 => [
            'publicado' => 'totalNitroPublicados',
            'total' => 'totalNitro',
        ]
    ];
    foreach ($planos as &$plano) {
        $m = $planosMap[$plano['idPlano']];

        $plano['qtd'] = [
            'publicado' => $qtdAnuncios[$m['publicado']],
            'total' => $qtdAnuncios[$m['total']],
        ];
    }
    unset($plano);
}

?>
<div class="container">
    <h4 class="text-center">
        PLANOS DE ANÚNCIOS
    </h4>
    <div class="text-center my-3">
        <small class="align-center">
            Escolha o plano que atende às suas necessidades e pode dar o destaque que você quer ao seu veículo.
            <br />Analise os Planos de Anúncios abaixo e conheça as vantagens de cada plano:
        </small>
    </div>

    <div class="row-full">
        <div class="container">
            <form id="form_Plano" name="form_Plano">
                <div class="row grupo-planos">
                    <?php
                    $planoJaEscolhido = false;
                    $prioridadePlano ??= 5;
                    $planoGratis = false;
                    foreach ($planos as $k => $plano) :
                        if ($plano['valorPlano'] == '0.0') {
                            $planoGratis = $plano;
                            continue;
                        }
                        echo $this->partial('./box-plano.phtml', [
                            'k' => $k,
                            'planoJaEscolhido' => $planoJaEscolhido,
                            'plano' => $plano,
                            'prioridadePlano' => $prioridadePlano,
                            'isRevenda' => $isRevenda,
                            'isParticular' => $isParticular,
                            'idPlanoAtual' => $idPlanoAtual,
                            'idStatusAnuncio' => $idStatusAnuncio,
                            'zeroKm' => $zeroKm,
                        ]);
                    endforeach;
                    ?>
                </div>
                <div>
                    <?php if ($isParticular && $prioridadePlano >= $planoGratis['prioridade']) : ?>
                        <div class="row mt-1 mb-4">
                            <div class="col col-md-4 offset-md-4 text-center">
                                <div>
                                    <a
                                        data-toggle="collapse"
                                        href="#planoSimplesCollapse"
                                        role="button"
                                        aria-expanded="false"
                                        aria-controls="planoSimples"
                                        class="btn btn-block btn-sm bg-light text-dark text-bold"
                                    >Escolher Plano Grátis</a>
                                </div>
                            </div>
                        </div>
                        <div id="planoSimplesCollapse" class="row mt-2 collapse">
                            <div class="col-md-4 offset-md-4 text--center">
                                <?= $this->partial('./box-plano.phtml', [
                                    'k' => $k,
                                    'planoJaEscolhido' => $planoJaEscolhido,
                                    'plano' => $planoGratis,
                                    'prioridadePlano' => $prioridadePlano,
                                    'isRevenda' => $isRevenda,
                                    'isParticular' => $isParticular,
                                    'idPlanoAtual' => $idPlanoAtual,
                                    'idStatusAnuncio' => $idStatusAnuncio,
                                    'zeroKm' => $zeroKm,
                                ]) ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="alert-primary row-full">
                        <div class="container">
                            <div class=" row  justify-content-center text-justify p-4">
                                <div class="d-none d-md-block col-md-1 align-self-center">
                                    <i class="icon icon-alert"></i>
                                </div>
                                <div class="col-12 col-md-6 align-baseline">
                                    <h5 class="text-left bold">Reativação dos anúncios</h5>
                                    <ul class="list-unstyled">
                                        <li>
                                            Nos planos Nitro, Turbo, Flex e Básico, para que seja mantida a condição de
                                            exibição
                                            do seu anúncio até a venda, é necessário a reativação do anúncio a cada 30 dias (sem
                                            custo
                                            adicional).
                                        </li>
                                        <br/>
                                        <li class="text-danger">
                                            * Caso o anunciante coloque como vendido ou remova o anúncio, o mesmo perderá o direito de renovação sem ônus.  
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-12 col-md-5 border-left border-primary border-sm-0">
                                    <h5 class="bold">Para veículos 0km</h5>
                                    <ul class="list-unstyled">
                                        <li>
                                            Anúncios de veículos 0km terá o prazo de exibição no site limitado a 30 dias, sem
                                            direito a
                                            renovação gratuita.
                                        </li>
                                        <li>
                                            A renovação do anúncio de veículos 0km, será cobrado novamente conforme plano
                                            selecionado.
                                        </li>
                                        <li>
                                            Anúncios de veículos 0km que não estiverem listados como tal, serão removidos
                                            deliberadamente após o prazo de 30 dias e deverão pagar por um novo anúncio para
                                            reativar o
                                            mesmo.
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <input type="submit">
                    </div>
            </form>
        </div>
    </div>
</div>