<div class="container">
    <div class="row">
        <div class="col-md-6 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
        <div class="col-md-6">
            <div class="col-md-6">

                <div id="box_concluido">


                    <div class="mensagem_pendente">
                        <p style="color:#da5228; font-size:18px;font-weight: bold;"><?php echo $this->texto ?></p><br><br>
                        <p style="color:#acacac; font-size:14px;font-weight: bold; margin-bottom: 20px;">Após confirmação do pagamento no prazo de 24 horas o anúncio será ativado</p>
                        <p style="font-weight: bold;color:#333;margin-top: 10px">Obrigado por anunciar conosco.</p>
                        <p style="color:#acacac; font-size:14px;font-weight: bold; margin-top: 20px; float:right;">Equipe SeminovosBH!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>