<div class="container container-fixed-lg bg-white">
    <div class="row">
        <div class="col-12 m-t-20 text-center">
            <h3 style="color:#da5228;">Obrigado por anunciar conosco.</h3>
        </div>
        <div class="col-md-12 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
    </div>
    <div class="mx-auto py-2 mt-2" style="width: 75%; background-color: lightgray;">
        <p class="mx-5 my-1">Após confirmação do pagamento no prazo de 24 horas o anúncio será ativado.</p>
    </div>
    <div class="mx-auto py-4 text-center">
            <p style="font-weight: bold;color:#333;">Obrigado por anunciar conosco.</p>
            <p style="color:#acacac; font-size:14px;font-weight: bold;">Equipe SeminovosBH!</p>
    </div>
</div>