<div class="container container-fixed-lg bg-white">
    <div class="row">
        <div class="col-12 m-t-20 text-center">
            <h3 style="color:#da5228;">PARABÉNS!</h3>
            <h4>O SEU ANÚNCIO FOI CRIADO COM SUCESSO.</h4>
        </div>
        <div class="col-md-12 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
        
        <div class="mx-auto py-4" style="width: 75%;">


            <div class="mensagem_pendente pl-3">
                <?= $this->partial('partials/share', ['veiculo' => $this->veiculo]) ?>
            </div>
        </div>
    </div>
    <div class="mx-auto py-2" style="width: 75%; background-color: lightgray;">
        <p class="mx-5">O seu anúncio pode levar até 60 minutos para ser publicado no nosso portal. Nesse tempo ele será checado pela nossa equipe que pode entrar em contato para conferencia de alguns dados se for necessário.</p>
        <p class="mx-5">Assim que seu veículo for publicado nós te avisaremos! </p>
    </div>
    <div class="mx-auto py-4 text-center">
            <p style="font-weight: bold;color:#333;">Obrigado por anunciar conosco.</p>
            <p style="color:#acacac; font-size:14px;font-weight: bold;">Equipe SeminovosBH!</p>
    </div>
</div>