<div class="container">
    <div class="row">
        <div class="col-md-6 text-center">
            <img src="/img/pagamento/obrigado.jpg" /> 
        </div>
        <div class="col-md-6">
            <div class="mensagem_pendente">
                <p style="color:#da5228; font-size:18px;font-weight: bold;">Parabéns,</p>
                <p style="color:#acacac; font-size:14px;font-weight: bold; margin-bottom: 20px;">Seu plano foi renovado com sucesso.</p>
                <p style="font-weight: bold;color:#333;margin-top: 10px">Obrigado por anunciar conosco.</p>
                <p style="color:#acacac; font-size:14px;font-weight: bold; margin-top: 20px; float:right;">Equipe SeminovosBH!</p>
            </div>
            <?= $this->partial('partials/share', ['veiculo' => $this->veiculo]) ?>
        </div>

    </div>
</div>

