<?php
/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */
$this->headTitle()->setSeparator(' - ')->append('Seminovos.com.br');
$assetSufix = APPLICATION_ENV === 'development' ? random_int(0, 64_456_645) . '-development' : APPLICATION_VERSION;
/**
 * @todo Melhorar essa página de 404
 */
$this->headTitle();

?>
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <?php echo $this->headTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <!--<link href="assets/plugins/pace/pace-theme-flash.css?<?= $assetSufix ?>" rel="stylesheet" type="text/css" />-->

    <link class="main-stylesheet" href="/css/app.css?<?= $assetSufix ?>" rel="stylesheet" type="text/css" />
    <script src="/js/app.js?<?= $assetSufix ?>" async></script>

    <script type="text/javascript">
        window.onload = function ()
        {
          // fix for windows 8
          if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
            document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
    <?php if (IS_PROD): ?>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-WMZDL2D');</script>
    <?php endif;?>
  </head>
  <body class="fixed-header l-blank <?=$this->bodyClass()?>">
    <?= $this->content ?>
    <?= $this->jsMcvPartial() ?>
  </body>
</html>
