<?php
/** @var \AreaRestrita\View\Helper\AutocompleteClass $this */
$this->headTitle()->setSeparator(' - ')->append('Seminovos.com.br');

$assetSufix = APPLICATION_ENV === 'development' ? random_int(0, 64_456_645) . '-development' : APPLICATION_VERSION;
?>
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <?php echo $this->headTitle() ?>
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/css/app.css?<?= $assetSufix ?>" media="screen" rel="stylesheet" type="text/css">
    <?php if (IS_PROD): ?>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WMZDL2D');</script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1006006929"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1006006929'); </script>
    <?php endif;?>
</head>

<body class="fixed--header l-criar-anuncio <?= $this->bodyClass() ?>">
    <div class="page-container p-0 ">
        <div class="hea-der">

            <div class="container">
                <div class="row">
                    <div class="col-md-2 mt-0 mt-md-2 p-3 text-center">
                        <a href="/meus-veiculos" title="Voltar para meus veículos">
                            <svg viewBox="0 0 180 66" alt="logo" width="78" height="29" class="snbh-logo">
                                <use xlink:href="/img/svg/logo.svg#layer_letters" class="layer-letters"></use>
                                <use xlink:href="/img/svg/logo.svg#layer_car" class="layer-car"></use>
                            </svg>
                        </a>
                    </div>
                    <div class="col-lg-8 mt-0 mt-md-3 px-0 px-md-5 step-list-container">
                        <ul class="steps-list p-0 justify-content-center px-3 px-md-5">
                            <li title="Seu dados" data-step="usuario">
                                <svg viewBox="0 0 42 42" alt="usuário">
                                    <use xlink:href="/img/svg/icons/user.svg#icon"></use>
                                </svg>
                            </li>
                            <li title="Dados do seu veículo" data-step="dados,preco,mais-informacoes">
                                <svg viewBox="0 0 42 42" alt="veículo">
                                    <use xlink:href="/img/svg/icons/ad-car.svg#body"></use>
                                    <use xlink:href="/img/svg/icons/ad-car.svg#light-1" style="fill:#fff"></use>
                                    <use xlink:href="/img/svg/icons/ad-car.svg#light-2" style="fill:#fff"></use>
                                </svg>
                            </li>
                            <li title="Fotos do veículo" data-step="fotos,video">
                                <svg viewBox="0 0 16 16" alt="fotos">
                                    <use xlink:href="/img/svg/icons/photos.svg#cam"></use>
                                </svg>
                            </li>
                            <li title="Planos de Anúncio" data-step="plano">
                                <svg viewBox="0 0 100 100" alt="plano">
                                    <use xlink:href="/img/svg/icons/ad-plan.svg#item-1"></use>
                                    <use xlink:href="/img/svg/icons/ad-plan.svg#item-2"></use>
                                    <use xlink:href="/img/svg/icons/ad-plan.svg#item-3"></use>
                                </svg>
                            </li>
                            <li title="Pagamento" data-step="checkout">
                                <svg viewBox="0 0 42 42" alt="pagamento">
                                    <use xlink:href="/img/svg/icons/ad-payment.svg#icon"></use>
                                </svg>
                            </li>
                            <li title="Conclusão" data-step="finalizar">
                                <svg viewBox="0 0 42 42" alt="concluído">
                                    <use xlink:href="/img/svg/icons/check.svg#circle"></use>
                                    <use xlink:href="/img/svg/icons/check.svg#check" style="fill:#fff"></use>
                                </svg>
                            </li>
                        </ul>

                    </div>
                </div>

            </div>


        </div>
        <div class="page-content-wrapper">
            <div class="content">
                <div class="container">
                    <div class="row">
                        <!-------->

                    </div>
                </div>
                <div class="container-fluid container-fixed-lg">
                    <?= $this->content ?>
                </div>
            </div>

        </div>
    </div>
    <div class="footer pl-0 pr-0 d-flex w-100 justify-content-center copyright">
        <div class="sm-text-center pt-1">
            <p class="small font-montserrat no-margin pull-left sm-pull-reset">
                <span class="hint-text mr-2">Copyright &copy; <?= date("Y") ?> </span>
                <span class="hint-text mr-2">seminovos.com.br</span>
                <span class="hint-text">Todos direitos reservados</span>
            </p>
            <div class="clearfix"></div>
        </div>
    </div>
    <script src="/js/app.js?<?= $assetSufix ?>" async="true"></script>
    <?= $this->jsMcvPartial() ?>
    <script>
! function(f, b, e, v, n, t, s) {
    if (f.fbq) return;
    n = f.fbq = function() {
        n.callMethod ?
            n.callMethod.apply(n, arguments) : n.queue.push(arguments)
    };
    if (!f._fbq) f._fbq = n;
    n.push = n;
    n.loaded = !0;
    n.version = '2.0';
    n.queue = [];
    t = b.createElement(e);
    t.async = !0;
    t.src = v;
    s = b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t, s)
}(window, document, 'script',
    'https://connect.facebook.net/en_US/fbevents.js');
</script>
</body>

</html>
