<?php
/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

?>
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Pages - Admin Dashboard UI Kit - Blank Page</title>
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
  <link rel="apple-touch-icon" href="pages/ico/60.png">
  <link rel="apple-touch-icon" sizes="76x76" href="pages/ico/76.png">
  <link rel="apple-touch-icon" sizes="120x120" href="pages/ico/120.png">
  <link rel="apple-touch-icon" sizes="152x152" href="pages/ico/152.png">
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <!--<link href="assets/plugins/pace/pace-theme-flash.css" rel="stylesheet" type="text/css" />-->
  <!--<link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />-->
  <!--<link href="assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css" />-->
  <link href="/css/app.css?<?= rand(0, 1000) ?>" media="screen" rel="stylesheet" type="text/css">
  <!--<link class="main-stylesheet" href="pages/css/pages.css" rel="stylesheet" type="text/css" />-->
  <!--<link href="assets/plugins/jquery-scrollbar/jquery.scrollbar.css" rel="stylesheet" type="text/css" media="screen" />-->
  <!--<link href="assets/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" media="screen" />-->
  <!--<link href="assets/plugins/switchery/css/switchery.min.css" rel="stylesheet" type="text/css" media="screen" />-->
  <!--<link href="pages/css/pages-icons.css" rel="stylesheet" type="text/css">-->

</head>

<body class="fixed-header desktop pace-done pace-done menu-unpinned menu-pin l-layout <?= $this->bodyClass() ?>">
  <nav class="page-sidebar animated" data-pages="sidebar">
    <div class="sidebar-header">
      <svg viewBox="0 0 180 66" width="90" height="33" class="snbh-logo inverse brand">
        <use xlink:href="/img/svg/snbh_logo.svg#layer_letters" class="layer-letters"></use>
        <use xlink:href="/img/svg/snbh_logo.svg#layer_car" class="layer-car"></use>
      </svg>
      <div class="sidebar-header-controls">
        <button type="button" class="btn btn-link hidden-md-down" data-toggle-pin="sidebar"><i class="fa fs-12"></i>
        </button>
      </div>
    </div>
    <?php
      if ($this->userInfo('tipoCadastro') == 1) {
          echo $this->partial('partials/menu-revenda.phtml');
          $arrayPlanos = [
              1 => ['nitro',      'Nitro',      '12',  'alta',    '', '', 'nitro-value', $this->qtdAnuncios()->totalNitro, $this->qtdAnuncios()->totalNitroPublicados],
              2 => ['turbo',      'Turbo',      '09',  'média',   '', '', 'turbo-value', $this->qtdAnuncios()->totalTurbo, $this->qtdAnuncios()->totalTurboPublicados],
              3 => ['basico',     'Básico',     '06',  'baixa',   '', '', 'basic-value', $this->qtdAnuncios()->totalBasico, $this->qtdAnuncios()->totalBasicoPublicado],
          ];
      } else if ($this->userInfo('tipoCadastro') == 2) {
          echo $this->partial('partials/menu-particular.phtml');
          $arrayPlanos = [
              1 => ['nitro-home', 'Nitro Home', '12',  'máxima',  '', 'R$ 49,90', 'nitro-home-value', $this->qtdAnuncios()->totalNitroHome, $this->qtdAnuncios()->totalNitroHomePublicados],
              2 => ['nitro',      'Nitro',      '12',  'alta',    '', 'R$ 39,90', 'nitro-value', $this->qtdAnuncios()->totalNitro, $this->qtdAnuncios()->totalNitroPublicados],
              3 => ['turbo',      'Turbo',      '09',  'média',   '', 'R$ 29,90', 'turbo-value', $this->qtdAnuncios()->totalTurbo, $this->qtdAnuncios()->totalTurboPublicados],
              4 => ['basico',     'Básico',     '06',  'baixa',   '', 'R$ 14,90', 'basic-value', $this->qtdAnuncios()->totalBasico, $this->qtdAnuncios()->totalBasicoPublicado],
              5 => ['simples',    'Simples',    '03',  'mínima',  '', 'Grátis',   'simple-value', $this->qtdAnuncios()->totalGratuito, $this->qtdAnuncios()->totalGratuitoPublicado],
          ];
      }

      ?>
  </nav>

  <div class="page-container">
    <div class="header d-flex justify-content-around">
      <a href="#" class="btn-link toggle-sidebar pg pg-menu" data-toggle="sidebar">
        <span class="thumbnail-wrapper d32 circular inline">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </span>
      </a>
      <div class="d-flex">
        <?php  foreach ($arrayPlanos as $i => $plano): list($slug, $plano, $fotos, $nivel, $video, $preco, $classValue, $totalAnuncio, $totalAnuncioPublicado) = $plano; ?>
        <div class="mx-3 justify-content-start d-flex align-items-center">
          <div class="linha-plano size-3x plano-<?= $slug ?> m-0">
            <div class="icon-plano m-0">
              <span class="bar-1"></span>
              <span class="bar-2"></span>
              <span class="bar-3"></span>
              <span class="bar-4"></span>
              <span class="bar-4"></span>
            </div>
          </div>
          <div class="text-left ml-2">
            <div>
              <b><?= $plano ?></b>
            </div>
            <div>
              <?php echo $totalAnuncioPublicado . "/" . $totalAnuncio ?>
            </div>
          </div>


        </div>
        <?php endforeach; ?>
      </div>


      <div class="d-flex align-items-center">
        <div class="pull-left p-r-10 fs-14 font-heading hidden-md-down">
          <span class="semi-bold"><?= $this->userInfo('responsavelNome') ?></span>
        </div>
        <div class="dropdown pull-right hidden-md-down">
          <?php /* <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <span class="thumbnail-wrapper d32 circular inline">
              <i class="fa fa-bars" aria-hidden="true"></i>
            
                  <!-- echo $this->userInfo()->getImgPerfil();
                  echo '<img src="assets/img/profiles/avatar.jpg" alt="" data-src="assets/img/profiles/avatar.jpg" data-src-retina="assets/img/profiles/avatar_small2x.jpg" width="32" height="32">'; -->


          </span> */ ?>
          </button>
          <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
            <a href="<?= $this->url('restrito/meus-dados') ?>" class="dropdown-item"><i class="pg-settings_small"></i>
              Meus dados</a>
            <a href="<?= $this->url('logout') ?>" class="clearfix bg-master-lighter dropdown-item">
              <span class="pull-left">Sair</span>
              <span class="pull-right"><i class="pg-power"></i></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="page-content-wrapper">
      <div class="content">
        <?= $this->content ?>
      </div>
      <div class=" container-fluid  container-fixed-lg footer">
        <div class="copyright sm-text-center">
          <p class="small no-margin pull-left sm-pull-reset">
            <span class="hint-text">Copyright &copy; 2018 </span>
            <span class="font-montserrat">SeminovosBH</span>.
            <span class="hint-text">Todos direitos reservados</span>
          </p>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
  <script src="/js/app.js?<?= rand(0, 1000) ?>" async="true"></script>
</body>

</html>