<?php
/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */
$this->headTitle()->setSeparator(' - ')->append('Meus Anúncios')->append('Seminovos.com.br');

$assetSufix = APPLICATION_ENV === 'development' ? random_int(0, 64_456_645) . '-development' : APPLICATION_VERSION;

global $container;
$url = $container->get('Config')['SnBH']['urls']['site'] ?? "/meus_veiculos";

?>
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <?php echo $this->headTitle() ?>
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/css/app.css?<?= $assetSufix ?>" media="screen" rel="stylesheet" type="text/css">
    <?php if (IS_PROD): ?>
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WMZDL2D');</script>
    <?php endif;?>
</head>

<body
    class="fixed-header desktop pace-done menu-behind pace-done menu-unpinned menu-pin l-layout <?= $this->bodyClass() ?>">
    <nav class="page-sidebar animated" data-pages="sidebar">
        <div class="sidebar-header d-flex d-md-none justify-content-center mt-0">
            <a href="<?= $url . '?' . substr(time(), 0, 4) ?>" title="Voltar para o site seminovos.com.br">
                <svg viewBox="0 0 180 66" width="90" height="33" class="snbh-logo inverse brand">
                    <use xlink:href="/img/svg/logo.svg#layer_letters" class="layer-letters"></use>
                    <use xlink:href="/img/svg/logo.svg#layer_car" class="layer-car"></use>
                </svg>
            </a>
        </div>
        <?php
      if ($this->userInfo('tipoCadastro') == 1) {
    $arrayPlanos = [
        1 => ['nitro',      'Nitro',      '15',  'alta',    '', '', 'nitro-value', $this->qtdAnuncios()->totalNitro, $this->qtdAnuncios()->totalNitroPublicados],
        2 => ['turbo',      'Turbo',      '09',  'média',   '', '', 'turbo-value', $this->qtdAnuncios()->totalTurbo, $this->qtdAnuncios()->totalTurboPublicados],
        3 => ['basico',     'Básico',     '06',  'baixa',   '', '', 'basic-value', $this->qtdAnuncios()->totalBasico, $this->qtdAnuncios()->totalBasicoPublicado],
    ];
    $data = [
      "arrayPlanos" => $arrayPlanos,
      "dataExpiracaoRevenda" => $this->expiracaoRevenda()->dataExpiracaoRevenda,
      "diasParaExpirar" => $this->expiracaoRevenda()->diasParaExpirar,
    ];
    echo $this->partial('partials/menu-revenda.phtml',$data);
} elseif ($this->userInfo('tipoCadastro') == 2) {
    echo $this->partial('partials/menu-particular.phtml');
}

      ?>
    </nav>

    <div class="page-container">
        <div class="header d-flex justify-content-around">
            <a href="#" class="btn-link toggle-sidebar d-lg-none" data-toggle="sidebar">
                <span class="thumbnail-wrapper d32 circular inline">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </span>
            </a>
            <div class="sidebar-header">
                <a  href="<?= $url . '?' . substr(time(), 0, 4) ?>" title="Voltar para o site seminovos.com.br">
                    <svg viewBox=" 0 0 180 66" width="90" height="33" class="snbh-logo inverse brand">
                        <use xlink:href="/img/svg/logo.svg#layer_letters"></use>
                        <use xlink:href="/img/svg/logo.svg#layer_car" class="layer-car"></use>
                    </svg>
                </a>
            </div>
            <div class="d-flex align-items-center ml-auto">
                <?php if($this->userInfo('tipoCadastro') == AreaRestrita\Model\Cadastros::TIPO_CADASTRO_REVENDA) { ?>
                    <a target="_blank" href="https://autoconecta.com.br/auth/login" class="btn btn-info text-white" style="background-color:#2081C3;border-color:#2081C3;margin-right:10px;">Acesse o Repasse Auto Conecta</a> 
                <?php } ?>
                <div class="dropdown pull-right d-block">
                    <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <div class="p-r-10 fs-14 font-heading hidden-md-down">
                            <?php
                if($this->userInfo('tipoCadastro')!== null){ 
                  if($this->userInfo('tipoCadastro') == 1) {
                    $new_nome = $this->userInfo('nomeFantasia');
                  }
                  elseif ($this->userInfo('tipoCadastro') == 2){
                    $new_nome = $this->userInfo('responsavelNome');
                  }
                  if ($new_nome) {
                    $new_nome = explode(" ",(string) $new_nome);
                    $new_nome = $new_nome[0] . " " . ($new_nome[1] ?? '');
                  } else {
                    $new_nome = "Não informado";
                  }
                }else{
                  $new_nome = "Não informado";
                }
                ?>
                            <span class="semi-bold d-block">
                                <?= $new_nome ?>
                                <i class="fa fa-angle-down ml-1" aria-hidden="true"></i>
                            </span>
                        </div>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu" x-placement="bottom-end"
                        style="position: absolute; transform: translate3d(-94px, 34px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <a href="<?= $this->url('restrito/meus-dados') ?>" class="dropdown-item"
                            title="Meus dados de cadastro">
                            <i class="fa fa-cogs" aria-hidden="true"></i> Meus Dados
                        </a>
                        <a href="<?= $this->url('restrito/alterar-senha') ?>" class="dropdown-item"
                            title="Alterar minha senha">
                            <i class="fa fa-lock" aria-hidden="true"></i> Alterar Senha
                        </a>
                        <a href="<?= $this->url('logout') ?>" class="clearfix bg-master-lighter dropdown-item">
                            <i class="fa fa-sign-out" aria-hidden="true"></i> Sair
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-content-wrapper">
            <div class="content pb-0">
                <?= $this->content ?>
            </div>
            <div class="footer d-flex w-100 justify-content-center copyright">
                <div class="sm-text-center pt-1">
                    <p class="small font-montserrat no-margin pull-left sm-pull-reset">
                        <span class="hint-text mr-2">Copyright &copy; <?= date("Y") ?> </span>
                        <span class="hint-text mr-2">Seminovos.com</span>
                        <span class="hint-text">Todos direitos reservados</span>
                    </p>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="/js/app.js?<?= $assetSufix ?>" async="true"></script>
  </div>

<div class="modal fade" id="modalTipoAnuncio" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header p-0">
                <div class="w-100 text-center mb-2"><h5 class="m-0">O que deseja vender?</h5></div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0">
                <div class="d-flex justify-content-center">
                    <a class="link-tipo" data-confirm href="/carro">
                        <div>
                            <i class="fa-2x icon icon-type-car-2"></i><br>
                            Carro
                        </div>
                    </a>
                    <a class="link-tipo" data-confirm href="/moto">
                        <div>
                            <i class="fa-2x icon icon-type-moto-2"></i><br>
                            Moto
                        </div>
                    </a>
                    <a class="link-tipo" data-confirm href="/caminhao">
                        <div>
                            <i class="fa-2x icon icon-type-truck-2"></i><br>
                            Caminhão
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
  <?php /*<script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
  <script src="/js/app.js?<?= $assetSufix ?>" async="true"></script>*/ ?>
</body>

</html>
