<?php
/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

$assetSufix = APPLICATION_ENV === 'development' ? rand(0, 64456645) . '-development' : APPLICATION_VERSION;

?>
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Meus Anúncios - Seminovos.com.br</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <link class="main-stylesheet" href="/css/app.css?<?= $assetSufix ?>" rel="stylesheet" type="text/css" />
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-5Z5MTSZ');</script>
</head>

<body class="fixed-header l-login <?= $this->bodyClass() ?>">
  <div class="login-wrapper d-flex justify-content-center bg-white">
    <?php /*
    <div class="bg-pic bg-light">
        // Quando tiver uma imagem colocar nessa tag
        if (0):
            ?>
      <img src="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg"
        data-src="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg"
        data-src-retina="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" alt="" class="lazy">
      <?php endif; ?>
      <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
      </div>
    </div>
    */?>
    <div class="login-container bg-white">
      <div class="px-4 px-md-5 mx-md-3 py-3 py-md-5">
        <?= $this->content ?>
      </div>
    </div>
  </div>
  <script src="/js/app.js?<?= $assetSufix ?>" async></script>
</body>
</html>