<?php
/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <meta charset="utf-8" />
        <title>Pages - Admin Dashboard UI Kit - Lock Screen</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
        <link rel="apple-touch-icon" href="pages/ico/60.png">
        <link rel="apple-touch-icon" sizes="76x76" href="pages/ico/76.png">
        <link rel="apple-touch-icon" sizes="120x120" href="pages/ico/120.png">
        <link rel="apple-touch-icon" sizes="152x152" href="pages/ico/152.png">
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-touch-fullscreen" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta content="" name="description" />
        <meta content="" name="author" />
        <link href="assets/plugins/pace/pace-theme-flash.css" rel="stylesheet" type="text/css" />

        <link class="main-stylesheet" href="/css/app.css" rel="stylesheet" type="text/css" />
        <script src="/js/app.js" async></script>

        <script type="text/javascript">
            window.onload = function ()
            {
                // fix for windows 8
                if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                    document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
            }
        </script>
    </head>
    <body class="fixed-header l-login <?= $this->bodyClass() ?>">
        <div class="login-wrapper ">
            <div class="bg-pic">
                <img src="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" data-src="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" data-src-retina="assets/img/demo/new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg" alt="" class="lazy">
                <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
                </div>
            </div>
            <div class="login-container bg-white">
                <div class="p-l-50 m-l-20 p-r-50 m-r-20 p-t-50 m-t-30 sm-p-l-15 sm-p-r-15 sm-p-t-40">

                    <!-- START Login Form -->
                    <?= $this->content ?>
                    <?php /*
                      <form id="form-login" class="p-t-15" role="form" action="index.html">
                      <!-- START Form Control-->
                      <div class="form-group form-group-default">
                      <label>Login</label>
                      <div class="controls">
                      <input type="text" name="username" placeholder="User Name" class="form-control" required>
                      </div>
                      </div>
                      <!-- END Form Control-->
                      <!-- START Form Control-->
                      <div class="form-group form-group-default">
                      <label>Password</label>
                      <div class="controls">
                      <input type="password" class="form-control" name="password" placeholder="Credentials" required>
                      </div>
                      </div>
                      <!-- START Form Control-->
                      <div class="row">
                      <div class="col-md-6 no-padding sm-p-l-10">
                      <div class="checkbox ">
                      <input type="checkbox" value="1" id="checkbox1">
                      <label for="checkbox1">Keep Me Signed in</label>
                      </div>
                      </div>
                      <div class="col-md-6 d-flex align-items-center justify-content-end">
                      <a href="#" class="text-info small">Help? Contact Support</a>
                      </div>
                      </div>
                      <!-- END Form Control-->
                      <button class="btn btn-primary btn-cons m-t-10" type="submit">Sign in</button>
                      </form>
                     */ ?>
                </div>
            </div>
            <!-- END Login Right Container-->
        </div>


        <script src="assets/plugins/pace/pace.min.js" type="text/javascript"></script><!--
        <script src="assets/plugins/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
        <script src="assets/plugins/modernizr.custom.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="assets/plugins/tether/js/tether.min.js" type="text/javascript"></script>
        <script src="assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery/jquery-easy.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery-ios-list/jquery.ioslist.min.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery-actual/jquery.actual.min.js"></script>
        <script src="assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script type="text/javascript" src="assets/plugins/select2/js/select2.full.min.js"></script>
        <script type="text/javascript" src="assets/plugins/classie/classie.js"></script>
        <script src="assets/plugins/switchery/js/switchery.min.js" type="text/javascript"></script>
        <script src="assets/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>-->
        <!-- END VENDOR JS -->
        <!--<script src="pages/js/pages.min.js"></script>-->
    </body>
</html>

<?php
# $this->content ?>