<?php
$currentUrl = $this->serverUrl(true);
$isRedirect = preg_match('/redirect=/', $currentUrl);

/* @var $this \AreaRestrita\View\Helper\AutocompleteClass */

$assetSufix = APPLICATION_ENV === 'development' ? rand(0, 64456645) . '-development' : APPLICATION_VERSION;

?>
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Meus Anúncios - Seminovos.com.br</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <link class="main-stylesheet" href="/css/app.css?<?= $assetSufix ?>" rel="stylesheet" type="text/css" />
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-5Z5MTSZ');</script>
</head>

<body class="fixed-header l-login <?= $this->bodyClass() ?> container-fluid <?= $isRedirect ? 'intro-off' : '' ?>">
    <div class="col-12 col-md-12">
        <?= $this->content ?>
    </div>
    <script src="/js/app.js?<?= $assetSufix ?>" async="true"></script>
</body>
</html>