<div class="col-6 col-sm-4 col-md-2 card bg-dark m--0 mb-2">
    <div class="card-header row text-center text-white">
        <b><?= $header ?></b>
    </div>
    <div class="card-body row text-white p-0">
        <?php if ($textB) : ?>
            <div class="col-6 border-right-c border-s-2">
                <?= $textA ?>
            </div>
            <div class="col-6 text-center">
                <?= $textB ?>
            </div>
        <?php else : ?>
            <?= $textA ?>
        <?php endif; ?>

    </div>

</div>